// Programmatically generated by gen_structs.py
package get_workers_response

import "encoding/xml"

type GetWorkersResponse struct {
    XMLName xml.Name `xml:"Get_Workers_Response"`
    Version *string `xml:"version,attr,omitempty"`
    RequestReferences *RequestReferences `xml:"Request_References,omitempty"`
    RequestCriteria *RequestCriteria `xml:"Request_Criteria,omitempty"`
    ResponseFilter *ResponseFilter `xml:"Response_Filter,omitempty"`
    ResponseGroup *ResponseGroup `xml:"Response_Group,omitempty"`
    ResponseResults *ResponseResults `xml:"Response_Results,omitempty"`
    ResponseData *ResponseData `xml:"Response_Data,omitempty"`
}

type RequestReferences struct {
    SkipNonExistingInstances *string `xml:"Skip_Non_Existing_Instances,attr,omitempty"`
    IgnoreInvalidReferences *string `xml:"Ignore_Invalid_References,attr,omitempty"`
    WorkerReference *WorkerReference `xml:"Worker_Reference,omitempty"`
}

type WorkerReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Id struct {
    Type *string `xml:"type,attr,omitempty"`
    Value *string `xml:",chardata"`
    ParentId *string `xml:"parent_id,attr,omitempty"`
    ParentType *string `xml:"parent_type,attr,omitempty"`
    SystemId *string `xml:"System_ID,attr,omitempty"`
}

type RequestCriteria struct {
    TransactionLogCriteriaData *TransactionLogCriteriaData `xml:"Transaction_Log_Criteria_Data,omitempty"`
    OrganizationReference *OrganizationReference `xml:"Organization_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    IncludeSubordinateOrganizations *bool `xml:"Include_Subordinate_Organizations,omitempty"`
    PositionReference *PositionReference `xml:"Position_Reference,omitempty"`
    EventReference *EventReference `xml:"Event_Reference,omitempty"`
    BenefitPlanReference *BenefitPlanReference `xml:"Benefit_Plan_Reference,omitempty"`
    FieldAndParameterCriteriaData *FieldAndParameterCriteriaData `xml:"Field_And_Parameter_Criteria_Data,omitempty"`
    NationalIdCriteriaData *NationalIdCriteriaData `xml:"National_ID_Criteria_Data,omitempty"`
    ExcludeInactiveWorkers *bool `xml:"Exclude_Inactive_Workers,omitempty"`
    ExcludeEmployees *bool `xml:"Exclude_Employees,omitempty"`
    ExcludeContingentWorkers *bool `xml:"Exclude_Contingent_Workers,omitempty"`
    EligibilityCriteriaData *EligibilityCriteriaData `xml:"Eligibility_Criteria_Data,omitempty"`
    UniversalIdReference *UniversalIdReference `xml:"Universal_ID_Reference,omitempty"`
}

type TransactionLogCriteriaData struct {
    TransactionDateRangeData *TransactionDateRangeData `xml:"Transaction_Date_Range_Data,omitempty"`
    TransactionTypeReferences *TransactionTypeReferences `xml:"Transaction_Type_References,omitempty"`
    SubscriberReference *SubscriberReference `xml:"Subscriber_Reference,omitempty"`
}

type TransactionDateRangeData struct {
    UpdatedFrom *string `xml:"Updated_From,omitempty"`
    UpdatedThrough *string `xml:"Updated_Through,omitempty"`
    EffectiveFrom *string `xml:"Effective_From,omitempty"`
    EffectiveThrough *string `xml:"Effective_Through,omitempty"`
}

type TransactionTypeReferences struct {
    TransactionTypeReference *TransactionTypeReference `xml:"Transaction_Type_Reference,omitempty"`
}

type TransactionTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SubscriberReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type OrganizationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CountryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PositionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EventReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type BenefitPlanReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type FieldAndParameterCriteriaData struct {
    ProviderReference *ProviderReference `xml:"Provider_Reference,omitempty"`
}

type ProviderReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type NationalIdCriteriaData struct {
    IdentifierId *string `xml:"Identifier_ID,omitempty"`
    NationalIdTypeReference *NationalIdTypeReference `xml:"National_ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
}

type NationalIdTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EligibilityCriteriaData struct {
    FieldReference *FieldReference `xml:"Field_Reference,omitempty"`
    AsOfEffectiveDate *string `xml:"As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"As_Of_Entry_DateTime,omitempty"`
}

type FieldReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type UniversalIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ResponseFilter struct {
    AsOfEffectiveDate *string `xml:"As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"As_Of_Entry_DateTime,omitempty"`
    Page *int `xml:"Page,omitempty"`
    Count *int `xml:"Count,omitempty"`
}

type ResponseGroup struct {
    IncludeReference *bool `xml:"Include_Reference,omitempty"`
    IncludePersonalInformation *bool `xml:"Include_Personal_Information,omitempty"`
    ShowAllPersonalInformation *bool `xml:"Show_All_Personal_Information,omitempty"`
    IncludeAdditionalJobs *bool `xml:"Include_Additional_Jobs,omitempty"`
    IncludeEmploymentInformation *bool `xml:"Include_Employment_Information,omitempty"`
    IncludeCompensation *bool `xml:"Include_Compensation,omitempty"`
    IncludeOrganizations *bool `xml:"Include_Organizations,omitempty"`
    ExcludeOrganizationSupportRoleData *bool `xml:"Exclude_Organization_Support_Role_Data,omitempty"`
    ExcludeLocationHierarchies *bool `xml:"Exclude_Location_Hierarchies,omitempty"`
    ExcludeCostCenters *bool `xml:"Exclude_Cost_Centers,omitempty"`
    ExcludeCostCenterHierarchies *bool `xml:"Exclude_Cost_Center_Hierarchies,omitempty"`
    ExcludeCompanies *bool `xml:"Exclude_Companies,omitempty"`
    ExcludeCompanyHierarchies *bool `xml:"Exclude_Company_Hierarchies,omitempty"`
    ExcludeMatrixOrganizations *bool `xml:"Exclude_Matrix_Organizations,omitempty"`
    ExcludePayGroups *bool `xml:"Exclude_Pay_Groups,omitempty"`
    ExcludeRegions *bool `xml:"Exclude_Regions,omitempty"`
    ExcludeRegionHierarchies *bool `xml:"Exclude_Region_Hierarchies,omitempty"`
    ExcludeSupervisoryOrganizations *bool `xml:"Exclude_Supervisory_Organizations,omitempty"`
    ExcludeTeams *bool `xml:"Exclude_Teams,omitempty"`
    ExcludeCustomOrganizations *bool `xml:"Exclude_Custom_Organizations,omitempty"`
    IncludeRoles *bool `xml:"Include_Roles,omitempty"`
    IncludeManagementChainData *bool `xml:"Include_Management_Chain_Data,omitempty"`
    IncludeMultipleManagersInManagementChainData *bool `xml:"Include_Multiple_Managers_in_Management_Chain_Data,omitempty"`
    IncludeBenefitEnrollments *bool `xml:"Include_Benefit_Enrollments,omitempty"`
    IncludeBenefitEligibility *bool `xml:"Include_Benefit_Eligibility,omitempty"`
    IncludeRelatedPersons *bool `xml:"Include_Related_Persons,omitempty"`
    IncludeQualifications *bool `xml:"Include_Qualifications,omitempty"`
    IncludeEmployeeReview *bool `xml:"Include_Employee_Review,omitempty"`
    IncludeGoals *bool `xml:"Include_Goals,omitempty"`
    IncludeDevelopmentItems *bool `xml:"Include_Development_Items,omitempty"`
    IncludeSkills *bool `xml:"Include_Skills,omitempty"`
    IncludePhoto *bool `xml:"Include_Photo,omitempty"`
    IncludeWorkerDocuments *bool `xml:"Include_Worker_Documents,omitempty"`
    IncludeTransactionLogData *bool `xml:"Include_Transaction_Log_Data,omitempty"`
    IncludeSubeventsForCorrectedTransaction *bool `xml:"Include_Subevents_for_Corrected_Transaction,omitempty"`
    IncludeSubeventsForRescindedTransaction *bool `xml:"Include_Subevents_for_Rescinded_Transaction,omitempty"`
    IncludeSuccessionProfile *bool `xml:"Include_Succession_Profile,omitempty"`
    IncludeTalentAssessment *bool `xml:"Include_Talent_Assessment,omitempty"`
    IncludeEmployeeContractData *bool `xml:"Include_Employee_Contract_Data,omitempty"`
    IncludeContractsForTerminatedWorkers *bool `xml:"Include_Contracts_for_Terminated_Workers,omitempty"`
    IncludeCollectiveAgreementData *bool `xml:"Include_Collective_Agreement_Data,omitempty"`
    IncludeProbationPeriodData *bool `xml:"Include_Probation_Period_Data,omitempty"`
    IncludeExtendedEmployeeContractDetails *bool `xml:"Include_Extended_Employee_Contract_Details,omitempty"`
    IncludeFeedbackReceived *bool `xml:"Include_Feedback_Received,omitempty"`
    IncludeUserAccount *bool `xml:"Include_User_Account,omitempty"`
    IncludeCareer *bool `xml:"Include_Career,omitempty"`
    IncludeAccountProvisioning *bool `xml:"Include_Account_Provisioning,omitempty"`
    IncludeBackgroundCheckData *bool `xml:"Include_Background_Check_Data,omitempty"`
    IncludeContingentWorkerTaxAuthorityFormInformation *bool `xml:"Include_Contingent_Worker_Tax_Authority_Form_Information,omitempty"`
    ExcludeFunds *bool `xml:"Exclude_Funds,omitempty"`
    ExcludeFundHierarchies *bool `xml:"Exclude_Fund_Hierarchies,omitempty"`
    ExcludeGrants *bool `xml:"Exclude_Grants,omitempty"`
    ExcludeGrantHierarchies *bool `xml:"Exclude_Grant_Hierarchies,omitempty"`
    ExcludeBusinessUnits *bool `xml:"Exclude_Business_Units,omitempty"`
    ExcludeBusinessUnitHierarchies *bool `xml:"Exclude_Business_Unit_Hierarchies,omitempty"`
    ExcludePrograms *bool `xml:"Exclude_Programs,omitempty"`
    ExcludeProgramHierarchies *bool `xml:"Exclude_Program_Hierarchies,omitempty"`
    ExcludeGifts *bool `xml:"Exclude_Gifts,omitempty"`
    ExcludeGiftHierarchies *bool `xml:"Exclude_Gift_Hierarchies,omitempty"`
    ExcludeRetireeOrganizations *bool `xml:"Exclude_Retiree_Organizations,omitempty"`
}

type ResponseResults struct {
    TotalResults *int `xml:"Total_Results,omitempty"`
    TotalPages *int `xml:"Total_Pages,omitempty"`
    PageResults *int `xml:"Page_Results,omitempty"`
    Page *int `xml:"Page,omitempty"`
}

type ResponseData struct {
    Worker *Worker `xml:"Worker,omitempty"`
}

type Worker struct {
    WorkerReference *WorkerReference `xml:"Worker_Reference,omitempty"`
    WorkerDescriptor *string `xml:"Worker_Descriptor,omitempty"`
    UniversalIdentifierReference *UniversalIdentifierReference `xml:"Universal_Identifier_Reference,omitempty"`
    WorkerData *WorkerData `xml:"Worker_Data,omitempty"`
}

type UniversalIdentifierReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkerData struct {
    WorkerId *string `xml:"Worker_ID,omitempty"`
    UserId *string `xml:"User_ID,omitempty"`
    UniversalId *string `xml:"Universal_ID,omitempty"`
    PersonalData *PersonalData `xml:"Personal_Data,omitempty"`
    EmploymentData *EmploymentData `xml:"Employment_Data,omitempty"`
}

type PersonalData struct {
    UniversalId *string `xml:"Universal_ID,omitempty"`
    NameData *NameData `xml:"Name_Data,omitempty"`
    PersonalInformationData *PersonalInformationData `xml:"Personal_Information_Data,omitempty"`
    IdentificationData *IdentificationData `xml:"Identification_Data,omitempty"`
    ContactData *ContactData `xml:"Contact_Data,omitempty"`
    TobaccoUse *bool `xml:"Tobacco_Use,omitempty"`
}

type NameData struct {
    LegalNameData *LegalNameData `xml:"Legal_Name_Data,omitempty"`
    PreferredNameData *PreferredNameData `xml:"Preferred_Name_Data,omitempty"`
    AdditionalNameData *AdditionalNameData `xml:"Additional_Name_Data,omitempty"`
}

type LegalNameData struct {
    NameDetailData *NameDetailData `xml:"Name_Detail_Data,omitempty"`
}

type NameDetailData struct {
    FormattedName *string `xml:"Formatted_Name,attr,omitempty"`
    ReportingName *string `xml:"Reporting_Name,attr,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    PrefixData *PrefixData `xml:"Prefix_Data,omitempty"`
    FirstName *string `xml:"First_Name,omitempty"`
    MiddleName *string `xml:"Middle_Name,omitempty"`
    LastName *string `xml:"Last_Name,omitempty"`
    SecondaryLastName *string `xml:"Secondary_Last_Name,omitempty"`
    TertiaryLastName *string `xml:"Tertiary_Last_Name,omitempty"`
    LocalNameDetailData *LocalNameDetailData `xml:"Local_Name_Detail_Data,omitempty"`
    SuffixData *SuffixData `xml:"Suffix_Data,omitempty"`
    FullNameForSingaporeAndMalaysia *string `xml:"Full_Name_for_Singapore_and_Malaysia,omitempty"`
}

type PrefixData struct {
    TitleReference *TitleReference `xml:"Title_Reference,omitempty"`
    TitleDescriptor *string `xml:"Title_Descriptor,omitempty"`
    SalutationReference *SalutationReference `xml:"Salutation_Reference,omitempty"`
}

type TitleReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SalutationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LocalNameDetailData struct {
    LocalName *string `xml:"Local_Name,attr,omitempty"`
    LocalScript *string `xml:"Local_Script,attr,omitempty"`
    FirstName *string `xml:"First_Name,omitempty"`
    MiddleName *string `xml:"Middle_Name,omitempty"`
    LastName *string `xml:"Last_Name,omitempty"`
    SecondaryLastName *string `xml:"Secondary_Last_Name,omitempty"`
    FirstName2 *string `xml:"First_Name_2,omitempty"`
    MiddleName2 *string `xml:"Middle_Name_2,omitempty"`
    LastName2 *string `xml:"Last_Name_2,omitempty"`
    SecondaryLastName2 *string `xml:"Secondary_Last_Name_2,omitempty"`
}

type SuffixData struct {
    SocialSuffixReference *SocialSuffixReference `xml:"Social_Suffix_Reference,omitempty"`
    SocialSuffixDescriptor *string `xml:"Social_Suffix_Descriptor,omitempty"`
    AcademicSuffixReference *AcademicSuffixReference `xml:"Academic_Suffix_Reference,omitempty"`
    HereditarySuffixReference *HereditarySuffixReference `xml:"Hereditary_Suffix_Reference,omitempty"`
    HonorarySuffixReference *HonorarySuffixReference `xml:"Honorary_Suffix_Reference,omitempty"`
    ProfessionalSuffixReference *ProfessionalSuffixReference `xml:"Professional_Suffix_Reference,omitempty"`
    ReligiousSuffixReference *ReligiousSuffixReference `xml:"Religious_Suffix_Reference,omitempty"`
    RoyalSuffixReference *RoyalSuffixReference `xml:"Royal_Suffix_Reference,omitempty"`
}

type SocialSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AcademicSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HereditarySuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HonorarySuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ProfessionalSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ReligiousSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type RoyalSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PreferredNameData struct {
    NameDetailData *NameDetailData `xml:"Name_Detail_Data,omitempty"`
}

type AdditionalNameData struct {
    NameDetailData *NameDetailData `xml:"Name_Detail_Data,omitempty"`
    NameTypeReference *NameTypeReference `xml:"Name_Type_Reference,omitempty"`
}

type NameTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PersonalInformationData struct {
    PersonalInformationForCountryData *PersonalInformationForCountryData `xml:"Personal_Information_For_Country_Data,omitempty"`
    BirthDate *string `xml:"Birth_Date,omitempty"`
    DateOfDeath *string `xml:"Date_of_Death,omitempty"`
    CountryOfBirthReference *CountryOfBirthReference `xml:"Country_of_Birth_Reference,omitempty"`
    CountryRegionOfBirthReference *CountryRegionOfBirthReference `xml:"Country_Region_of_Birth_Reference,omitempty"`
    RegionOfBirthDescriptor *string `xml:"Region_of_Birth_Descriptor,omitempty"`
    CityOfBirth *string `xml:"City_of_Birth,omitempty"`
    CityOfBirthReference *CityOfBirthReference `xml:"City_of_Birth_Reference,omitempty"`
    CitizenshipStatusReference *CitizenshipStatusReference `xml:"Citizenship_Status_Reference,omitempty"`
    PrimaryNationalityReference *PrimaryNationalityReference `xml:"Primary_Nationality_Reference,omitempty"`
    AdditionalNationalitiesReference *AdditionalNationalitiesReference `xml:"Additional_Nationalities_Reference,omitempty"`
    LastMedicalExamValidTo *string `xml:"Last_Medical_Exam_Valid_To,omitempty"`
    LastMedicalExamDate *string `xml:"Last_Medical_Exam_Date,omitempty"`
    MedicalExamNotes *string `xml:"Medical_Exam_Notes,omitempty"`
    BloodTypeReference *BloodTypeReference `xml:"Blood_Type_Reference,omitempty"`
    MilitaryServiceData *MilitaryServiceData `xml:"Military_Service_Data,omitempty"`
    SexualOrientationReference *SexualOrientationReference `xml:"Sexual_Orientation_Reference,omitempty"`
    GenderIdentityReference *GenderIdentityReference `xml:"Gender_Identity_Reference,omitempty"`
    PronounReference *PronounReference `xml:"Pronoun_Reference,omitempty"`
    NonCountrySpecificSectionData *NonCountrySpecificSectionData `xml:"Non_Country_Specific_Section_Data,omitempty"`
}

type PersonalInformationForCountryData struct {
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    CountryPersonalInformationData *CountryPersonalInformationData `xml:"Country_Personal_Information_Data,omitempty"`
}

type CountryPersonalInformationData struct {
    MaritalStatusReference *MaritalStatusReference `xml:"Marital_Status_Reference,omitempty"`
    MaritalStatusDate *string `xml:"Marital_Status_Date,omitempty"`
    ReligionReference *ReligionReference `xml:"Religion_Reference,omitempty"`
    DisabilityStatusData *DisabilityStatusData `xml:"Disability_Status_Data,omitempty"`
    EthnicityReference *EthnicityReference `xml:"Ethnicity_Reference,omitempty"`
    RaceEthnicityDetailsReference *RaceEthnicityDetailsReference `xml:"Race_Ethnicity_Details_Reference,omitempty"`
    EthnicityVisualSurveyReference *EthnicityVisualSurveyReference `xml:"Ethnicity_Visual_Survey_Reference,omitempty"`
    HispanicOrLatino *bool `xml:"Hispanic_or_Latino,omitempty"`
    HispanicOrLatinoVisualSurvey *bool `xml:"Hispanic_or_Latino_Visual_Survey,omitempty"`
    AboriginalIndigenousIdentificationReference *AboriginalIndigenousIdentificationReference `xml:"Aboriginal_Indigenous_Identification_Reference,omitempty"`
    AboriginalIndigenousIdentificationDetailsReference *AboriginalIndigenousIdentificationDetailsReference `xml:"Aboriginal_Indigenous_Identification_Details_Reference,omitempty"`
    HukouRegionReference *HukouRegionReference `xml:"Hukou_Region_Reference,omitempty"`
    HukouSubregionReference *HukouSubregionReference `xml:"Hukou_Subregion_Reference,omitempty"`
    HukouLocality *string `xml:"Hukou_Locality,omitempty"`
    HukouPostalCode *string `xml:"Hukou_Postal_Code,omitempty"`
    HukouTypeReference *HukouTypeReference `xml:"Hukou_Type_Reference,omitempty"`
    LocalHukou *bool `xml:"Local_Hukou,omitempty"`
    NativeRegionReference *NativeRegionReference `xml:"Native_Region_Reference,omitempty"`
    NativeRegionDescriptor *string `xml:"Native_Region_Descriptor,omitempty"`
    PersonnelFileAgencyForPerson *string `xml:"Personnel_File_Agency_for_Person,omitempty"`
    PoliticalAffiliationReference *PoliticalAffiliationReference `xml:"Political_Affiliation_Reference,omitempty"`
    SocialBenefitsLocalityReference *SocialBenefitsLocalityReference `xml:"Social_Benefits_Locality_Reference,omitempty"`
    RelativeNameInformationData *RelativeNameInformationData `xml:"Relative_Name_Information_Data,omitempty"`
    SexualOrientationAndGenderIdentityReference *SexualOrientationAndGenderIdentityReference `xml:"Sexual_Orientation_and_Gender_Identity_Reference,omitempty"`
    GenderReference *GenderReference `xml:"Gender_Reference,omitempty"`
    ReportingGenderReference *ReportingGenderReference `xml:"Reporting_Gender_Reference,omitempty"`
    VeteransPreferenceReference *VeteransPreferenceReference `xml:"Veterans_Preference_Reference,omitempty"`
    VeteransPreferenceForRifReference *VeteransPreferenceForRifReference `xml:"Veterans_Preference_For_RIF_Reference,omitempty"`
    SelectiveServiceRegistrationReference *SelectiveServiceRegistrationReference `xml:"Selective_Service_Registration_Reference,omitempty"`
    DisabledVeteranLeaveDateReference *string `xml:"Disabled_Veteran_Leave_Date_Reference,omitempty"`
    ActiveMilitaryUniformedServiceReference *ActiveMilitaryUniformedServiceReference `xml:"Active_Military_Uniformed_Service_Reference,omitempty"`
    UniformServiceReserveStatusReference *UniformServiceReserveStatusReference `xml:"Uniform_Service_Reserve_Status_Reference,omitempty"`
    CountrySpecificSectionData *CountrySpecificSectionData `xml:"Country_Specific_Section_Data,omitempty"`
}

type MaritalStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ReligionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DisabilityStatusData struct {
    DisabilityReference *DisabilityReference `xml:"Disability_Reference,omitempty"`
    DisabilityStatusDate *string `xml:"Disability_Status_Date,omitempty"`
    DisabilityDateKnown *string `xml:"Disability_Date_Known,omitempty"`
    DisabilityEndDate *string `xml:"Disability_End_Date,omitempty"`
    DisabilityGradeReference *DisabilityGradeReference `xml:"Disability_Grade_Reference,omitempty"`
    DisabilityDegree *int `xml:"Disability_Degree,omitempty"`
    DisabilityRemainingCapacity *int `xml:"Disability_Remaining_Capacity,omitempty"`
    DisabilityCertificationAuthorityReference *DisabilityCertificationAuthorityReference `xml:"Disability_Certification_Authority_Reference,omitempty"`
    DisabilityCertificationAuthority *string `xml:"Disability_Certification_Authority,omitempty"`
    DisabilityCertifiedAt *string `xml:"Disability_Certified_At,omitempty"`
    DisabilityCertificationId *string `xml:"Disability_Certification_ID,omitempty"`
    DisabilityCertificationBasisReference *DisabilityCertificationBasisReference `xml:"Disability_Certification_Basis_Reference,omitempty"`
    DisabilitySeverityRecognitionDate *string `xml:"Disability_Severity_Recognition_Date,omitempty"`
    DisabilityFteTowardQuota *int `xml:"Disability_FTE_Toward_Quota,omitempty"`
    DisabilityWorkRestrictions *string `xml:"Disability_Work_Restrictions,omitempty"`
    DisabilityAccommodationsRequested *string `xml:"Disability_Accommodations_Requested,omitempty"`
    DisabilityAccommodationsProvided *string `xml:"Disability_Accommodations_Provided,omitempty"`
    DisabilityRehabilitationRequested *string `xml:"Disability_Rehabilitation_Requested,omitempty"`
    DisabilityRehabilitationProvided *string `xml:"Disability_Rehabilitation_Provided,omitempty"`
    Note *string `xml:"Note,omitempty"`
    WorkerDocumentReference *WorkerDocumentReference `xml:"Worker_Document_Reference,omitempty"`
    DisabilityStatusReference *DisabilityStatusReference `xml:"Disability_Status_Reference,omitempty"`
}

type DisabilityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DisabilityGradeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DisabilityCertificationAuthorityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DisabilityCertificationBasisReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkerDocumentReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DisabilityStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EthnicityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type RaceEthnicityDetailsReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EthnicityVisualSurveyReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AboriginalIndigenousIdentificationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AboriginalIndigenousIdentificationDetailsReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HukouRegionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HukouSubregionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HukouTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type NativeRegionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PoliticalAffiliationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SocialBenefitsLocalityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type RelativeNameInformationData struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    RelativeNameReferenceReference *RelativeNameReferenceReference `xml:"Relative_Name_Reference_Reference,omitempty"`
    RelativeTypeReference *RelativeTypeReference `xml:"Relative_Type_Reference,omitempty"`
    NameDetailData *NameDetailData `xml:"Name_Detail_Data,omitempty"`
}

type RelativeNameReferenceReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type RelativeTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SexualOrientationAndGenderIdentityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type GenderReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ReportingGenderReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type VeteransPreferenceReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type VeteransPreferenceForRifReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SelectiveServiceRegistrationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ActiveMilitaryUniformedServiceReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type UniformServiceReserveStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CountrySpecificSectionData struct {
    CountrySpecificSection1Data *CountrySpecificSection1Data `xml:"Country_Specific_Section_1_Data,omitempty"`
    CountrySpecificSection2Data *CountrySpecificSection2Data `xml:"Country_Specific_Section_2_Data,omitempty"`
    CountrySpecificSection3Data *CountrySpecificSection3Data `xml:"Country_Specific_Section_3_Data,omitempty"`
}

type CountrySpecificSection1Data struct {
    Field1Reference *Field1Reference `xml:"Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"Field_3_Reference,omitempty"`
}

type Field1Reference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Field2Reference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Field3Reference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CountrySpecificSection2Data struct {
    Field1Reference *Field1Reference `xml:"Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"Field_3_Reference,omitempty"`
}

type CountrySpecificSection3Data struct {
    Field1Reference *Field1Reference `xml:"Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"Field_3_Reference,omitempty"`
}

type CountryOfBirthReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CountryRegionOfBirthReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CityOfBirthReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CitizenshipStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PrimaryNationalityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AdditionalNationalitiesReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type BloodTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryServiceData struct {
    StatusReference *StatusReference `xml:"Status_Reference,omitempty"`
    DischargeDate *string `xml:"Discharge_Date,omitempty"`
    StatusBeginDate *string `xml:"Status_Begin_Date,omitempty"`
    MilitaryServiceTypeReference *MilitaryServiceTypeReference `xml:"Military_Service_Type_Reference,omitempty"`
    MilitaryRankReference *MilitaryRankReference `xml:"Military_Rank_Reference,omitempty"`
    Notes *string `xml:"Notes,omitempty"`
    MilitaryServiceReference *MilitaryServiceReference `xml:"Military_Service_Reference,omitempty"`
    MilitaryDischargeTypeReference *MilitaryDischargeTypeReference `xml:"Military_Discharge_Type_Reference,omitempty"`
}

type StatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryServiceTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryRankReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryServiceReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryDischargeTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SexualOrientationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type GenderIdentityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PronounReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type NonCountrySpecificSectionData struct {
    NonCountrySpecificSection1Data *NonCountrySpecificSection1Data `xml:"Non_Country_Specific_Section_1_Data,omitempty"`
    NonCountrySpecificSection2Data *NonCountrySpecificSection2Data `xml:"Non_Country_Specific_Section_2_Data,omitempty"`
    NonCountrySpecificSection3Data *NonCountrySpecificSection3Data `xml:"Non_Country_Specific_Section_3_Data,omitempty"`
}

type NonCountrySpecificSection1Data struct {
    Field1Reference *Field1Reference `xml:"Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"Field_3_Reference,omitempty"`
}

type NonCountrySpecificSection2Data struct {
    Field1Reference *Field1Reference `xml:"Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"Field_3_Reference,omitempty"`
}

type NonCountrySpecificSection3Data struct {
    Field1Reference *Field1Reference `xml:"Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"Field_3_Reference,omitempty"`
}

type IdentificationData struct {
    NationalId *NationalId `xml:"National_ID,omitempty"`
    GovernmentId *GovernmentId `xml:"Government_ID,omitempty"`
    VisaId *VisaId `xml:"Visa_ID,omitempty"`
    PassportId *PassportId `xml:"Passport_ID,omitempty"`
    LicenseId *LicenseId `xml:"License_ID,omitempty"`
    CustomId *CustomId `xml:"Custom_ID,omitempty"`
}

type NationalId struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    NationalIdReference *NationalIdReference `xml:"National_ID_Reference,omitempty"`
    NationalIdData *NationalIdData `xml:"National_ID_Data,omitempty"`
    NationalIdSharedReference *NationalIdSharedReference `xml:"National_ID_Shared_Reference,omitempty"`
}

type NationalIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type NationalIdData struct {
    Id *string `xml:"ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
    Series *string `xml:"Series,omitempty"`
    IssuingAgency *string `xml:"Issuing_Agency,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"Verified_By_Reference,omitempty"`
}

type IdTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type VerifiedByReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type NationalIdSharedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type GovernmentId struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    GovernmentIdReference *GovernmentIdReference `xml:"Government_ID_Reference,omitempty"`
    GovernmentIdData *GovernmentIdData `xml:"Government_ID_Data,omitempty"`
    GovernmentIdSharedReference *GovernmentIdSharedReference `xml:"Government_ID_Shared_Reference,omitempty"`
}

type GovernmentIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type GovernmentIdData struct {
    Id *string `xml:"ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"Verified_by_Reference,omitempty"`
}

type GovernmentIdSharedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type VisaId struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    VisaIdReference *VisaIdReference `xml:"Visa_ID_Reference,omitempty"`
    VisaIdData *VisaIdData `xml:"Visa_ID_Data,omitempty"`
    VisaIdSharedReference *VisaIdSharedReference `xml:"Visa_ID_Shared_Reference,omitempty"`
}

type VisaIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type VisaIdData struct {
    Id *string `xml:"ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"Verified_By_Reference,omitempty"`
}

type VisaIdSharedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PassportId struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    PassportIdReference *PassportIdReference `xml:"Passport_ID_Reference,omitempty"`
    PassportIdData *PassportIdData `xml:"Passport_ID_Data,omitempty"`
    PassportIdSharedReference *PassportIdSharedReference `xml:"Passport_ID_Shared_Reference,omitempty"`
}

type PassportIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PassportIdData struct {
    Id *string `xml:"ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"Verified_By_Reference,omitempty"`
}

type PassportIdSharedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LicenseId struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    LicenseIdReference *LicenseIdReference `xml:"License_ID_Reference,omitempty"`
    LicenseIdData *LicenseIdData `xml:"License_ID_Data,omitempty"`
    LicenseIdSharedReference *LicenseIdSharedReference `xml:"License_ID_Shared_Reference,omitempty"`
}

type LicenseIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LicenseIdData struct {
    Id *string `xml:"ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    CountryRegionReference *CountryRegionReference `xml:"Country_Region_Reference,omitempty"`
    CountryRegionDescriptor *string `xml:"Country_Region_Descriptor,omitempty"`
    AuthorityReference *AuthorityReference `xml:"Authority_Reference,omitempty"`
    LicenseClass *string `xml:"License_Class,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"Verified_By_Reference,omitempty"`
}

type CountryRegionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AuthorityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LicenseIdSharedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CustomId struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    CustomIdReference *CustomIdReference `xml:"Custom_ID_Reference,omitempty"`
    CustomIdData *CustomIdData `xml:"Custom_ID_Data,omitempty"`
    CustomIdSharedReference *CustomIdSharedReference `xml:"Custom_ID_Shared_Reference,omitempty"`
}

type CustomIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CustomIdData struct {
    Id *string `xml:"ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"ID_Type_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    OrganizationIdReference *OrganizationIdReference `xml:"Organization_ID_Reference,omitempty"`
    CustomDescription *string `xml:"Custom_Description,omitempty"`
}

type OrganizationIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CustomIdSharedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ContactData struct {
    AddressData *AddressData `xml:"Address_Data,omitempty"`
    PhoneData *PhoneData `xml:"Phone_Data,omitempty"`
    EmailAddressData *EmailAddressData `xml:"Email_Address_Data,omitempty"`
    InstantMessengerData *InstantMessengerData `xml:"Instant_Messenger_Data,omitempty"`
    WebAddressData *WebAddressData `xml:"Web_Address_Data,omitempty"`
}

type AddressData struct {
    FormattedAddress *string `xml:"Formatted_Address,attr,omitempty"`
    AddressFormatType *string `xml:"Address_Format_Type,attr,omitempty"`
    DefaultedBusinessSiteAddress *string `xml:"Defaulted_Business_Site_Address,attr,omitempty"`
    Delete *string `xml:"Delete,attr,omitempty"`
    DoNotReplaceAll *string `xml:"Do_Not_Replace_All,attr,omitempty"`
    EffectiveDate *string `xml:"Effective_Date,attr,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    LastModified *string `xml:"Last_Modified,omitempty"`
    AddressLineData *AddressLineData `xml:"Address_Line_Data,omitempty"`
    Municipality *string `xml:"Municipality,omitempty"`
    CountryCityReference *CountryCityReference `xml:"Country_City_Reference,omitempty"`
    SubmunicipalityData *SubmunicipalityData `xml:"Submunicipality_Data,omitempty"`
    CountryRegionReference *CountryRegionReference `xml:"Country_Region_Reference,omitempty"`
    CountryRegionDescriptor *string `xml:"Country_Region_Descriptor,omitempty"`
    SubregionData *SubregionData `xml:"Subregion_Data,omitempty"`
    PostalCode *string `xml:"Postal_Code,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
    NumberOfDays *int `xml:"Number_of_Days,omitempty"`
    MunicipalityLocal *string `xml:"Municipality_Local,omitempty"`
    AddressReference *AddressReference `xml:"Address_Reference,omitempty"`
    AddressId *string `xml:"Address_ID,omitempty"`
}

type AddressLineData struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type CountryCityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SubmunicipalityData struct {
    AddressComponentName *string `xml:"Address_Component_Name,attr,omitempty"`
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type SubregionData struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type UsageData struct {
    Public *string `xml:"Public,attr,omitempty"`
    TypeData *TypeData `xml:"Type_Data,omitempty"`
    UseForReference *UseForReference `xml:"Use_For_Reference,omitempty"`
    UseForTenantedReference *UseForTenantedReference `xml:"Use_For_Tenanted_Reference,omitempty"`
    Comments *string `xml:"Comments,omitempty"`
}

type TypeData struct {
    Primary *string `xml:"Primary,attr,omitempty"`
    TypeReference *TypeReference `xml:"Type_Reference,omitempty"`
}

type TypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type UseForReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type UseForTenantedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AddressReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PhoneData struct {
    AreaCode *string `xml:"Area_Code,attr,omitempty"`
    TenantFormattedPhone *string `xml:"Tenant_Formatted_Phone,attr,omitempty"`
    InternationalFormattedPhone *string `xml:"International_Formatted_Phone,attr,omitempty"`
    PhoneNumberWithoutAreaCode *string `xml:"Phone_Number_Without_Area_Code,attr,omitempty"`
    NationalFormattedPhone *string `xml:"National_Formatted_Phone,attr,omitempty"`
    E164FormattedPhone *string `xml:"E164_Formatted_Phone,attr,omitempty"`
    WorkdayTraditionalFormattedPhone *string `xml:"Workday_Traditional_Formatted_Phone,attr,omitempty"`
    Delete *string `xml:"Delete,attr,omitempty"`
    DoNotReplaceAll *string `xml:"Do_Not_Replace_All,attr,omitempty"`
    CountryIsoCode *string `xml:"Country_ISO_Code,omitempty"`
    InternationalPhoneCode *string `xml:"International_Phone_Code,omitempty"`
    PhoneNumber *string `xml:"Phone_Number,omitempty"`
    PhoneExtension *string `xml:"Phone_Extension,omitempty"`
    PhoneDeviceTypeReference *PhoneDeviceTypeReference `xml:"Phone_Device_Type_Reference,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
    PhoneReference *PhoneReference `xml:"Phone_Reference,omitempty"`
    Id *string `xml:"ID,omitempty"`
}

type PhoneDeviceTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PhoneReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EmailAddressData struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    DoNotReplaceAll *string `xml:"Do_Not_Replace_All,attr,omitempty"`
    EmailAddress *string `xml:"Email_Address,omitempty"`
    EmailComment *string `xml:"Email_Comment,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
    EmailReference *EmailReference `xml:"Email_Reference,omitempty"`
    Id *string `xml:"ID,omitempty"`
}

type EmailReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type InstantMessengerData struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    DoNotReplaceAll *string `xml:"Do_Not_Replace_All,attr,omitempty"`
    InstantMessengerAddress *string `xml:"Instant_Messenger_Address,omitempty"`
    InstantMessengerTypeReference *InstantMessengerTypeReference `xml:"Instant_Messenger_Type_Reference,omitempty"`
    InstantMessengerComment *string `xml:"Instant_Messenger_Comment,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
    InstantMessengerReference *InstantMessengerReference `xml:"Instant_Messenger_Reference,omitempty"`
    Id *string `xml:"ID,omitempty"`
}

type InstantMessengerTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type InstantMessengerReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WebAddressData struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    DoNotReplaceAll *string `xml:"Do_Not_Replace_All,attr,omitempty"`
    WebAddress *string `xml:"Web_Address,omitempty"`
    WebAddressComment *string `xml:"Web_Address_Comment,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
    WebAddressReference *WebAddressReference `xml:"Web_Address_Reference,omitempty"`
    Id *string `xml:"ID,omitempty"`
}

type WebAddressReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EmploymentData struct {
    WorkerJobData *WorkerJobData `xml:"Worker_Job_Data,omitempty"`
    WorkerStatusData *WorkerStatusData `xml:"Worker_Status_Data,omitempty"`
}

type WorkerJobData struct {
    PrimaryJob *string `xml:"Primary_Job,attr,omitempty"`
    PositionData *PositionData `xml:"Position_Data,omitempty"`
    PositionOrganizationsData *PositionOrganizationsData `xml:"Position_Organizations_Data,omitempty"`
    PositionManagementChainsData *PositionManagementChainsData `xml:"Position_Management_Chains_Data,omitempty"`
    PositionContractDetailData *PositionContractDetailData `xml:"Position_Contract_Detail_Data,omitempty"`
}

type PositionData struct {
    EffectiveDate *string `xml:"Effective_Date,attr,omitempty"`
    PositionReference *PositionReference `xml:"Position_Reference,omitempty"`
    HeadcountReference *HeadcountReference `xml:"Headcount_Reference,omitempty"`
    PositionId *string `xml:"Position_ID,omitempty"`
    PositionTitle *string `xml:"Position_Title,omitempty"`
    BusinessTitle *string `xml:"Business_Title,omitempty"`
    StartDate *string `xml:"Start_Date,omitempty"`
    EndEmploymentDate *string `xml:"End_Employment_Date,omitempty"`
    EndEmploymentReasonReference *EndEmploymentReasonReference `xml:"End_Employment_Reason_Reference,omitempty"`
    WorkerTypeReference *WorkerTypeReference `xml:"Worker_Type_Reference,omitempty"`
    PositionTimeTypeReference *PositionTimeTypeReference `xml:"Position_Time_Type_Reference,omitempty"`
    JobExempt *bool `xml:"Job_Exempt,omitempty"`
    ScheduledWeeklyHours *int `xml:"Scheduled_Weekly_Hours,omitempty"`
    DefaultWeeklyHours *int `xml:"Default_Weekly_Hours,omitempty"`
    WorkingTimeFrequencyReference *WorkingTimeFrequencyReference `xml:"Working_Time_Frequency_Reference,omitempty"`
    WorkingTimeUnitReference *WorkingTimeUnitReference `xml:"Working_Time_Unit_Reference,omitempty"`
    WorkingTimeValue *int `xml:"Working_Time_Value,omitempty"`
    FullTimeEquivalentPercentage *int `xml:"Full_Time_Equivalent_Percentage,omitempty"`
    SpecifyPaidFte *bool `xml:"Specify_Paid_FTE,omitempty"`
    PaidFte *int `xml:"Paid_FTE,omitempty"`
    SpecifyWorkingFte *bool `xml:"Specify_Working_FTE,omitempty"`
    WorkingFte *int `xml:"Working_FTE,omitempty"`
    ExcludeFromHeadcount *bool `xml:"Exclude_from_Headcount,omitempty"`
    PayRateTypeReference *PayRateTypeReference `xml:"Pay_Rate_Type_Reference,omitempty"`
    JobClassificationSummaryData *JobClassificationSummaryData `xml:"Job_Classification_Summary_Data,omitempty"`
    CompanyInsiderReference *CompanyInsiderReference `xml:"Company_Insider_Reference,omitempty"`
    WorkShiftReference *WorkShiftReference `xml:"Work_Shift_Reference,omitempty"`
    WorkHoursProfilesReference *WorkHoursProfilesReference `xml:"Work_Hours_Profiles_Reference,omitempty"`
    FederalWithholdingFein *string `xml:"Federal_Withholding_FEIN,omitempty"`
    WorkerCompensationCodeData *WorkerCompensationCodeData `xml:"Worker_Compensation_Code_Data,omitempty"`
    PositionPayrollReportingCodeData *PositionPayrollReportingCodeData `xml:"Position_Payroll_Reporting_Code_Data,omitempty"`
    JobProfileSummaryData *JobProfileSummaryData `xml:"Job_Profile_Summary_Data,omitempty"`
    BusinessSiteSummaryData *BusinessSiteSummaryData `xml:"Business_Site_Summary_Data,omitempty"`
    PayrollInterfaceProcessingData *PayrollInterfaceProcessingData `xml:"Payroll_Interface_Processing_Data,omitempty"`
    RegularPaidEquivalentHours *int `xml:"Regular_Paid_Equivalent_Hours,omitempty"`
    WorkerHoursProfileClassification *string `xml:"Worker_Hours_Profile_Classification,omitempty"`
    InternationalAssignmentData *InternationalAssignmentData `xml:"International_Assignment_Data,omitempty"`
    WorkSpaceReference *WorkSpaceReference `xml:"Work_Space__Reference,omitempty"`
    AcademicPaySetupData *AcademicPaySetupData `xml:"Academic_Pay_Setup_Data,omitempty"`
    EndDate *string `xml:"End_Date,omitempty"`
    PayThroughDate *string `xml:"Pay_Through_Date,omitempty"`
    CollectiveAgreementSummaryData *CollectiveAgreementSummaryData `xml:"Collective_Agreement_Summary_Data,omitempty"`
    EmployeeProbationPeriodSummaryData *EmployeeProbationPeriodSummaryData `xml:"Employee_Probation_Period_Summary_Data,omitempty"`
    ManagerAsOfLastDetectedManagerChangeReference *ManagerAsOfLastDetectedManagerChangeReference `xml:"Manager_as_of_last_detected_manager_change_Reference,omitempty"`
}

type HeadcountReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EndEmploymentReasonReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkerTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PositionTimeTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkingTimeFrequencyReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkingTimeUnitReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PayRateTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type JobClassificationSummaryData struct {
    Additional *string `xml:"Additional,attr,omitempty"`
    JobClassificationReference *JobClassificationReference `xml:"Job_Classification_Reference,omitempty"`
    JobGroupReference *JobGroupReference `xml:"Job_Group_Reference,omitempty"`
}

type JobClassificationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type JobGroupReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CompanyInsiderReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkShiftReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkHoursProfilesReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkerCompensationCodeData struct {
    WorkersCompensationCodeReference *WorkersCompensationCodeReference `xml:"Workers_Compensation_Code_Reference,omitempty"`
    WorkersCompensationCode *string `xml:"Workers_Compensation_Code,omitempty"`
}

type WorkersCompensationCodeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PositionPayrollReportingCodeData struct {
    PayrollReportingCodeReference *PayrollReportingCodeReference `xml:"Payroll_Reporting_Code_Reference,omitempty"`
    Code *string `xml:"Code,omitempty"`
    FormattedCode *string `xml:"Formatted_Code,omitempty"`
    Name *string `xml:"Name,omitempty"`
    PayrollReportingTypeReference *PayrollReportingTypeReference `xml:"Payroll_Reporting_Type_Reference,omitempty"`
}

type PayrollReportingCodeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PayrollReportingTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type JobProfileSummaryData struct {
    JobProfileReference *JobProfileReference `xml:"Job_Profile_Reference,omitempty"`
    JobExempt *bool `xml:"Job_Exempt,omitempty"`
    ManagementLevelReference *ManagementLevelReference `xml:"Management_Level_Reference,omitempty"`
    JobCategoryReference *JobCategoryReference `xml:"Job_Category_Reference,omitempty"`
    JobFamilyReference *JobFamilyReference `xml:"Job_Family_Reference,omitempty"`
    JobProfileName *string `xml:"Job_Profile_Name,omitempty"`
    WorkShiftRequired *bool `xml:"Work_Shift_Required,omitempty"`
    CriticalJob *bool `xml:"Critical_Job,omitempty"`
    DifficultyToFillReference *DifficultyToFillReference `xml:"Difficulty_to_Fill_Reference,omitempty"`
}

type JobProfileReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ManagementLevelReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type JobCategoryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type JobFamilyReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DifficultyToFillReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type BusinessSiteSummaryData struct {
    LocationReference *LocationReference `xml:"Location_Reference,omitempty"`
    Name *string `xml:"Name,omitempty"`
    LocationTypeReference *LocationTypeReference `xml:"Location_Type_Reference,omitempty"`
    LocalReference *LocalReference `xml:"Local_Reference,omitempty"`
    DisplayLanguageReference *DisplayLanguageReference `xml:"Display_Language_Reference,omitempty"`
    TimeProfileReference *TimeProfileReference `xml:"Time_Profile_Reference,omitempty"`
    ScheduledWeeklyHours *int `xml:"Scheduled_Weekly_Hours,omitempty"`
    AddressData *AddressData `xml:"Address_Data,omitempty"`
}

type LocationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LocationTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LocalReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DisplayLanguageReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type TimeProfileReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PayrollInterfaceProcessingData struct {
    EffectiveDate *string `xml:"Effective_Date,omitempty"`
    PayRateTypeReference *PayRateTypeReference `xml:"Pay_Rate_Type_Reference,omitempty"`
    FrequencyReference *FrequencyReference `xml:"Frequency_Reference,omitempty"`
    PayGroupReference *PayGroupReference `xml:"Pay_Group_Reference,omitempty"`
    PayrollEntityReference *PayrollEntityReference `xml:"Payroll_Entity_Reference,omitempty"`
    ExternalEmployeeTypeReference *ExternalEmployeeTypeReference `xml:"External_Employee_Type_Reference,omitempty"`
    PayrollFileNumber *string `xml:"Payroll_File_Number,omitempty"`
}

type FrequencyReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PayGroupReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PayrollEntityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ExternalEmployeeTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type InternationalAssignmentData struct {
    InternationalAssignmentTypeReference *InternationalAssignmentTypeReference `xml:"International_Assignment_Type_Reference,omitempty"`
    StartInternationalAssignmentReasonReference *StartInternationalAssignmentReasonReference `xml:"Start_International_Assignment_Reason_Reference,omitempty"`
    ExpectedAssignmentEndDate *string `xml:"Expected_Assignment_End_Date,omitempty"`
    HostCountryReference *HostCountryReference `xml:"Host_Country_Reference,omitempty"`
    HomeCountryReference *HomeCountryReference `xml:"Home_Country_Reference,omitempty"`
}

type InternationalAssignmentTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type StartInternationalAssignmentReasonReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HostCountryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HomeCountryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkSpaceReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AcademicPaySetupData struct {
    AnnualWorkPeriodWorkPercentOfYear *int `xml:"Annual_Work_Period_Work_Percent_of_Year,omitempty"`
    AnnualWorkPeriodStartDate *string `xml:"Annual_Work_Period_Start_Date,omitempty"`
    AnnualWorkPeriodEndDate *string `xml:"Annual_Work_Period_End_Date,omitempty"`
    DisbursementPlanPeriodStartDate *string `xml:"Disbursement_Plan_Period_Start_Date,omitempty"`
    DisbursementPlanPeriodEndDate *string `xml:"Disbursement_Plan_Period_End_Date,omitempty"`
}

type CollectiveAgreementSummaryData struct {
    CollectiveAgreementData *CollectiveAgreementData `xml:"Collective_Agreement_Data,omitempty"`
}

type CollectiveAgreementData struct {
    AssignEmployeeCollectiveAgreementEventReference *AssignEmployeeCollectiveAgreementEventReference `xml:"Assign_Employee_Collective_Agreement_Event_Reference,omitempty"`
    EffectiveDate *string `xml:"Effective_Date,omitempty"`
    EndAssignmentDate *string `xml:"End_Assignment_Date,omitempty"`
    CollectiveAgreementData *CollectiveAgreementData `xml:"Collective_Agreement_Data,omitempty"`
    CollectiveAgreementReference *CollectiveAgreementReference `xml:"Collective_Agreement_Reference,omitempty"`
    CollectiveAgreementReviewDate *string `xml:"Collective_Agreement_Review_Date,omitempty"`
    CollectiveAgreementFactor *CollectiveAgreementFactor `xml:"Collective_Agreement_Factor,omitempty"`
}

type AssignEmployeeCollectiveAgreementEventReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CollectiveAgreementReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CollectiveAgreementFactor struct {
    Order *string `xml:"Order,omitempty"`
    CollectiveAgreementFactorReference *CollectiveAgreementFactorReference `xml:"Collective_Agreement_Factor_Reference,omitempty"`
    CollectiveAgreementFactorOptionReference *CollectiveAgreementFactorOptionReference `xml:"Collective_Agreement_Factor_Option_Reference,omitempty"`
}

type CollectiveAgreementFactorReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CollectiveAgreementFactorOptionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EmployeeProbationPeriodSummaryData struct {
    EmployeeProbationPeriodDetailData *EmployeeProbationPeriodDetailData `xml:"Employee_Probation_Period_Detail_Data,omitempty"`
}

type EmployeeProbationPeriodDetailData struct {
    EmployeeProbationPeriodEventReference *EmployeeProbationPeriodEventReference `xml:"Employee_Probation_Period_Event_Reference,omitempty"`
    EmployeeProbationPeriodReference *EmployeeProbationPeriodReference `xml:"Employee_Probation_Period_Reference,omitempty"`
    EffectiveDate *string `xml:"Effective_Date,omitempty"`
    StartDate *string `xml:"Start_Date,omitempty"`
    EndDate *string `xml:"End_Date,omitempty"`
    ProbationTypeReference *ProbationTypeReference `xml:"Probation_Type_Reference,omitempty"`
    ProbationReasonReference *ProbationReasonReference `xml:"Probation_Reason_Reference,omitempty"`
    ExtendedEndDate *string `xml:"Extended_End_Date,omitempty"`
    Note *string `xml:"Note,omitempty"`
}

type EmployeeProbationPeriodEventReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EmployeeProbationPeriodReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ProbationTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ProbationReasonReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ManagerAsOfLastDetectedManagerChangeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PositionOrganizationsData struct {
    PositionOrganizationData *PositionOrganizationData `xml:"Position_Organization_Data,omitempty"`
    PayGroupAssignmentCorrectOrRescindData *PayGroupAssignmentCorrectOrRescindData `xml:"Pay_Group_Assignment_Correct_or_Rescind_Data,omitempty"`
}

type PositionOrganizationData struct {
    OrganizationReference *OrganizationReference `xml:"Organization_Reference,omitempty"`
    OrganizationData *OrganizationData `xml:"Organization_Data,omitempty"`
}

type OrganizationData struct {
    OrganizationReferenceId *string `xml:"Organization_Reference_ID,omitempty"`
    OrganizationCode *string `xml:"Organization_Code,omitempty"`
    IntegrationIdData *IntegrationIdData `xml:"Integration_ID_Data,omitempty"`
    OrganizationName *string `xml:"Organization_Name,omitempty"`
    OrganizationTypeReference *OrganizationTypeReference `xml:"Organization_Type_Reference,omitempty"`
    OrganizationSubtypeReference *OrganizationSubtypeReference `xml:"Organization_Subtype_Reference,omitempty"`
    PrimaryBusinessSiteReference *PrimaryBusinessSiteReference `xml:"Primary_Business_Site_Reference,omitempty"`
    OrganizationSupportRoleData *OrganizationSupportRoleData `xml:"Organization_Support_Role_Data,omitempty"`
    DateOfPayGroupAssignment *string `xml:"Date_of_Pay_Group_Assignment,omitempty"`
    UsedInChangeOrganizationAssignments *bool `xml:"Used_in_Change_Organization_Assignments,omitempty"`
}

type IntegrationIdData struct {
    Id *Id `xml:"ID,omitempty"`
}

type OrganizationTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type OrganizationSubtypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PrimaryBusinessSiteReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type OrganizationSupportRoleData struct {
    OrganizationSupportRole *OrganizationSupportRole `xml:"Organization_Support_Role,omitempty"`
}

type OrganizationSupportRole struct {
    OrganizationRoleReference *OrganizationRoleReference `xml:"Organization_Role_Reference,omitempty"`
    OrganizationRoleData *OrganizationRoleData `xml:"Organization_Role_Data,omitempty"`
}

type OrganizationRoleReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type OrganizationRoleData struct {
    WorkerReference *WorkerReference `xml:"Worker_Reference,omitempty"`
    AssignmentFrom *string `xml:"Assignment_From,omitempty"`
}

type PayGroupAssignmentCorrectOrRescindData struct {
    EffectiveDate *string `xml:"Effective_Date,omitempty"`
    CompletedOn *string `xml:"Completed_On,omitempty"`
    EventCorrected *bool `xml:"Event_Corrected,omitempty"`
    EventRescinded *bool `xml:"Event_Rescinded,omitempty"`
    OriginalPayGroupReference *OriginalPayGroupReference `xml:"Original_Pay_Group_Reference,omitempty"`
    ProposedPayGroupReference *ProposedPayGroupReference `xml:"Proposed_Pay_Group_Reference,omitempty"`
}

type OriginalPayGroupReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ProposedPayGroupReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PositionManagementChainsData struct {
    PositionSupervisoryManagementChainData *PositionSupervisoryManagementChainData `xml:"Position_Supervisory_Management_Chain_Data,omitempty"`
    PositionMatrixManagementChainData *PositionMatrixManagementChainData `xml:"Position_Matrix_Management_Chain_Data,omitempty"`
}

type PositionSupervisoryManagementChainData struct {
    ManagementChainData *ManagementChainData `xml:"Management_Chain_Data,omitempty"`
}

type ManagementChainData struct {
    OrganizationReference *OrganizationReference `xml:"Organization_Reference,omitempty"`
    ManagerReference *ManagerReference `xml:"Manager_Reference,omitempty"`
    Manager *Manager `xml:"Manager,omitempty"`
}

type ManagerReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Manager struct {
    WorkerReference *WorkerReference `xml:"Worker_Reference,omitempty"`
    WorkerDescriptor *string `xml:"Worker_Descriptor,omitempty"`
}

type PositionMatrixManagementChainData struct {
    ManagementChainData *ManagementChainData `xml:"Management_Chain_Data,omitempty"`
}

type PositionContractDetailData struct {
    ContractPayRate *int `xml:"Contract_Pay_Rate,omitempty"`
    CurrencyReference *CurrencyReference `xml:"Currency_Reference,omitempty"`
    FrequencyReference *FrequencyReference `xml:"Frequency_Reference,omitempty"`
    ContractAssignmentDetails *string `xml:"Contract_Assignment_Details,omitempty"`
    ContractEndDate *string `xml:"Contract_End_Date,omitempty"`
    SupplierReference *SupplierReference `xml:"Supplier_Reference,omitempty"`
}

type CurrencyReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SupplierReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkerStatusData struct {
    Active *bool `xml:"Active,omitempty"`
    ActiveStatusDate *string `xml:"Active_Status_Date,omitempty"`
    HireDate *string `xml:"Hire_Date,omitempty"`
    OriginalHireDate *string `xml:"Original_Hire_Date,omitempty"`
    HireReasonReference *HireReasonReference `xml:"Hire_Reason_Reference,omitempty"`
    EndEmploymentDate *string `xml:"End_Employment_Date,omitempty"`
    ContinuousServiceDate *string `xml:"Continuous_Service_Date,omitempty"`
    FirstDayOfWork *string `xml:"First_Day_of_Work,omitempty"`
    ExpectedRetirementDate *string `xml:"Expected_Retirement_Date,omitempty"`
    RetirementEligibilityDate *string `xml:"Retirement_Eligibility_Date,omitempty"`
    Retired *bool `xml:"Retired,omitempty"`
    RetirementDate *string `xml:"Retirement_Date,omitempty"`
    SeniorityDate *string `xml:"Seniority_Date,omitempty"`
    SeveranceDate *string `xml:"Severance_Date,omitempty"`
    BenefitsServiceDate *string `xml:"Benefits_Service_Date,omitempty"`
    CompanyServiceDate *string `xml:"Company_Service_Date,omitempty"`
    TimeOffServiceDate *string `xml:"Time_Off_Service_Date,omitempty"`
    VestingDate *string `xml:"Vesting_Date,omitempty"`
    DateEnteredWorkforce *string `xml:"Date_Entered_Workforce,omitempty"`
    DaysUnemployed *int `xml:"Days_Unemployed,omitempty"`
    MonthsContinuousPriorEmployment *int `xml:"Months_Continuous_Prior_Employment,omitempty"`
    Terminated *bool `xml:"Terminated,omitempty"`
    TerminationDate *string `xml:"Termination_Date,omitempty"`
    PayThroughDate *string `xml:"Pay_Through_Date,omitempty"`
    AgreementSignatureDate *string `xml:"Agreement_Signature_Date,omitempty"`
    DismissalProcessStartDate *string `xml:"Dismissal_Process_Start_Date,omitempty"`
    NoticePeriodStartDate *string `xml:"Notice_Period_Start_Date,omitempty"`
    PrimaryTerminationReasonReference *PrimaryTerminationReasonReference `xml:"Primary_Termination_Reason_Reference,omitempty"`
    PrimaryTerminationCategoryReference *PrimaryTerminationCategoryReference `xml:"Primary_Termination_Category_Reference,omitempty"`
    TerminationInvoluntary *bool `xml:"Termination_Involuntary,omitempty"`
    SecondaryTerminationReasonsData *SecondaryTerminationReasonsData `xml:"Secondary_Termination_Reasons_Data,omitempty"`
    LocalTerminationReasonReference *LocalTerminationReasonReference `xml:"Local_Termination_Reason_Reference,omitempty"`
    EligibleForHireReference *EligibleForHireReference `xml:"Eligible_for_Hire_Reference,omitempty"`
    RegrettableTermination *bool `xml:"Regrettable_Termination,omitempty"`
    EligibleForRehireOnLatestTerminationReference *EligibleForRehireOnLatestTerminationReference `xml:"Eligible_for_Rehire_on_Latest_Termination_Reference,omitempty"`
    HireRescinded *bool `xml:"Hire_Rescinded,omitempty"`
    TerminationLastDayOfWork *string `xml:"Termination_Last_Day_of_Work,omitempty"`
    ResignationDate *string `xml:"Resignation_Date,omitempty"`
    LastDateForWhichPaid *string `xml:"Last_Date_for_Which_Paid,omitempty"`
    ExpectedDateOfReturn *string `xml:"Expected_Date_of_Return,omitempty"`
    NotReturning *bool `xml:"Not_Returning,omitempty"`
    ReturnUnknown *bool `xml:"Return_Unknown,omitempty"`
    ProbationStartDate *string `xml:"Probation_Start_Date,omitempty"`
    ProbationEndDate *string `xml:"Probation_End_Date,omitempty"`
    LeaveStatusData *LeaveStatusData `xml:"Leave_Status_Data,omitempty"`
}

type HireReasonReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PrimaryTerminationReasonReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PrimaryTerminationCategoryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SecondaryTerminationReasonsData struct {
    SecondaryTerminationReasonReference *SecondaryTerminationReasonReference `xml:"Secondary_Termination_Reason_Reference,omitempty"`
    SecondaryTerminationReasonCategoryReference *SecondaryTerminationReasonCategoryReference `xml:"Secondary_Termination_Reason_Category_Reference,omitempty"`
}

type SecondaryTerminationReasonReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SecondaryTerminationReasonCategoryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LocalTerminationReasonReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EligibleForHireReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EligibleForRehireOnLatestTerminationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LeaveStatusData struct {
    LeaveRequestEventReference *LeaveRequestEventReference `xml:"Leave_Request_Event_Reference,omitempty"`
    LeaveRequestDescription *string `xml:"Leave_Request_Description,omitempty"`
    LeaveReturnEventReference *LeaveReturnEventReference `xml:"Leave_Return_Event_Reference,omitempty"`
    OnLeave *bool `xml:"On_Leave,omitempty"`
    LeaveStartDate *string `xml:"Leave_Start_Date,omitempty"`
    EstimatedLeaveEndDate *string `xml:"Estimated_Leave_End_Date,omitempty"`
    LeaveEndDate *string `xml:"Leave_End_Date,omitempty"`
    FirstDayOfWork *string `xml:"First_Day_Of_Work,omitempty"`
    LeaveLastDayOfWork *string `xml:"Leave_Last_Day_of_Work,omitempty"`
    LeaveOfAbsenceTypeReference *LeaveOfAbsenceTypeReference `xml:"Leave_of_Absence_Type_Reference,omitempty"`
    BenefitsEffect *bool `xml:"Benefits_Effect,omitempty"`
    PayrollEffect *bool `xml:"Payroll_Effect,omitempty"`
    PaidTimeOffAccrualEffect *bool `xml:"Paid_Time_Off_Accrual_Effect,omitempty"`
    ContinuousServiceAccrualEffect *bool `xml:"Continuous_Service_Accrual_Effect,omitempty"`
    StockVestingEffect *bool `xml:"Stock_Vesting_Effect,omitempty"`
    LeaveTypeReasonReference *LeaveTypeReasonReference `xml:"Leave_Type_Reason_Reference,omitempty"`
    LeaveRequestAdditionalFields *LeaveRequestAdditionalFields `xml:"Leave_Request_Additional_Fields,omitempty"`
}

type LeaveRequestEventReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LeaveReturnEventReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LeaveOfAbsenceTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LeaveTypeReasonReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LeaveRequestAdditionalFields struct {
    LastDateForWhichPaid *string `xml:"Last_Date_for_Which_Paid,omitempty"`
    ExpectedDueDate *string `xml:"Expected_Due_Date,omitempty"`
    ChildSBirthDate *string `xml:"Child_s_Birth_Date,omitempty"`
    StillbirthBabyDeceased *bool `xml:"Stillbirth_Baby_Deceased,omitempty"`
    DateBabyArrivedHomeFromHospital *string `xml:"Date_Baby_Arrived_Home_From_Hospital,omitempty"`
}

