// Programmatically generated by gen_structs.py
package put_applicant_request

import "encoding/xml"

type PutApplicantRequest struct {
    XMLName xml.Name `xml:"wd:Put_Applicant_Request"`
    XMLNamespace *string `xml:"xmlns:wd,attr,omitempty"`
    AddOnly *string `xml:"wd:Add_Only,attr,omitempty"`
    Version *string `xml:"wd:version,attr,omitempty"`
    ApplicantReference *ApplicantReference `xml:"wd:Applicant_Reference,omitempty"`
    ApplicantData *ApplicantData `xml:"wd:Applicant_Data,omitempty"`
}

type ApplicantReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Id struct {
    Type *string `xml:"wd:type,attr,omitempty"`
    Value *string `xml:",chardata"`
    ParentId *string `xml:"wd:parent_id,attr,omitempty"`
    ParentType *string `xml:"wd:parent_type,attr,omitempty"`
    SystemId *string `xml:"wd:System_ID,attr,omitempty"`
}

type ApplicantData struct {
    ApplicantId *string `xml:"wd:Applicant_ID,omitempty"`
    PersonalData *PersonalData `xml:"wd:Personal_Data,omitempty"`
    QualificationData *QualificationData `xml:"wd:Qualification_Data,omitempty"`
    RecruitingData *RecruitingData `xml:"wd:Recruiting_Data,omitempty"`
    ResumeData *ResumeData `xml:"wd:Resume_Data,omitempty"`
    BackgroundCheckData *BackgroundCheckData `xml:"wd:Background_Check_Data,omitempty"`
    ExternalIntegrationIdData *ExternalIntegrationIdData `xml:"wd:External_Integration_ID_Data,omitempty"`
    DocumentFieldResultData *DocumentFieldResultData `xml:"wd:Document_Field_Result_Data,omitempty"`
}

type PersonalData struct {
    UniversalId *string `xml:"wd:Universal_ID,omitempty"`
    NameData *NameData `xml:"wd:Name_Data,omitempty"`
    PersonalInformationData *PersonalInformationData `xml:"wd:Personal_Information_Data,omitempty"`
    IdentificationData *IdentificationData `xml:"wd:Identification_Data,omitempty"`
    ContactData *ContactData `xml:"wd:Contact_Data,omitempty"`
    TobaccoUse *bool `xml:"wd:Tobacco_Use,omitempty"`
}

type NameData struct {
    LegalNameData *LegalNameData `xml:"wd:Legal_Name_Data,omitempty"`
    PreferredNameData *PreferredNameData `xml:"wd:Preferred_Name_Data,omitempty"`
    AdditionalNameData *AdditionalNameData `xml:"wd:Additional_Name_Data,omitempty"`
}

type LegalNameData struct {
    NameDetailData *NameDetailData `xml:"wd:Name_Detail_Data,omitempty"`
}

type NameDetailData struct {
    FormattedName *string `xml:"wd:Formatted_Name,attr,omitempty"`
    ReportingName *string `xml:"wd:Reporting_Name,attr,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    PrefixData *PrefixData `xml:"wd:Prefix_Data,omitempty"`
    FirstName *string `xml:"wd:First_Name,omitempty"`
    MiddleName *string `xml:"wd:Middle_Name,omitempty"`
    LastName *string `xml:"wd:Last_Name,omitempty"`
    SecondaryLastName *string `xml:"wd:Secondary_Last_Name,omitempty"`
    TertiaryLastName *string `xml:"wd:Tertiary_Last_Name,omitempty"`
    LocalNameDetailData *LocalNameDetailData `xml:"wd:Local_Name_Detail_Data,omitempty"`
    SuffixData *SuffixData `xml:"wd:Suffix_Data,omitempty"`
    FullNameForSingaporeAndMalaysia *string `xml:"wd:Full_Name_for_Singapore_and_Malaysia,omitempty"`
}

type CountryReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PrefixData struct {
    TitleReference *TitleReference `xml:"wd:Title_Reference,omitempty"`
    TitleDescriptor *string `xml:"wd:Title_Descriptor,omitempty"`
    SalutationReference *SalutationReference `xml:"wd:Salutation_Reference,omitempty"`
}

type TitleReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type SalutationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type LocalNameDetailData struct {
    LocalName *string `xml:"wd:Local_Name,attr,omitempty"`
    LocalScript *string `xml:"wd:Local_Script,attr,omitempty"`
    FirstName *string `xml:"wd:First_Name,omitempty"`
    MiddleName *string `xml:"wd:Middle_Name,omitempty"`
    LastName *string `xml:"wd:Last_Name,omitempty"`
    SecondaryLastName *string `xml:"wd:Secondary_Last_Name,omitempty"`
    FirstName2 *string `xml:"wd:First_Name_2,omitempty"`
    MiddleName2 *string `xml:"wd:Middle_Name_2,omitempty"`
    LastName2 *string `xml:"wd:Last_Name_2,omitempty"`
    SecondaryLastName2 *string `xml:"wd:Secondary_Last_Name_2,omitempty"`
}

type SuffixData struct {
    SocialSuffixReference *SocialSuffixReference `xml:"wd:Social_Suffix_Reference,omitempty"`
    SocialSuffixDescriptor *string `xml:"wd:Social_Suffix_Descriptor,omitempty"`
    AcademicSuffixReference *AcademicSuffixReference `xml:"wd:Academic_Suffix_Reference,omitempty"`
    HereditarySuffixReference *HereditarySuffixReference `xml:"wd:Hereditary_Suffix_Reference,omitempty"`
    HonorarySuffixReference *HonorarySuffixReference `xml:"wd:Honorary_Suffix_Reference,omitempty"`
    ProfessionalSuffixReference *ProfessionalSuffixReference `xml:"wd:Professional_Suffix_Reference,omitempty"`
    ReligiousSuffixReference *ReligiousSuffixReference `xml:"wd:Religious_Suffix_Reference,omitempty"`
    RoyalSuffixReference *RoyalSuffixReference `xml:"wd:Royal_Suffix_Reference,omitempty"`
}

type SocialSuffixReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type AcademicSuffixReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type HereditarySuffixReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type HonorarySuffixReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ProfessionalSuffixReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ReligiousSuffixReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type RoyalSuffixReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PreferredNameData struct {
    NameDetailData *NameDetailData `xml:"wd:Name_Detail_Data,omitempty"`
}

type AdditionalNameData struct {
    NameDetailData *NameDetailData `xml:"wd:Name_Detail_Data,omitempty"`
    NameTypeReference *NameTypeReference `xml:"wd:Name_Type_Reference,omitempty"`
}

type NameTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PersonalInformationData struct {
    PersonalInformationForCountryData *PersonalInformationForCountryData `xml:"wd:Personal_Information_For_Country_Data,omitempty"`
    BirthDate *string `xml:"wd:Birth_Date,omitempty"`
    DateOfDeath *string `xml:"wd:Date_of_Death,omitempty"`
    CountryOfBirthReference *CountryOfBirthReference `xml:"wd:Country_of_Birth_Reference,omitempty"`
    CountryRegionOfBirthReference *CountryRegionOfBirthReference `xml:"wd:Country_Region_of_Birth_Reference,omitempty"`
    RegionOfBirthDescriptor *string `xml:"wd:Region_of_Birth_Descriptor,omitempty"`
    CityOfBirth *string `xml:"wd:City_of_Birth,omitempty"`
    CityOfBirthReference *CityOfBirthReference `xml:"wd:City_of_Birth_Reference,omitempty"`
    CitizenshipStatusReference *CitizenshipStatusReference `xml:"wd:Citizenship_Status_Reference,omitempty"`
    PrimaryNationalityReference *PrimaryNationalityReference `xml:"wd:Primary_Nationality_Reference,omitempty"`
    AdditionalNationalitiesReference *AdditionalNationalitiesReference `xml:"wd:Additional_Nationalities_Reference,omitempty"`
    LastMedicalExamValidTo *string `xml:"wd:Last_Medical_Exam_Valid_To,omitempty"`
    LastMedicalExamDate *string `xml:"wd:Last_Medical_Exam_Date,omitempty"`
    MedicalExamNotes *string `xml:"wd:Medical_Exam_Notes,omitempty"`
    BloodTypeReference *BloodTypeReference `xml:"wd:Blood_Type_Reference,omitempty"`
    MilitaryServiceData *MilitaryServiceData `xml:"wd:Military_Service_Data,omitempty"`
    SexualOrientationReference *SexualOrientationReference `xml:"wd:Sexual_Orientation_Reference,omitempty"`
    GenderIdentityReference *GenderIdentityReference `xml:"wd:Gender_Identity_Reference,omitempty"`
    PronounReference *PronounReference `xml:"wd:Pronoun_Reference,omitempty"`
    NonCountrySpecificSectionData *NonCountrySpecificSectionData `xml:"wd:Non_Country_Specific_Section_Data,omitempty"`
}

type PersonalInformationForCountryData struct {
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    CountryPersonalInformationData *CountryPersonalInformationData `xml:"wd:Country_Personal_Information_Data,omitempty"`
}

type CountryPersonalInformationData struct {
    MaritalStatusReference *MaritalStatusReference `xml:"wd:Marital_Status_Reference,omitempty"`
    MaritalStatusDate *string `xml:"wd:Marital_Status_Date,omitempty"`
    ReligionReference *ReligionReference `xml:"wd:Religion_Reference,omitempty"`
    DisabilityStatusData *DisabilityStatusData `xml:"wd:Disability_Status_Data,omitempty"`
    EthnicityReference *EthnicityReference `xml:"wd:Ethnicity_Reference,omitempty"`
    RaceEthnicityDetailsReference *RaceEthnicityDetailsReference `xml:"wd:Race_Ethnicity_Details_Reference,omitempty"`
    EthnicityVisualSurveyReference *EthnicityVisualSurveyReference `xml:"wd:Ethnicity_Visual_Survey_Reference,omitempty"`
    HispanicOrLatino *bool `xml:"wd:Hispanic_or_Latino,omitempty"`
    HispanicOrLatinoVisualSurvey *bool `xml:"wd:Hispanic_or_Latino_Visual_Survey,omitempty"`
    AboriginalIndigenousIdentificationReference *AboriginalIndigenousIdentificationReference `xml:"wd:Aboriginal_Indigenous_Identification_Reference,omitempty"`
    AboriginalIndigenousIdentificationDetailsReference *AboriginalIndigenousIdentificationDetailsReference `xml:"wd:Aboriginal_Indigenous_Identification_Details_Reference,omitempty"`
    HukouRegionReference *HukouRegionReference `xml:"wd:Hukou_Region_Reference,omitempty"`
    HukouSubregionReference *HukouSubregionReference `xml:"wd:Hukou_Subregion_Reference,omitempty"`
    HukouLocality *string `xml:"wd:Hukou_Locality,omitempty"`
    HukouPostalCode *string `xml:"wd:Hukou_Postal_Code,omitempty"`
    HukouTypeReference *HukouTypeReference `xml:"wd:Hukou_Type_Reference,omitempty"`
    LocalHukou *bool `xml:"wd:Local_Hukou,omitempty"`
    NativeRegionReference *NativeRegionReference `xml:"wd:Native_Region_Reference,omitempty"`
    NativeRegionDescriptor *string `xml:"wd:Native_Region_Descriptor,omitempty"`
    PersonnelFileAgencyForPerson *string `xml:"wd:Personnel_File_Agency_for_Person,omitempty"`
    PoliticalAffiliationReference *PoliticalAffiliationReference `xml:"wd:Political_Affiliation_Reference,omitempty"`
    SocialBenefitsLocalityReference *SocialBenefitsLocalityReference `xml:"wd:Social_Benefits_Locality_Reference,omitempty"`
    RelativeNameInformationData *RelativeNameInformationData `xml:"wd:Relative_Name_Information_Data,omitempty"`
    SexualOrientationAndGenderIdentityReference *SexualOrientationAndGenderIdentityReference `xml:"wd:Sexual_Orientation_and_Gender_Identity_Reference,omitempty"`
    GenderReference *GenderReference `xml:"wd:Gender_Reference,omitempty"`
    ReportingGenderReference *ReportingGenderReference `xml:"wd:Reporting_Gender_Reference,omitempty"`
    VeteransPreferenceReference *VeteransPreferenceReference `xml:"wd:Veterans_Preference_Reference,omitempty"`
    VeteransPreferenceForRifReference *VeteransPreferenceForRifReference `xml:"wd:Veterans_Preference_For_RIF_Reference,omitempty"`
    SelectiveServiceRegistrationReference *SelectiveServiceRegistrationReference `xml:"wd:Selective_Service_Registration_Reference,omitempty"`
    DisabledVeteranLeaveDateReference *string `xml:"wd:Disabled_Veteran_Leave_Date_Reference,omitempty"`
    ActiveMilitaryUniformedServiceReference *ActiveMilitaryUniformedServiceReference `xml:"wd:Active_Military_Uniformed_Service_Reference,omitempty"`
    UniformServiceReserveStatusReference *UniformServiceReserveStatusReference `xml:"wd:Uniform_Service_Reserve_Status_Reference,omitempty"`
    CountrySpecificSectionData *CountrySpecificSectionData `xml:"wd:Country_Specific_Section_Data,omitempty"`
}

type MaritalStatusReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ReligionReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type DisabilityStatusData struct {
    DisabilityReference *DisabilityReference `xml:"wd:Disability_Reference,omitempty"`
    DisabilityStatusDate *string `xml:"wd:Disability_Status_Date,omitempty"`
    DisabilityDateKnown *string `xml:"wd:Disability_Date_Known,omitempty"`
    DisabilityEndDate *string `xml:"wd:Disability_End_Date,omitempty"`
    DisabilityGradeReference *DisabilityGradeReference `xml:"wd:Disability_Grade_Reference,omitempty"`
    DisabilityDegree *int `xml:"wd:Disability_Degree,omitempty"`
    DisabilityRemainingCapacity *int `xml:"wd:Disability_Remaining_Capacity,omitempty"`
    DisabilityCertificationAuthorityReference *DisabilityCertificationAuthorityReference `xml:"wd:Disability_Certification_Authority_Reference,omitempty"`
    DisabilityCertificationAuthority *string `xml:"wd:Disability_Certification_Authority,omitempty"`
    DisabilityCertifiedAt *string `xml:"wd:Disability_Certified_At,omitempty"`
    DisabilityCertificationId *string `xml:"wd:Disability_Certification_ID,omitempty"`
    DisabilityCertificationBasisReference *DisabilityCertificationBasisReference `xml:"wd:Disability_Certification_Basis_Reference,omitempty"`
    DisabilitySeverityRecognitionDate *string `xml:"wd:Disability_Severity_Recognition_Date,omitempty"`
    DisabilityFteTowardQuota *int `xml:"wd:Disability_FTE_Toward_Quota,omitempty"`
    DisabilityWorkRestrictions *string `xml:"wd:Disability_Work_Restrictions,omitempty"`
    DisabilityAccommodationsRequested *string `xml:"wd:Disability_Accommodations_Requested,omitempty"`
    DisabilityAccommodationsProvided *string `xml:"wd:Disability_Accommodations_Provided,omitempty"`
    DisabilityRehabilitationRequested *string `xml:"wd:Disability_Rehabilitation_Requested,omitempty"`
    DisabilityRehabilitationProvided *string `xml:"wd:Disability_Rehabilitation_Provided,omitempty"`
    Note *string `xml:"wd:Note,omitempty"`
    WorkerDocumentReference *WorkerDocumentReference `xml:"wd:Worker_Document_Reference,omitempty"`
    DisabilityStatusReference *DisabilityStatusReference `xml:"wd:Disability_Status_Reference,omitempty"`
}

type DisabilityReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type DisabilityGradeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type DisabilityCertificationAuthorityReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type DisabilityCertificationBasisReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type WorkerDocumentReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type DisabilityStatusReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type EthnicityReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type RaceEthnicityDetailsReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type EthnicityVisualSurveyReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type AboriginalIndigenousIdentificationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type AboriginalIndigenousIdentificationDetailsReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type HukouRegionReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type HukouSubregionReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type HukouTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type NativeRegionReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PoliticalAffiliationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type SocialBenefitsLocalityReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type RelativeNameInformationData struct {
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    RelativeNameReferenceReference *RelativeNameReferenceReference `xml:"wd:Relative_Name_Reference_Reference,omitempty"`
    RelativeTypeReference *RelativeTypeReference `xml:"wd:Relative_Type_Reference,omitempty"`
    NameDetailData *NameDetailData `xml:"wd:Name_Detail_Data,omitempty"`
}

type RelativeNameReferenceReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type RelativeTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type SexualOrientationAndGenderIdentityReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type GenderReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ReportingGenderReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type VeteransPreferenceReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type VeteransPreferenceForRifReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type SelectiveServiceRegistrationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ActiveMilitaryUniformedServiceReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type UniformServiceReserveStatusReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CountrySpecificSectionData struct {
    CountrySpecificSection1Data *CountrySpecificSection1Data `xml:"wd:Country_Specific_Section_1_Data,omitempty"`
    CountrySpecificSection2Data *CountrySpecificSection2Data `xml:"wd:Country_Specific_Section_2_Data,omitempty"`
    CountrySpecificSection3Data *CountrySpecificSection3Data `xml:"wd:Country_Specific_Section_3_Data,omitempty"`
}

type CountrySpecificSection1Data struct {
    Field1Reference *Field1Reference `xml:"wd:Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"wd:Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"wd:Field_3_Reference,omitempty"`
}

type Field1Reference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Field2Reference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Field3Reference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CountrySpecificSection2Data struct {
    Field1Reference *Field1Reference `xml:"wd:Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"wd:Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"wd:Field_3_Reference,omitempty"`
}

type CountrySpecificSection3Data struct {
    Field1Reference *Field1Reference `xml:"wd:Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"wd:Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"wd:Field_3_Reference,omitempty"`
}

type CountryOfBirthReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CountryRegionOfBirthReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CityOfBirthReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CitizenshipStatusReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PrimaryNationalityReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type AdditionalNationalitiesReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type BloodTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type MilitaryServiceData struct {
    StatusReference *StatusReference `xml:"wd:Status_Reference,omitempty"`
    DischargeDate *string `xml:"wd:Discharge_Date,omitempty"`
    StatusBeginDate *string `xml:"wd:Status_Begin_Date,omitempty"`
    MilitaryServiceTypeReference *MilitaryServiceTypeReference `xml:"wd:Military_Service_Type_Reference,omitempty"`
    MilitaryRankReference *MilitaryRankReference `xml:"wd:Military_Rank_Reference,omitempty"`
    Notes *string `xml:"wd:Notes,omitempty"`
    MilitaryServiceReference *MilitaryServiceReference `xml:"wd:Military_Service_Reference,omitempty"`
    MilitaryDischargeTypeReference *MilitaryDischargeTypeReference `xml:"wd:Military_Discharge_Type_Reference,omitempty"`
}

type StatusReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type MilitaryServiceTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type MilitaryRankReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type MilitaryServiceReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type MilitaryDischargeTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type SexualOrientationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type GenderIdentityReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PronounReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type NonCountrySpecificSectionData struct {
    NonCountrySpecificSection1Data *NonCountrySpecificSection1Data `xml:"wd:Non_Country_Specific_Section_1_Data,omitempty"`
    NonCountrySpecificSection2Data *NonCountrySpecificSection2Data `xml:"wd:Non_Country_Specific_Section_2_Data,omitempty"`
    NonCountrySpecificSection3Data *NonCountrySpecificSection3Data `xml:"wd:Non_Country_Specific_Section_3_Data,omitempty"`
}

type NonCountrySpecificSection1Data struct {
    Field1Reference *Field1Reference `xml:"wd:Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"wd:Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"wd:Field_3_Reference,omitempty"`
}

type NonCountrySpecificSection2Data struct {
    Field1Reference *Field1Reference `xml:"wd:Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"wd:Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"wd:Field_3_Reference,omitempty"`
}

type NonCountrySpecificSection3Data struct {
    Field1Reference *Field1Reference `xml:"wd:Field_1_Reference,omitempty"`
    Field2Reference *Field2Reference `xml:"wd:Field_2_Reference,omitempty"`
    Field3Reference *Field3Reference `xml:"wd:Field_3_Reference,omitempty"`
}

type IdentificationData struct {
    NationalId *NationalId `xml:"wd:National_ID,omitempty"`
    GovernmentId *GovernmentId `xml:"wd:Government_ID,omitempty"`
    VisaId *VisaId `xml:"wd:Visa_ID,omitempty"`
    PassportId *PassportId `xml:"wd:Passport_ID,omitempty"`
    LicenseId *LicenseId `xml:"wd:License_ID,omitempty"`
    CustomId *CustomId `xml:"wd:Custom_ID,omitempty"`
}

type NationalId struct {
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    NationalIdReference *NationalIdReference `xml:"wd:National_ID_Reference,omitempty"`
    NationalIdData *NationalIdData `xml:"wd:National_ID_Data,omitempty"`
    NationalIdSharedReference *NationalIdSharedReference `xml:"wd:National_ID_Shared_Reference,omitempty"`
}

type NationalIdReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type NationalIdData struct {
    Id *string `xml:"wd:ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"wd:ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    IssuedDate *string `xml:"wd:Issued_Date,omitempty"`
    ExpirationDate *string `xml:"wd:Expiration_Date,omitempty"`
    VerificationDate *string `xml:"wd:Verification_Date,omitempty"`
    Series *string `xml:"wd:Series,omitempty"`
    IssuingAgency *string `xml:"wd:Issuing_Agency,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"wd:Verified_By_Reference,omitempty"`
}

type IdTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type VerifiedByReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type NationalIdSharedReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type GovernmentId struct {
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    GovernmentIdReference *GovernmentIdReference `xml:"wd:Government_ID_Reference,omitempty"`
    GovernmentIdData *GovernmentIdData `xml:"wd:Government_ID_Data,omitempty"`
    GovernmentIdSharedReference *GovernmentIdSharedReference `xml:"wd:Government_ID_Shared_Reference,omitempty"`
}

type GovernmentIdReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type GovernmentIdData struct {
    Id *string `xml:"wd:ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"wd:ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    IssuedDate *string `xml:"wd:Issued_Date,omitempty"`
    ExpirationDate *string `xml:"wd:Expiration_Date,omitempty"`
    VerificationDate *string `xml:"wd:Verification_Date,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"wd:Verified_by_Reference,omitempty"`
}

type GovernmentIdSharedReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type VisaId struct {
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    VisaIdReference *VisaIdReference `xml:"wd:Visa_ID_Reference,omitempty"`
    VisaIdData *VisaIdData `xml:"wd:Visa_ID_Data,omitempty"`
    VisaIdSharedReference *VisaIdSharedReference `xml:"wd:Visa_ID_Shared_Reference,omitempty"`
}

type VisaIdReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type VisaIdData struct {
    Id *string `xml:"wd:ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"wd:ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    IssuedDate *string `xml:"wd:Issued_Date,omitempty"`
    ExpirationDate *string `xml:"wd:Expiration_Date,omitempty"`
    VerificationDate *string `xml:"wd:Verification_Date,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"wd:Verified_By_Reference,omitempty"`
}

type VisaIdSharedReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PassportId struct {
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    PassportIdReference *PassportIdReference `xml:"wd:Passport_ID_Reference,omitempty"`
    PassportIdData *PassportIdData `xml:"wd:Passport_ID_Data,omitempty"`
    PassportIdSharedReference *PassportIdSharedReference `xml:"wd:Passport_ID_Shared_Reference,omitempty"`
}

type PassportIdReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PassportIdData struct {
    Id *string `xml:"wd:ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"wd:ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    IssuedDate *string `xml:"wd:Issued_Date,omitempty"`
    ExpirationDate *string `xml:"wd:Expiration_Date,omitempty"`
    VerificationDate *string `xml:"wd:Verification_Date,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"wd:Verified_By_Reference,omitempty"`
}

type PassportIdSharedReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type LicenseId struct {
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    LicenseIdReference *LicenseIdReference `xml:"wd:License_ID_Reference,omitempty"`
    LicenseIdData *LicenseIdData `xml:"wd:License_ID_Data,omitempty"`
    LicenseIdSharedReference *LicenseIdSharedReference `xml:"wd:License_ID_Shared_Reference,omitempty"`
}

type LicenseIdReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type LicenseIdData struct {
    Id *string `xml:"wd:ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"wd:ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    CountryRegionReference *CountryRegionReference `xml:"wd:Country_Region_Reference,omitempty"`
    CountryRegionDescriptor *string `xml:"wd:Country_Region_Descriptor,omitempty"`
    AuthorityReference *AuthorityReference `xml:"wd:Authority_Reference,omitempty"`
    LicenseClass *string `xml:"wd:License_Class,omitempty"`
    IssuedDate *string `xml:"wd:Issued_Date,omitempty"`
    ExpirationDate *string `xml:"wd:Expiration_Date,omitempty"`
    VerificationDate *string `xml:"wd:Verification_Date,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"wd:Verified_By_Reference,omitempty"`
}

type CountryRegionReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type AuthorityReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type LicenseIdSharedReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CustomId struct {
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    CustomIdReference *CustomIdReference `xml:"wd:Custom_ID_Reference,omitempty"`
    CustomIdData *CustomIdData `xml:"wd:Custom_ID_Data,omitempty"`
    CustomIdSharedReference *CustomIdSharedReference `xml:"wd:Custom_ID_Shared_Reference,omitempty"`
}

type CustomIdReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CustomIdData struct {
    Id *string `xml:"wd:ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"wd:ID_Type_Reference,omitempty"`
    IssuedDate *string `xml:"wd:Issued_Date,omitempty"`
    ExpirationDate *string `xml:"wd:Expiration_Date,omitempty"`
    OrganizationIdReference *OrganizationIdReference `xml:"wd:Organization_ID_Reference,omitempty"`
    CustomDescription *string `xml:"wd:Custom_Description,omitempty"`
}

type OrganizationIdReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CustomIdSharedReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ContactData struct {
    AddressData *AddressData `xml:"wd:Address_Data,omitempty"`
    PhoneData *PhoneData `xml:"wd:Phone_Data,omitempty"`
    EmailAddressData *EmailAddressData `xml:"wd:Email_Address_Data,omitempty"`
    InstantMessengerData *InstantMessengerData `xml:"wd:Instant_Messenger_Data,omitempty"`
    WebAddressData *WebAddressData `xml:"wd:Web_Address_Data,omitempty"`
}

type AddressData struct {
    FormattedAddress *string `xml:"wd:Formatted_Address,attr,omitempty"`
    AddressFormatType *string `xml:"wd:Address_Format_Type,attr,omitempty"`
    DefaultedBusinessSiteAddress *string `xml:"wd:Defaulted_Business_Site_Address,attr,omitempty"`
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    DoNotReplaceAll *string `xml:"wd:Do_Not_Replace_All,attr,omitempty"`
    EffectiveDate *string `xml:"wd:Effective_Date,attr,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    LastModified *string `xml:"wd:Last_Modified,omitempty"`
    AddressLineData *AddressLineData `xml:"wd:Address_Line_Data,omitempty"`
    Municipality *string `xml:"wd:Municipality,omitempty"`
    CountryCityReference *CountryCityReference `xml:"wd:Country_City_Reference,omitempty"`
    SubmunicipalityData *SubmunicipalityData `xml:"wd:Submunicipality_Data,omitempty"`
    CountryRegionReference *CountryRegionReference `xml:"wd:Country_Region_Reference,omitempty"`
    CountryRegionDescriptor *string `xml:"wd:Country_Region_Descriptor,omitempty"`
    SubregionData *SubregionData `xml:"wd:Subregion_Data,omitempty"`
    PostalCode *string `xml:"wd:Postal_Code,omitempty"`
    UsageData *UsageData `xml:"wd:Usage_Data,omitempty"`
    NumberOfDays *int `xml:"wd:Number_of_Days,omitempty"`
    MunicipalityLocal *string `xml:"wd:Municipality_Local,omitempty"`
    AddressReference *AddressReference `xml:"wd:Address_Reference,omitempty"`
    AddressId *string `xml:"wd:Address_ID,omitempty"`
}

type AddressLineData struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Type *string `xml:"wd:Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type CountryCityReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type SubmunicipalityData struct {
    AddressComponentName *string `xml:"wd:Address_Component_Name,attr,omitempty"`
    Type *string `xml:"wd:Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type SubregionData struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Type *string `xml:"wd:Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type UsageData struct {
    Public *string `xml:"wd:Public,attr,omitempty"`
    TypeData *TypeData `xml:"wd:Type_Data,omitempty"`
    UseForReference *UseForReference `xml:"wd:Use_For_Reference,omitempty"`
    UseForTenantedReference *UseForTenantedReference `xml:"wd:Use_For_Tenanted_Reference,omitempty"`
    Comments *string `xml:"wd:Comments,omitempty"`
}

type TypeData struct {
    Primary *string `xml:"wd:Primary,attr,omitempty"`
    TypeReference *TypeReference `xml:"wd:Type_Reference,omitempty"`
}

type TypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type UseForReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type UseForTenantedReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type AddressReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PhoneData struct {
    AreaCode *string `xml:"wd:Area_Code,attr,omitempty"`
    TenantFormattedPhone *string `xml:"wd:Tenant_Formatted_Phone,attr,omitempty"`
    InternationalFormattedPhone *string `xml:"wd:International_Formatted_Phone,attr,omitempty"`
    PhoneNumberWithoutAreaCode *string `xml:"wd:Phone_Number_Without_Area_Code,attr,omitempty"`
    NationalFormattedPhone *string `xml:"wd:National_Formatted_Phone,attr,omitempty"`
    E164FormattedPhone *string `xml:"wd:E164_Formatted_Phone,attr,omitempty"`
    WorkdayTraditionalFormattedPhone *string `xml:"wd:Workday_Traditional_Formatted_Phone,attr,omitempty"`
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    DoNotReplaceAll *string `xml:"wd:Do_Not_Replace_All,attr,omitempty"`
    CountryIsoCode *string `xml:"wd:Country_ISO_Code,omitempty"`
    InternationalPhoneCode *string `xml:"wd:International_Phone_Code,omitempty"`
    PhoneNumber *string `xml:"wd:Phone_Number,omitempty"`
    PhoneExtension *string `xml:"wd:Phone_Extension,omitempty"`
    PhoneDeviceTypeReference *PhoneDeviceTypeReference `xml:"wd:Phone_Device_Type_Reference,omitempty"`
    UsageData *UsageData `xml:"wd:Usage_Data,omitempty"`
    PhoneReference *PhoneReference `xml:"wd:Phone_Reference,omitempty"`
    Id *string `xml:"wd:ID,omitempty"`
}

type PhoneDeviceTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PhoneReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type EmailAddressData struct {
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    DoNotReplaceAll *string `xml:"wd:Do_Not_Replace_All,attr,omitempty"`
    EmailAddress *string `xml:"wd:Email_Address,omitempty"`
    EmailComment *string `xml:"wd:Email_Comment,omitempty"`
    UsageData *UsageData `xml:"wd:Usage_Data,omitempty"`
    EmailReference *EmailReference `xml:"wd:Email_Reference,omitempty"`
    Id *string `xml:"wd:ID,omitempty"`
}

type EmailReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type InstantMessengerData struct {
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    DoNotReplaceAll *string `xml:"wd:Do_Not_Replace_All,attr,omitempty"`
    InstantMessengerAddress *string `xml:"wd:Instant_Messenger_Address,omitempty"`
    InstantMessengerTypeReference *InstantMessengerTypeReference `xml:"wd:Instant_Messenger_Type_Reference,omitempty"`
    InstantMessengerComment *string `xml:"wd:Instant_Messenger_Comment,omitempty"`
    UsageData *UsageData `xml:"wd:Usage_Data,omitempty"`
    InstantMessengerReference *InstantMessengerReference `xml:"wd:Instant_Messenger_Reference,omitempty"`
    Id *string `xml:"wd:ID,omitempty"`
}

type InstantMessengerTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type InstantMessengerReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type WebAddressData struct {
    Delete *string `xml:"wd:Delete,attr,omitempty"`
    DoNotReplaceAll *string `xml:"wd:Do_Not_Replace_All,attr,omitempty"`
    WebAddress *string `xml:"wd:Web_Address,omitempty"`
    WebAddressComment *string `xml:"wd:Web_Address_Comment,omitempty"`
    UsageData *UsageData `xml:"wd:Usage_Data,omitempty"`
    WebAddressReference *WebAddressReference `xml:"wd:Web_Address_Reference,omitempty"`
    Id *string `xml:"wd:ID,omitempty"`
}

type WebAddressReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type QualificationData struct {
    ExternalJobHistory *ExternalJobHistory `xml:"wd:External_Job_History,omitempty"`
    Competency *Competency `xml:"wd:Competency,omitempty"`
    Certification *Certification `xml:"wd:Certification,omitempty"`
    Training *Training `xml:"wd:Training,omitempty"`
    AwardAndActivity *AwardAndActivity `xml:"wd:Award_and_Activity,omitempty"`
    OrganizationMembership *OrganizationMembership `xml:"wd:Organization_Membership,omitempty"`
    Education *Education `xml:"wd:Education,omitempty"`
    WorkExperience *WorkExperience `xml:"wd:Work_Experience,omitempty"`
    Language *Language `xml:"wd:Language,omitempty"`
    InternalProjectExperience *InternalProjectExperience `xml:"wd:Internal_Project_Experience,omitempty"`
}

type ExternalJobHistory struct {
    JobHistoryReference *JobHistoryReference `xml:"wd:Job_History_Reference,omitempty"`
    JobHistoryData *JobHistoryData `xml:"wd:Job_History_Data,omitempty"`
}

type JobHistoryReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type JobHistoryData struct {
    JobHistoryId *string `xml:"wd:Job_History_ID,omitempty"`
    RemoveJobHistory *bool `xml:"wd:Remove_Job_History,omitempty"`
    JobTitle *string `xml:"wd:Job_Title,omitempty"`
    Company *string `xml:"wd:Company,omitempty"`
    JobHistoryCompanyReference *JobHistoryCompanyReference `xml:"wd:Job_History_Company_Reference,omitempty"`
    StartDate *string `xml:"wd:Start_Date,omitempty"`
    EndDate *string `xml:"wd:End_Date,omitempty"`
    ResponsibilitiesAndAchievements *string `xml:"wd:Responsibilities_and_Achievements,omitempty"`
    Location *string `xml:"wd:Location,omitempty"`
    JobReference *string `xml:"wd:Job_Reference,omitempty"`
    Contact *string `xml:"wd:Contact,omitempty"`
}

type JobHistoryCompanyReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Competency struct {
    CompetencyLevelBehaviorReference *CompetencyLevelBehaviorReference `xml:"wd:Competency_Level_Behavior_Reference,omitempty"`
    CompetencyLevelBehaviorDescriptor *string `xml:"wd:Competency_Level_Behavior_Descriptor,omitempty"`
    AssessmentComment *string `xml:"wd:Assessment_Comment,omitempty"`
    AssessedOn *string `xml:"wd:Assessed_On,omitempty"`
    AssessedByPersonReference *AssessedByPersonReference `xml:"wd:Assessed_By_Person_Reference,omitempty"`
    AssessedByWorkerDescriptor *string `xml:"wd:Assessed_By_Worker_Descriptor,omitempty"`
    CompetencyReference *CompetencyReference `xml:"wd:Competency_Reference,omitempty"`
    CompetencyDescriptor *string `xml:"wd:Competency_Descriptor,omitempty"`
}

type CompetencyLevelBehaviorReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type AssessedByPersonReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CompetencyReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Certification struct {
    CertificationReference *CertificationReference `xml:"wd:Certification_Reference,omitempty"`
    CertificationData *CertificationData `xml:"wd:Certification_Data,omitempty"`
}

type CertificationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CertificationData struct {
    CertificationId *string `xml:"wd:Certification_ID,omitempty"`
    RemoveCertification *bool `xml:"wd:Remove_Certification,omitempty"`
    CertificationReference *CertificationReference `xml:"wd:Certification_Reference,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    CertificationName *string `xml:"wd:Certification_Name,omitempty"`
    Issuer *string `xml:"wd:Issuer,omitempty"`
    CertificationNumber *string `xml:"wd:Certification_Number,omitempty"`
    IssuedDate *string `xml:"wd:Issued_Date,omitempty"`
    ExpirationDate *string `xml:"wd:Expiration_Date,omitempty"`
    ExaminationScore *string `xml:"wd:Examination_Score,omitempty"`
    ExaminationDate *string `xml:"wd:Examination_Date,omitempty"`
    SpecialtyAchievementData *SpecialtyAchievementData `xml:"wd:Specialty_Achievement_Data,omitempty"`
    WorkerDocumentData *WorkerDocumentData `xml:"wd:Worker_Document_Data,omitempty"`
}

type SpecialtyAchievementData struct {
    SpecialtyReference *SpecialtyReference `xml:"wd:Specialty_Reference,omitempty"`
    StartDate *string `xml:"wd:Start_Date,omitempty"`
    EndDate *string `xml:"wd:End_Date,omitempty"`
    SubspecialtyReference *SubspecialtyReference `xml:"wd:Subspecialty_Reference,omitempty"`
}

type SpecialtyReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type SubspecialtyReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type WorkerDocumentData struct {
    FileName *string `xml:"wd:File_Name,omitempty"`
    Comment *string `xml:"wd:Comment,omitempty"`
    File *string `xml:"wd:File,omitempty"`
    DocumentCategoryReference *DocumentCategoryReference `xml:"wd:Document_Category_Reference,omitempty"`
    ContentType *string `xml:"wd:Content_Type,omitempty"`
}

type DocumentCategoryReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Training struct {
    TrainingReference *TrainingReference `xml:"wd:Training_Reference,omitempty"`
    TrainingData *TrainingData `xml:"wd:Training_Data,omitempty"`
}

type TrainingReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type TrainingData struct {
    TrainingId *string `xml:"wd:Training_ID,omitempty"`
    RemoveTraining *bool `xml:"wd:Remove_Training,omitempty"`
    Training *string `xml:"wd:Training,omitempty"`
    Description *string `xml:"wd:Description,omitempty"`
    TrainingTypeReference *TrainingTypeReference `xml:"wd:Training_Type_Reference,omitempty"`
    CompletionDate *string `xml:"wd:Completion_Date,omitempty"`
    TrainingDuration *string `xml:"wd:Training_Duration,omitempty"`
}

type TrainingTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type AwardAndActivity struct {
    AwardAndActivityReference *AwardAndActivityReference `xml:"wd:Award_and_Activity_Reference,omitempty"`
    AwardAndActivityData *AwardAndActivityData `xml:"wd:Award_and_Activity_Data,omitempty"`
}

type AwardAndActivityReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type AwardAndActivityData struct {
    AwardAndActivityId *string `xml:"wd:Award_and_Activity_ID,omitempty"`
    RemoveAwardAndActivity *bool `xml:"wd:Remove_Award_and_Activity,omitempty"`
    AwardAndActivityTypeReference *AwardAndActivityTypeReference `xml:"wd:Award_and_Activity_Type_Reference,omitempty"`
    Title *string `xml:"wd:Title,omitempty"`
    SponsorIssuer *string `xml:"wd:Sponsor_Issuer,omitempty"`
    StartDate *string `xml:"wd:Start_Date,omitempty"`
    EndDate *string `xml:"wd:End_Date,omitempty"`
    Description *string `xml:"wd:Description,omitempty"`
    Url *string `xml:"wd:URL,omitempty"`
    RelatedPositionReference *RelatedPositionReference `xml:"wd:Related_Position_Reference,omitempty"`
}

type AwardAndActivityTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type RelatedPositionReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type OrganizationMembership struct {
    OrganizationProfessionalAffiliationReference *OrganizationProfessionalAffiliationReference `xml:"wd:Organization_Professional_Affiliation_Reference,omitempty"`
    OrganizationProfessionalAffiliationData *OrganizationProfessionalAffiliationData `xml:"wd:Organization_Professional_Affiliation_Data,omitempty"`
}

type OrganizationProfessionalAffiliationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type OrganizationProfessionalAffiliationData struct {
    ProfessionalAffiliationId *string `xml:"wd:Professional_Affiliation_ID,omitempty"`
    RemoveProfessionalAffiliation *bool `xml:"wd:Remove_Professional_Affiliation,omitempty"`
    ProfessionalAffiliationReference *ProfessionalAffiliationReference `xml:"wd:Professional_Affiliation_Reference,omitempty"`
    ProfessionalAffiliation *string `xml:"wd:Professional_Affiliation,omitempty"`
    ProfessionalAffiliationTypeReference *ProfessionalAffiliationTypeReference `xml:"wd:Professional_Affiliation_Type_Reference,omitempty"`
    Affiliation *string `xml:"wd:Affiliation,omitempty"`
    ProfessionalAffiliationRelationshipTypeReference *ProfessionalAffiliationRelationshipTypeReference `xml:"wd:Professional_Affiliation_Relationship_Type_Reference,omitempty"`
    BeginDate *string `xml:"wd:Begin_Date,omitempty"`
    EndDate *string `xml:"wd:End_Date,omitempty"`
    ContactInformationData *ContactInformationData `xml:"wd:Contact_Information_Data,omitempty"`
}

type ProfessionalAffiliationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ProfessionalAffiliationTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ProfessionalAffiliationRelationshipTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ContactInformationData struct {
    AddressData *AddressData `xml:"wd:Address_Data,omitempty"`
    PhoneData *PhoneData `xml:"wd:Phone_Data,omitempty"`
    EmailAddressData *EmailAddressData `xml:"wd:Email_Address_Data,omitempty"`
    InstantMessengerData *InstantMessengerData `xml:"wd:Instant_Messenger_Data,omitempty"`
    WebAddressData *WebAddressData `xml:"wd:Web_Address_Data,omitempty"`
}

type Education struct {
    EducationReference *EducationReference `xml:"wd:Education_Reference,omitempty"`
    EducationData *EducationData `xml:"wd:Education_Data,omitempty"`
}

type EducationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type EducationData struct {
    EducationId *string `xml:"wd:Education_ID,omitempty"`
    RemoveEducation *bool `xml:"wd:Remove_Education,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    SchoolReference *SchoolReference `xml:"wd:School_Reference,omitempty"`
    SchoolName *string `xml:"wd:School_Name,omitempty"`
    SchoolTypeReference *SchoolTypeReference `xml:"wd:School_Type_Reference,omitempty"`
    Location *string `xml:"wd:Location,omitempty"`
    DegreeReference *DegreeReference `xml:"wd:Degree_Reference,omitempty"`
    DegreeCompletedReference *DegreeCompletedReference `xml:"wd:Degree_Completed_Reference,omitempty"`
    DateDegreeReceived *string `xml:"wd:Date_Degree_Received,omitempty"`
    FieldOfStudyReference *FieldOfStudyReference `xml:"wd:Field_Of_Study_Reference,omitempty"`
    GradeAverage *string `xml:"wd:Grade_Average,omitempty"`
    FirstYearAttended *string `xml:"wd:First_Year_Attended,omitempty"`
    LastYearAttended *string `xml:"wd:Last_Year_Attended,omitempty"`
    IsHighestLevelOfEducation *bool `xml:"wd:Is_Highest_Level_of_Education,omitempty"`
    FirstDayAttended *string `xml:"wd:First_Day_Attended,omitempty"`
    LastDayAttended *string `xml:"wd:Last_Day_Attended,omitempty"`
    EducationAttachmentData *EducationAttachmentData `xml:"wd:Education_Attachment_Data,omitempty"`
}

type SchoolReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type SchoolTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type DegreeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type DegreeCompletedReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type FieldOfStudyReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type EducationAttachmentData struct {
    FileName *string `xml:"wd:File_Name,omitempty"`
    Comment *string `xml:"wd:Comment,omitempty"`
    File *string `xml:"wd:File,omitempty"`
    DocumentCategoryReference *DocumentCategoryReference `xml:"wd:Document_Category_Reference,omitempty"`
}

type WorkExperience struct {
    ExperienceReference *ExperienceReference `xml:"wd:Experience_Reference,omitempty"`
    RemoveExperience *bool `xml:"wd:Remove_Experience,omitempty"`
    ExperienceRatingReference *ExperienceRatingReference `xml:"wd:Experience_Rating_Reference,omitempty"`
    ExperienceComment *string `xml:"wd:Experience_Comment,omitempty"`
}

type ExperienceReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ExperienceRatingReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Language struct {
    LanguageReference *LanguageReference `xml:"wd:Language_Reference,omitempty"`
    RemoveLanguage *bool `xml:"wd:Remove_Language,omitempty"`
    NativeLanguage *bool `xml:"wd:Native_Language,omitempty"`
    LanguageAbility *LanguageAbility `xml:"wd:Language_Ability,omitempty"`
    AssessedOn *string `xml:"wd:Assessed_On,omitempty"`
    Note *string `xml:"wd:Note,omitempty"`
    AssessedByWorkerReference *AssessedByWorkerReference `xml:"wd:Assessed_by_Worker_Reference,omitempty"`
}

type LanguageReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type LanguageAbility struct {
    LanguageAbilityData *LanguageAbilityData `xml:"wd:Language_Ability_Data,omitempty"`
}

type LanguageAbilityData struct {
    LanguageProficiencyReference *LanguageProficiencyReference `xml:"wd:Language_Proficiency_Reference,omitempty"`
    LanguageAbilityTypeReference *LanguageAbilityTypeReference `xml:"wd:Language_Ability_Type_Reference,omitempty"`
}

type LanguageProficiencyReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type LanguageAbilityTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type AssessedByWorkerReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type InternalProjectExperience struct {
    InternalProjectExperienceReference *InternalProjectExperienceReference `xml:"wd:Internal_Project_Experience_Reference,omitempty"`
    InternalProjectExperienceData *InternalProjectExperienceData `xml:"wd:Internal_Project_Experience_Data,omitempty"`
}

type InternalProjectExperienceReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type InternalProjectExperienceData struct {
    InternalProjectExperienceId *string `xml:"wd:Internal_Project_Experience_ID,omitempty"`
    RemoveInternalProjectExperience *bool `xml:"wd:Remove_Internal_Project_Experience,omitempty"`
    InternalProject *string `xml:"wd:Internal_Project,omitempty"`
    Description *string `xml:"wd:Description,omitempty"`
    StartDate *string `xml:"wd:Start_Date,omitempty"`
    EndDate *string `xml:"wd:End_Date,omitempty"`
    ProjectLeader *string `xml:"wd:Project_Leader,omitempty"`
}

type RecruitingData struct {
    ApplicantEnteredDate *string `xml:"wd:Applicant_Entered_Date,omitempty"`
    ApplicantComments *string `xml:"wd:Applicant_Comments,omitempty"`
    EligibleForHireReference *EligibleForHireReference `xml:"wd:Eligible_For_Hire_Reference,omitempty"`
    EligibleForRehireComments *string `xml:"wd:Eligible_for_Rehire_Comments,omitempty"`
    ApplicantHasMarkedAsNoShowReference *ApplicantHasMarkedAsNoShowReference `xml:"wd:Applicant_Has_Marked_as_No_Show_Reference,omitempty"`
    ApplicantSourceReference *ApplicantSourceReference `xml:"wd:Applicant_Source_Reference,omitempty"`
    ReferredByWorkerReference *ReferredByWorkerReference `xml:"wd:Referred_by_Worker_Reference,omitempty"`
    PositionsConsideredForReference *PositionsConsideredForReference `xml:"wd:Positions_Considered_for_Reference,omitempty"`
}

type EligibleForHireReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ApplicantHasMarkedAsNoShowReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ApplicantSourceReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ReferredByWorkerReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PositionsConsideredForReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ResumeData struct {
    Resume *Resume `xml:"wd:Resume,omitempty"`
    FileId *string `xml:"wd:File_ID,omitempty"`
    File *string `xml:"wd:File,omitempty"`
    Filename *string `xml:"wd:FileName,omitempty"`
    Comments *string `xml:"wd:Comments,omitempty"`
}

type Resume struct {
    ResumeReference *ResumeReference `xml:"wd:Resume_Reference,omitempty"`
    ResumeData *ResumeData `xml:"wd:Resume_Data,omitempty"`
}

type ResumeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type BackgroundCheckData struct {
    StatusDate *string `xml:"wd:Status_Date,omitempty"`
    StatusReference *StatusReference `xml:"wd:Status_Reference,omitempty"`
    StatusComment *string `xml:"wd:Status_Comment,omitempty"`
}

type ExternalIntegrationIdData struct {
    Id *Id `xml:"wd:ID,omitempty"`
}

type DocumentFieldResultData struct {
    FieldReference *FieldReference `xml:"wd:Field_Reference,omitempty"`
    Value *string `xml:"wd:Value,omitempty"`
}

type FieldReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

