// Programmatically generated by gen_structs.py
package change_home_contact_information_response

import "encoding/xml"

type ChangeHomeContactInformationResponse struct {
    XMLName xml.Name `xml:"Change_Home_Contact_Information_Response"`
    Version *string `xml:"version,attr,omitempty"`
    ChangeHomeContactInformationEventReference *ChangeHomeContactInformationEventReference `xml:"Change_Home_Contact_Information_Event_Reference,omitempty"`
}

type ChangeHomeContactInformationEventReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Id struct {
    Type *string `xml:"type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

