// Programmatically generated by gen_structs.py
package get_job_application_additional_data_request

import "encoding/xml"

type GetJobApplicationAdditionalDataRequest struct {
    XMLName xml.Name `xml:"wd:Get_Job_Application_Additional_Data_Request"`
    XMLNamespace *string `xml:"xmlns:wd,attr,omitempty"`
    Version *string `xml:"wd:version,attr,omitempty"`
    RequestReferences *RequestReferences `xml:"wd:Request_References,omitempty"`
    RequestCriteria *RequestCriteria `xml:"wd:Request_Criteria,omitempty"`
    ResponseFilter *ResponseFilter `xml:"wd:Response_Filter,omitempty"`
    ResponseGroup *ResponseGroup `xml:"wd:Response_Group,omitempty"`
}

type RequestReferences struct {
    JobApplicationReference *JobApplicationReference `xml:"wd:Job_Application_Reference,omitempty"`
}

type JobApplicationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Id struct {
    Type *string `xml:"wd:type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type RequestCriteria struct {
    CandidateReference *CandidateReference `xml:"wd:Candidate_Reference,omitempty"`
}

type CandidateReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ResponseFilter struct {
    AsOfEffectiveDate *string `xml:"wd:As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"wd:As_Of_Entry_DateTime,omitempty"`
    Page *int `xml:"wd:Page,omitempty"`
    Count *int `xml:"wd:Count,omitempty"`
}

type ResponseGroup struct {
    IncludeReference *bool `xml:"wd:Include_Reference,omitempty"`
}

