// Programmatically generated by gen_structs.py
package employee_personal_info

import "encoding/xml"

type EmployeePersonalInfo struct {
    XMLName xml.Name `xml:"Employee_Personal_Info"`
    AsOfDate *string `xml:"As_Of_Date,attr,omitempty"`
    AsOfMoment *string `xml:"As_Of_Moment,attr,omitempty"`
    Version *string `xml:"version,attr,omitempty"`
    EmployeeReference *EmployeeReference `xml:"Employee_Reference,omitempty"`
    EmployeePersonalInfoData *EmployeePersonalInfoData `xml:"Employee_Personal_Info_Data,omitempty"`
}

type EmployeeReference struct {
    IntegrationIdReference *IntegrationIdReference `xml:"Integration_ID_Reference,omitempty"`
}

type IntegrationIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Id struct {
    SystemId *string `xml:"System_ID,attr,omitempty"`
    Value *string `xml:",chardata"`
    Type *string `xml:"type,attr,omitempty"`
}

type EmployeePersonalInfoData struct {
    ExternalIntegrationIdData *ExternalIntegrationIdData `xml:"External_Integration_ID_Data,omitempty"`
    PersonalInfoData *PersonalInfoData `xml:"Personal_Info_Data,omitempty"`
}

type ExternalIntegrationIdData struct {
    Id *Id `xml:"ID,omitempty"`
}

type PersonalInfoData struct {
    BusinessTitle *string `xml:"Business_Title,omitempty"`
    PersonData *PersonData `xml:"Person_Data,omitempty"`
    QualificationData *QualificationData `xml:"Qualification_Data,omitempty"`
}

type PersonData struct {
    NameData *NameData `xml:"Name_Data,omitempty"`
    ContactData *ContactData `xml:"Contact_Data,omitempty"`
    DemographicData *DemographicData `xml:"Demographic_Data,omitempty"`
    BiographicData *BiographicData `xml:"Biographic_Data,omitempty"`
    VisaIdData *VisaIdData `xml:"Visa_ID_Data,omitempty"`
    CustomIdData *CustomIdData `xml:"Custom_ID_Data,omitempty"`
    GovernmentIdData *GovernmentIdData `xml:"Government_ID_Data,omitempty"`
    LicenseIdData *LicenseIdData `xml:"License_ID_Data,omitempty"`
    PassportIdData *PassportIdData `xml:"Passport_ID_Data,omitempty"`
    PersonalPreferencesData *PersonalPreferencesData `xml:"Personal_Preferences_Data,omitempty"`
}

type NameData struct {
    IsLegal *string `xml:"Is_Legal,attr,omitempty"`
    IsPreferred *string `xml:"Is_Preferred,attr,omitempty"`
    EffectiveDate *string `xml:"Effective_Date,attr,omitempty"`
    LastModified *string `xml:"Last_Modified,attr,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    AdditionalNameType *string `xml:"Additional_Name_Type,omitempty"`
    Prefix *Prefix `xml:"Prefix,omitempty"`
    FirstName *string `xml:"First_Name,omitempty"`
    MiddleName *string `xml:"Middle_Name,omitempty"`
    LastName *LastName `xml:"Last_Name,omitempty"`
    LocalNameData *LocalNameData `xml:"Local_Name_Data,omitempty"`
    Suffix *Suffix `xml:"Suffix,omitempty"`
}

type CountryReference struct {
    CountryIsoCode *string `xml:"Country_ISO_Code,omitempty"`
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Prefix struct {
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type LastName struct {
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type LocalNameData struct {
    LocalName *string `xml:"Local_Name,attr,omitempty"`
    LocalScript *string `xml:"Local_Script,attr,omitempty"`
    FirstName *string `xml:"First_Name,omitempty"`
    MiddleName *string `xml:"Middle_Name,omitempty"`
    LastName *LastName `xml:"Last_Name,omitempty"`
}

type Suffix struct {
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type ContactData struct {
    InternetEmailAddressData *InternetEmailAddressData `xml:"Internet_Email_Address_Data,omitempty"`
    PhoneNumberData *PhoneNumberData `xml:"Phone_Number_Data,omitempty"`
    AddressData *AddressData `xml:"Address_Data,omitempty"`
    WebAddressData *WebAddressData `xml:"Web_Address_Data,omitempty"`
    InstantMessengerData *InstantMessengerData `xml:"Instant_Messenger_Data,omitempty"`
}

type InternetEmailAddressData struct {
    EmailAddress *string `xml:"Email_Address,omitempty"`
    EmailComment *string `xml:"Email_Comment,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
}

type UsageData struct {
    Public *string `xml:"Public,attr,omitempty"`
    TypeReference *TypeReference `xml:"Type_Reference,omitempty"`
    UseForReference *string `xml:"Use_For_Reference,omitempty"`
    Comments *string `xml:"Comments,omitempty"`
}

type TypeReference struct {
    Primary *string `xml:"Primary,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type PhoneNumberData struct {
    CountryIsoCode *string `xml:"Country_ISO_Code,omitempty"`
    InternationalPhoneCode *string `xml:"International_Phone_Code,omitempty"`
    AreaCode *string `xml:"Area_Code,omitempty"`
    PhoneNumber *string `xml:"Phone_Number,omitempty"`
    PhoneExtension *string `xml:"Phone_Extension,omitempty"`
    PhoneDeviceTypeReference *PhoneDeviceTypeReference `xml:"Phone_Device_Type_Reference,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
}

type PhoneDeviceTypeReference struct {
    PhoneDeviceTypeDescription *string `xml:"Phone_Device_Type_Description,omitempty"`
}

type AddressData struct {
    LastModified *string `xml:"Last_Modified,attr,omitempty"`
    EffectiveDate *string `xml:"Effective_Date,attr,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    AddressLine *AddressLine `xml:"Address_Line,omitempty"`
    Municipality *string `xml:"Municipality,omitempty"`
    Submunicipality *string `xml:"Submunicipality,omitempty"`
    Region *string `xml:"Region,omitempty"`
    Subregion *Subregion `xml:"Subregion,omitempty"`
    PostalCode *string `xml:"Postal_Code,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
}

type AddressLine struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type Subregion struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type WebAddressData struct {
    WebAddress *string `xml:"Web_Address,omitempty"`
    WebAddressComment *string `xml:"Web_Address_Comment,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
}

type InstantMessengerData struct {
    InstantMessengerAddress *string `xml:"Instant_Messenger_Address,omitempty"`
    InstantMessengerComment *string `xml:"Instant_Messenger_Comment,omitempty"`
    InstantMessengerTypeReference *InstantMessengerTypeReference `xml:"Instant_Messenger_Type_Reference,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
}

type InstantMessengerTypeReference struct {
    InstantMessengerProvider *string `xml:"Instant_Messenger_Provider,omitempty"`
}

type DemographicData struct {
    MaritalStatusReference *MaritalStatusReference `xml:"Marital_Status_Reference,omitempty"`
    HispanicOrLatino *bool `xml:"Hispanic_or_Latino,omitempty"`
    EthnicityReference *EthnicityReference `xml:"Ethnicity_Reference,omitempty"`
    CitizenshipStatusReference *CitizenshipStatusReference `xml:"Citizenship_Status_Reference,omitempty"`
    NationalityReference *NationalityReference `xml:"Nationality_Reference,omitempty"`
    HukouRegionReference *HukouRegionReference `xml:"Hukou_Region_Reference,omitempty"`
    HukouSubregionReference *HukouSubregionReference `xml:"Hukou_Subregion_Reference,omitempty"`
    HukouLocality *string `xml:"Hukou_Locality,omitempty"`
    HukouPostalCode *string `xml:"Hukou_Postal_Code,omitempty"`
    HukouTypeReference *HukouTypeReference `xml:"Hukou_Type_Reference,omitempty"`
    NativeRegionReference *NativeRegionReference `xml:"Native_Region_Reference,omitempty"`
    PersonnelFileAgency *string `xml:"Personnel_File_Agency,omitempty"`
    MilitaryServiceData *MilitaryServiceData `xml:"Military_Service_Data,omitempty"`
}

type MaritalStatusReference struct {
    MaritalStatusDescription *string `xml:"Marital_Status_Description,omitempty"`
}

type EthnicityReference struct {
    EthnicityName *string `xml:"Ethnicity_Name,omitempty"`
    RegulatoryRegionOrganizationReference *RegulatoryRegionOrganizationReference `xml:"Regulatory_Region_Organization_Reference,omitempty"`
}

type RegulatoryRegionOrganizationReference struct {
    IntegrationIdReference *IntegrationIdReference `xml:"Integration_ID_Reference,omitempty"`
}

type CitizenshipStatusReference struct {
    CitizenshipStatusDescription *string `xml:"Citizenship_Status_Description,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
}

type NationalityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HukouRegionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HukouSubregionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HukouTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type NativeRegionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryServiceData struct {
    MilitaryStatusReference *MilitaryStatusReference `xml:"Military_Status_Reference,omitempty"`
    MilitaryDischargeDate *string `xml:"Military_Discharge_Date,omitempty"`
}

type MilitaryStatusReference struct {
    MilitaryStatusName *string `xml:"Military_Status_Name,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
}

type BiographicData struct {
    CountryOfBirthReference *CountryOfBirthReference `xml:"Country_Of_Birth_Reference,omitempty"`
    PlaceOfBirth *string `xml:"Place_Of_Birth,omitempty"`
    DateOfBirth *string `xml:"Date_Of_Birth,omitempty"`
    GenderReference *GenderReference `xml:"Gender_Reference,omitempty"`
    DisabilityReference *DisabilityReference `xml:"Disability_Reference,omitempty"`
    UsesTobacco *bool `xml:"Uses_Tobacco,omitempty"`
}

type CountryOfBirthReference struct {
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
}

type GenderReference struct {
    GenderDescription *string `xml:"Gender_Description,omitempty"`
}

type DisabilityReference struct {
    DisabilityName *string `xml:"Disability_Name,omitempty"`
    RegulatoryRegionOrganizationReference *RegulatoryRegionOrganizationReference `xml:"Regulatory_Region_Organization_Reference,omitempty"`
}

type VisaIdData struct {
    VisaId *string `xml:"Visa_ID,omitempty"`
    VisaTypeReference *VisaTypeReference `xml:"Visa_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
}

type VisaTypeReference struct {
    VisaTypeName *string `xml:"Visa_Type_Name,omitempty"`
}

type CustomIdData struct {
    CustomId *string `xml:"Custom_ID,omitempty"`
    CustomIdTypeReference *CustomIdTypeReference `xml:"Custom_ID_Type_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    OrganizationReference *OrganizationReference `xml:"Organization_Reference,omitempty"`
    CustomDescription *string `xml:"Custom_Description,omitempty"`
}

type CustomIdTypeReference struct {
    CustomIdTypeName *string `xml:"Custom_ID_Type_Name,omitempty"`
}

type OrganizationReference struct {
    IntegrationIdReference *IntegrationIdReference `xml:"Integration_ID_Reference,omitempty"`
}

type GovernmentIdData struct {
    GovernmentId *string `xml:"Government_ID,omitempty"`
    GovernmentIdTypeReference *GovernmentIdTypeReference `xml:"Government_ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
}

type GovernmentIdTypeReference struct {
    GovernmentIdTypeName *string `xml:"Government_ID_Type_Name,omitempty"`
}

type LicenseIdData struct {
    LicenseId *string `xml:"License_ID,omitempty"`
    LicenseTypeReference *LicenseTypeReference `xml:"License_Type_Reference,omitempty"`
    LicenseClass *string `xml:"License_Class,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    CountryRegionReference *CountryRegionReference `xml:"Country_Region_Reference,omitempty"`
    AuthorityReference *AuthorityReference `xml:"Authority_Reference,omitempty"`
}

type LicenseTypeReference struct {
    LicenseTypeName *string `xml:"License_Type_Name,omitempty"`
}

type CountryRegionReference struct {
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    CountryRegionName *string `xml:"Country_Region_Name,omitempty"`
}

type AuthorityReference struct {
    AuthorityName *string `xml:"Authority_Name,omitempty"`
    RegulatoryRegionOrganizationReference *RegulatoryRegionOrganizationReference `xml:"Regulatory_Region_Organization_Reference,omitempty"`
}

type PassportIdData struct {
    PassportNumber *string `xml:"Passport_Number,omitempty"`
    PassportTypeReference *PassportTypeReference `xml:"Passport_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
}

type PassportTypeReference struct {
    PassportTypeName *string `xml:"Passport_Type_Name,omitempty"`
}

type PersonalPreferencesData struct {
    ReceiveEmailNotifications *bool `xml:"Receive_Email_Notifications,omitempty"`
}

type QualificationData struct {
    EducationData *EducationData `xml:"Education_Data,omitempty"`
    ProfessionalExperienceData *ProfessionalExperienceData `xml:"Professional_Experience_Data,omitempty"`
}

type EducationData struct {
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    SchoolReference *SchoolReference `xml:"School_Reference,omitempty"`
    EducationInstitution *string `xml:"Education_Institution,omitempty"`
    EducationalInstitutionTypeReference *EducationalInstitutionTypeReference `xml:"Educational_Institution_Type_Reference,omitempty"`
    DegreeReference *DegreeReference `xml:"Degree_Reference,omitempty"`
    DegreeCompletedReference *DegreeCompletedReference `xml:"Degree_Completed_Reference,omitempty"`
    FieldOfStudyReference *FieldOfStudyReference `xml:"Field_Of_Study_Reference,omitempty"`
    EducationInstitutionLocation *string `xml:"Education_Institution_Location,omitempty"`
    EducationGradeAverage *string `xml:"Education_Grade_Average,omitempty"`
    FirstYearAttended *string `xml:"First_Year_Attended,omitempty"`
    LastYearAttended *string `xml:"Last_Year_Attended,omitempty"`
}

type SchoolReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EducationalInstitutionTypeReference struct {
    InstitutionTypeName *string `xml:"Institution_Type_Name,omitempty"`
}

type DegreeReference struct {
    DegreeName *string `xml:"Degree_Name,omitempty"`
}

type DegreeCompletedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type FieldOfStudyReference struct {
    FieldOfStudyName *string `xml:"Field_Of_Study_Name,omitempty"`
}

type ProfessionalExperienceData struct {
    ProfessionalExperience *string `xml:"Professional_Experience,omitempty"`
    ProfessionalExperienceRatingReference *ProfessionalExperienceRatingReference `xml:"Professional_Experience_Rating_Reference,omitempty"`
    ProfessionalExperienceComment *string `xml:"Professional_Experience_Comment,omitempty"`
}

type ProfessionalExperienceRatingReference struct {
    RatingDescription *string `xml:"Rating_Description,omitempty"`
}

