// Programmatically generated by gen_structs.py
package get_candidates_request

import "encoding/xml"

type GetCandidatesRequest struct {
    XMLName xml.Name `xml:"wd:Get_Candidates_Request"`
    XMLNamespace *string `xml:"xmlns:wd,attr,omitempty"`
    Version *string `xml:"wd:version,attr,omitempty"`
    RequestReferences *RequestReferences `xml:"wd:Request_References,omitempty"`
    RequestCriteria *RequestCriteria `xml:"wd:Request_Criteria,omitempty"`
    ResponseFilter *ResponseFilter `xml:"wd:Response_Filter,omitempty"`
    ResponseGroup *ResponseGroup `xml:"wd:Response_Group,omitempty"`
}

type RequestReferences struct {
    SkipNonExistingInstances *string `xml:"wd:Skip_Non_Existing_Instances,attr,omitempty"`
    CandidateReference *CandidateReference `xml:"wd:Candidate_Reference,omitempty"`
}

type CandidateReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Id struct {
    Type *string `xml:"wd:type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type RequestCriteria struct {
    TransactionLogCriteriaData *TransactionLogCriteriaData `xml:"wd:Transaction_Log_Criteria_Data,omitempty"`
    FirstName *string `xml:"wd:First_Name,omitempty"`
    LastName *string `xml:"wd:Last_Name,omitempty"`
    CandidateEmailAddress *string `xml:"wd:Candidate_Email_Address,omitempty"`
    PreHireReference *PreHireReference `xml:"wd:Pre_Hire_Reference,omitempty"`
    WorkerReference *WorkerReference `xml:"wd:Worker_Reference,omitempty"`
    JobRequisitionReference *JobRequisitionReference `xml:"wd:Job_Requisition_Reference,omitempty"`
    RecruitingStageReference *RecruitingStageReference `xml:"wd:Recruiting_Stage_Reference,omitempty"`
    ApplicantSourceReference *ApplicantSourceReference `xml:"wd:Applicant_Source_Reference,omitempty"`
    CandidateTagReference *CandidateTagReference `xml:"wd:Candidate_Tag_Reference,omitempty"`
    AppliedFrom *string `xml:"wd:Applied_From,omitempty"`
    AppliedThrough *string `xml:"wd:Applied_Through,omitempty"`
    InternalWorkersOnly *bool `xml:"wd:Internal_Workers_Only,omitempty"`
    CreatedFrom *string `xml:"wd:Created_From,omitempty"`
    CreatedThrough *string `xml:"wd:Created_Through,omitempty"`
    CriteriaMatchScoreCategoryReference *CriteriaMatchScoreCategoryReference `xml:"wd:Criteria_Match_Score_Category_Reference,omitempty"`
    StaticCandidatePoolReference *StaticCandidatePoolReference `xml:"wd:Static_Candidate_Pool_Reference,omitempty"`
}

type TransactionLogCriteriaData struct {
    TransactionDateRangeData *TransactionDateRangeData `xml:"wd:Transaction_Date_Range_Data,omitempty"`
    TransactionTypeReferences *TransactionTypeReferences `xml:"wd:Transaction_Type_References,omitempty"`
    SubscriberReference *SubscriberReference `xml:"wd:Subscriber_Reference,omitempty"`
}

type TransactionDateRangeData struct {
    UpdatedFrom *string `xml:"wd:Updated_From,omitempty"`
    UpdatedThrough *string `xml:"wd:Updated_Through,omitempty"`
    EffectiveFrom *string `xml:"wd:Effective_From,omitempty"`
    EffectiveThrough *string `xml:"wd:Effective_Through,omitempty"`
}

type TransactionTypeReferences struct {
    TransactionTypeReference *TransactionTypeReference `xml:"wd:Transaction_Type_Reference,omitempty"`
}

type TransactionTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type SubscriberReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PreHireReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type WorkerReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type JobRequisitionReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type RecruitingStageReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ApplicantSourceReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CandidateTagReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CriteriaMatchScoreCategoryReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type StaticCandidatePoolReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ResponseFilter struct {
    AsOfEffectiveDate *string `xml:"wd:As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"wd:As_Of_Entry_DateTime,omitempty"`
    Page *int `xml:"wd:Page,omitempty"`
    Count *int `xml:"wd:Count,omitempty"`
}

type ResponseGroup struct {
    IncludeReference *bool `xml:"wd:Include_Reference,omitempty"`
    ExcludeAllAttachments *bool `xml:"wd:Exclude_All_Attachments,omitempty"`
}

