// Programmatically generated by gen_structs.py
package get_applicants_request

import "encoding/xml"

type GetApplicantsRequest struct {
    XMLName xml.Name `xml:"wd:Get_Applicants_Request"`
    XMLNamespace *string `xml:"xmlns:wd,attr,omitempty"`
    Version *string `xml:"wd:version,attr,omitempty"`
    RequestReferences *RequestReferences `xml:"wd:Request_References,omitempty"`
    RequestCriteria *RequestCriteria `xml:"wd:Request_Criteria,omitempty"`
    ResponseFilter *ResponseFilter `xml:"wd:Response_Filter,omitempty"`
    ResponseGroup *ResponseGroup `xml:"wd:Response_Group,omitempty"`
}

type RequestReferences struct {
    ApplicantReference *ApplicantReference `xml:"wd:Applicant_Reference,omitempty"`
}

type ApplicantReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Id struct {
    Type *string `xml:"wd:type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type RequestCriteria struct {
    WorkerReference *WorkerReference `xml:"wd:Worker_Reference,omitempty"`
    FormerWorkerReference *FormerWorkerReference `xml:"wd:Former_Worker_Reference,omitempty"`
    EmailAddress *string `xml:"wd:Email_Address,omitempty"`
    FieldAndParameterCriteriaData *FieldAndParameterCriteriaData `xml:"wd:Field_And_Parameter_Criteria_Data,omitempty"`
}

type WorkerReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type FormerWorkerReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type FieldAndParameterCriteriaData struct {
    ProviderReference *ProviderReference `xml:"wd:Provider_Reference,omitempty"`
}

type ProviderReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ResponseFilter struct {
    AsOfEffectiveDate *string `xml:"wd:As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"wd:As_Of_Entry_DateTime,omitempty"`
    Page *int `xml:"wd:Page,omitempty"`
    Count *int `xml:"wd:Count,omitempty"`
}

type ResponseGroup struct {
    IncludeReference *bool `xml:"wd:Include_Reference,omitempty"`
    IncludePersonalInformation *bool `xml:"wd:Include_Personal_Information,omitempty"`
    ShowAllPersonalInformation *bool `xml:"wd:Show_All_Personal_Information,omitempty"`
    IncludeRecruitingInformation *bool `xml:"wd:Include_Recruiting_Information,omitempty"`
    IncludeQualificationProfile *bool `xml:"wd:Include_Qualification_Profile,omitempty"`
    IncludeResume *bool `xml:"wd:Include_Resume,omitempty"`
    IncludeBackgroundCheck *bool `xml:"wd:Include_Background_Check,omitempty"`
    IncludeExternalIntegrationIdData *bool `xml:"wd:Include_External_Integration_ID_Data,omitempty"`
}

