// Programmatically generated by gen_structs.py
package put_job_application_additional_data_request

import "encoding/xml"

type PutJobApplicationAdditionalDataRequest struct {
    XMLName xml.Name `xml:"wd:Put_Job_Application_Additional_Data_Request"`
    XMLNamespace *string `xml:"xmlns:wd,attr,omitempty"`
    Version *string `xml:"wd:version,attr,omitempty"`
    JobApplicationCustomObjectData *JobApplicationCustomObjectData `xml:"wd:Job_Application_Custom_Object_Data,omitempty"`
}

type JobApplicationCustomObjectData struct {
    JobApplicationReference *JobApplicationReference `xml:"wd:Job_Application_Reference,omitempty"`
    BusinessObjectAdditionalData *BusinessObjectAdditionalData `xml:"wd:Business_Object_Additional_Data,omitempty"`
}

type JobApplicationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Id struct {
    Type *string `xml:"wd:type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type BusinessObjectAdditionalData struct {
    Anyelement *string `xml:"wd:AnyElement,omitempty"`
}

