// Programmatically generated by gen_structs.py
package get_candidates_response

import "encoding/xml"

type GetCandidatesResponse struct {
    XMLName xml.Name `xml:"Get_Candidates_Response"`
    Version *string `xml:"version,attr,omitempty"`
    RequestReferences *RequestReferences `xml:"Request_References,omitempty"`
    RequestCriteria *RequestCriteria `xml:"Request_Criteria,omitempty"`
    ResponseFilter *ResponseFilter `xml:"Response_Filter,omitempty"`
    ResponseGroup *ResponseGroup `xml:"Response_Group,omitempty"`
    ResponseResults *ResponseResults `xml:"Response_Results,omitempty"`
    ResponseData *ResponseData `xml:"Response_Data,omitempty"`
}

type RequestReferences struct {
    SkipNonExistingInstances *string `xml:"Skip_Non_Existing_Instances,attr,omitempty"`
    CandidateReference *CandidateReference `xml:"Candidate_Reference,omitempty"`
}

type CandidateReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Id struct {
    Type *string `xml:"type,attr,omitempty"`
    Value *string `xml:",chardata"`
    ParentId *string `xml:"parent_id,attr,omitempty"`
    ParentType *string `xml:"parent_type,attr,omitempty"`
}

type RequestCriteria struct {
    TransactionLogCriteriaData *TransactionLogCriteriaData `xml:"Transaction_Log_Criteria_Data,omitempty"`
    FirstName *string `xml:"First_Name,omitempty"`
    LastName *string `xml:"Last_Name,omitempty"`
    CandidateEmailAddress *string `xml:"Candidate_Email_Address,omitempty"`
    PreHireReference *PreHireReference `xml:"Pre_Hire_Reference,omitempty"`
    WorkerReference *WorkerReference `xml:"Worker_Reference,omitempty"`
    JobRequisitionReference *JobRequisitionReference `xml:"Job_Requisition_Reference,omitempty"`
    RecruitingStageReference *RecruitingStageReference `xml:"Recruiting_Stage_Reference,omitempty"`
    ApplicantSourceReference *ApplicantSourceReference `xml:"Applicant_Source_Reference,omitempty"`
    CandidateTagReference *CandidateTagReference `xml:"Candidate_Tag_Reference,omitempty"`
    AppliedFrom *string `xml:"Applied_From,omitempty"`
    AppliedThrough *string `xml:"Applied_Through,omitempty"`
    InternalWorkersOnly *bool `xml:"Internal_Workers_Only,omitempty"`
    CreatedFrom *string `xml:"Created_From,omitempty"`
    CreatedThrough *string `xml:"Created_Through,omitempty"`
    CriteriaMatchScoreCategoryReference *CriteriaMatchScoreCategoryReference `xml:"Criteria_Match_Score_Category_Reference,omitempty"`
    StaticCandidatePoolReference *StaticCandidatePoolReference `xml:"Static_Candidate_Pool_Reference,omitempty"`
}

type TransactionLogCriteriaData struct {
    TransactionDateRangeData *TransactionDateRangeData `xml:"Transaction_Date_Range_Data,omitempty"`
    TransactionTypeReferences *TransactionTypeReferences `xml:"Transaction_Type_References,omitempty"`
    SubscriberReference *SubscriberReference `xml:"Subscriber_Reference,omitempty"`
}

type TransactionDateRangeData struct {
    UpdatedFrom *string `xml:"Updated_From,omitempty"`
    UpdatedThrough *string `xml:"Updated_Through,omitempty"`
    EffectiveFrom *string `xml:"Effective_From,omitempty"`
    EffectiveThrough *string `xml:"Effective_Through,omitempty"`
}

type TransactionTypeReferences struct {
    TransactionTypeReference *TransactionTypeReference `xml:"Transaction_Type_Reference,omitempty"`
}

type TransactionTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SubscriberReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PreHireReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkerReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type JobRequisitionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type RecruitingStageReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ApplicantSourceReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CandidateTagReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CriteriaMatchScoreCategoryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type StaticCandidatePoolReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ResponseFilter struct {
    AsOfEffectiveDate *string `xml:"As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"As_Of_Entry_DateTime,omitempty"`
    Page *int `xml:"Page,omitempty"`
    Count *int `xml:"Count,omitempty"`
}

type ResponseGroup struct {
    IncludeReference *bool `xml:"Include_Reference,omitempty"`
    ExcludeAllAttachments *bool `xml:"Exclude_All_Attachments,omitempty"`
}

type ResponseResults struct {
    TotalResults *int `xml:"Total_Results,omitempty"`
    TotalPages *int `xml:"Total_Pages,omitempty"`
    PageResults *int `xml:"Page_Results,omitempty"`
    Page *int `xml:"Page,omitempty"`
}

type ResponseData struct {
    Candidate *Candidate `xml:"Candidate,omitempty"`
    QuestionnaireReference *QuestionnaireReference `xml:"Questionnaire_Reference,omitempty"`
    QuestionnaireAnswerData *QuestionnaireAnswerData `xml:"Questionnaire_Answer_Data,omitempty"`
}

type Candidate struct {
    CandidateReference *CandidateReference `xml:"Candidate_Reference,omitempty"`
    CandidateData *CandidateData `xml:"Candidate_Data,omitempty"`
}

type CandidateData struct {
    CandidateId *string `xml:"Candidate_ID,omitempty"`
    PreHireReference *PreHireReference `xml:"Pre_Hire_Reference,omitempty"`
    WorkerReference *WorkerReference `xml:"Worker_Reference,omitempty"`
    NameData *NameData `xml:"Name_Data,omitempty"`
    ContactData *ContactData `xml:"Contact_Data,omitempty"`
    SocialMediaAccountData *SocialMediaAccountData `xml:"Social_Media_Account_Data,omitempty"`
    StatusData *StatusData `xml:"Status_Data,omitempty"`
    JobApplicationData *JobApplicationData `xml:"Job_Application_Data,omitempty"`
    ProspectData *ProspectData `xml:"Prospect_Data,omitempty"`
    ReferralData *ReferralData `xml:"Referral_Data,omitempty"`
    CandidateIdentificationData *CandidateIdentificationData `xml:"Candidate_Identification_Data,omitempty"`
    LanguageReference *LanguageReference `xml:"Language_Reference,omitempty"`
    CandidateTagReference *CandidateTagReference `xml:"Candidate_Tag_Reference,omitempty"`
    CandidatePoolData *CandidatePoolData `xml:"Candidate_Pool_Data,omitempty"`
    CandidateAttachmentData *CandidateAttachmentData `xml:"Candidate_Attachment_Data,omitempty"`
}

type NameData struct {
    LegalName *LegalName `xml:"Legal_Name,omitempty"`
    PreferredName *PreferredName `xml:"Preferred_Name,omitempty"`
}

type LegalName struct {
    NameDetailData *NameDetailData `xml:"Name_Detail_Data,omitempty"`
}

type NameDetailData struct {
    TitleReference *TitleReference `xml:"Title_Reference,omitempty"`
    SalutationSuffixReference *SalutationSuffixReference `xml:"Salutation_Suffix_Reference,omitempty"`
    FullName *string `xml:"Full_Name,omitempty"`
    FirstName *string `xml:"First_Name,omitempty"`
    MiddleName *string `xml:"Middle_Name,omitempty"`
    HereditarySuffixReference *HereditarySuffixReference `xml:"Hereditary_Suffix_Reference,omitempty"`
    LastName *string `xml:"Last_Name,omitempty"`
    SecondaryLastName *string `xml:"Secondary_Last_Name,omitempty"`
    TertiaryLastName *string `xml:"Tertiary_Last_Name,omitempty"`
    SocialSuffixReference *SocialSuffixReference `xml:"Social_Suffix_Reference,omitempty"`
    LocalPersonName *LocalPersonName `xml:"Local_Person_Name,omitempty"`
}

type TitleReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SalutationSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HereditarySuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SocialSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LocalPersonName struct {
    FirstNameLocal *string `xml:"First_Name___Local,omitempty"`
    MiddleNameLocal *string `xml:"Middle_Name___Local,omitempty"`
    LastNameLocal *string `xml:"Last_Name___Local,omitempty"`
    SecondaryLastNameLocal *string `xml:"Secondary_Last_Name___Local,omitempty"`
    FirstName2Local *string `xml:"First_Name_2___Local,omitempty"`
    LastName2Local *string `xml:"Last_Name_2___Local,omitempty"`
}

type PreferredName struct {
    DeletePreferredNameData *bool `xml:"Delete_Preferred_Name_Data,omitempty"`
    NameDetailData *NameDetailData `xml:"Name_Detail_Data,omitempty"`
}

type ContactData struct {
    PhoneDeviceTypeReference *PhoneDeviceTypeReference `xml:"Phone_Device_Type_Reference,omitempty"`
    CountryPhoneCodeReference *CountryPhoneCodeReference `xml:"Country_Phone_Code_Reference,omitempty"`
    PhoneNumber *string `xml:"Phone_Number,omitempty"`
    PhoneExtension *string `xml:"Phone_Extension,omitempty"`
    EmailAddress *string `xml:"Email_Address,omitempty"`
    WebsiteData *WebsiteData `xml:"Website_Data,omitempty"`
    LocationData *LocationData `xml:"Location_Data,omitempty"`
}

type PhoneDeviceTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CountryPhoneCodeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WebsiteData struct {
    UrlAddress *string `xml:"URL_Address,omitempty"`
}

type LocationData struct {
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    AddressLine1 *string `xml:"Address_Line_1,omitempty"`
    AddressLine2 *string `xml:"Address_Line_2,omitempty"`
    AddressLine3 *string `xml:"Address_Line_3,omitempty"`
    AddressLine4 *string `xml:"Address_Line_4,omitempty"`
    AddressLine5 *string `xml:"Address_Line_5,omitempty"`
    AddressLine6 *string `xml:"Address_Line_6,omitempty"`
    AddressLine7 *string `xml:"Address_Line_7,omitempty"`
    AddressLine8 *string `xml:"Address_Line_8,omitempty"`
    AddressLine9 *string `xml:"Address_Line_9,omitempty"`
    AddressLine1Local *string `xml:"Address_Line_1___Local,omitempty"`
    AddressLine2Local *string `xml:"Address_Line_2___Local,omitempty"`
    AddressLine3Local *string `xml:"Address_Line_3___Local,omitempty"`
    AddressLine4Local *string `xml:"Address_Line_4___Local,omitempty"`
    AddressLine5Local *string `xml:"Address_Line_5___Local,omitempty"`
    AddressLine6Local *string `xml:"Address_Line_6___Local,omitempty"`
    AddressLine7Local *string `xml:"Address_Line_7___Local,omitempty"`
    AddressLine8Local *string `xml:"Address_Line_8___Local,omitempty"`
    AddressLine9Local *string `xml:"Address_Line_9___Local,omitempty"`
    City *string `xml:"City,omitempty"`
    CityLocal *string `xml:"City___Local,omitempty"`
    CitySubdivision1 *string `xml:"City_Subdivision_1,omitempty"`
    CitySubdivision2 *string `xml:"City_Subdivision_2,omitempty"`
    CitySubdivision1Local *string `xml:"City_Subdivision_1___Local,omitempty"`
    CitySubdivision2Local *string `xml:"City_Subdivision_2___Local,omitempty"`
    CountryCityReference *CountryCityReference `xml:"Country_City_Reference,omitempty"`
    CountryRegionReference *CountryRegionReference `xml:"Country_Region_Reference,omitempty"`
    RegionSubdivision1 *string `xml:"Region_Subdivision_1,omitempty"`
    RegionSubdivision2 *string `xml:"Region_Subdivision_2,omitempty"`
    RegionSubdivision1Local *string `xml:"Region_Subdivision_1___Local,omitempty"`
    RegionSubdivision2Local *string `xml:"Region_Subdivision_2___Local,omitempty"`
    PostalCode *string `xml:"Postal_Code,omitempty"`
}

type CountryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CountryCityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CountryRegionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SocialMediaAccountData struct {
    SocialNetworkTypeReference *SocialNetworkTypeReference `xml:"Social_Network_Type_Reference,omitempty"`
    SocialNetworkAccountUrl *string `xml:"Social_Network_Account_URL,omitempty"`
    SocialNetworkAccountUserName *string `xml:"Social_Network_Account_User_Name,omitempty"`
}

type SocialNetworkTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type StatusData struct {
    DoNotHire *bool `xml:"Do_Not_Hire,omitempty"`
    Withdrawn *bool `xml:"Withdrawn,omitempty"`
}

type JobApplicationData struct {
    JobApplicationReference *JobApplicationReference `xml:"Job_Application_Reference,omitempty"`
    JobAppliedToData *JobAppliedToData `xml:"Job_Applied_To_Data,omitempty"`
    ResumeAttachmentData *ResumeAttachmentData `xml:"Resume_Attachment_Data,omitempty"`
    ResumeData *ResumeData `xml:"Resume_Data,omitempty"`
}

type JobApplicationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type JobAppliedToData struct {
    JobApplicationId *string `xml:"Job_Application_ID,omitempty"`
    JobRequisitionReference *JobRequisitionReference `xml:"Job_Requisition_Reference,omitempty"`
    JobApplicationDate *string `xml:"Job_Application_Date,omitempty"`
    StageReference *StageReference `xml:"Stage_Reference,omitempty"`
    WorkflowStepReference *WorkflowStepReference `xml:"Workflow_Step_Reference,omitempty"`
    DispositionReference *DispositionReference `xml:"Disposition_Reference,omitempty"`
    StatusTimestamp *string `xml:"Status_Timestamp,omitempty"`
    SourceReference *SourceReference `xml:"Source_Reference,omitempty"`
    ReferredByWorkerReference *ReferredByWorkerReference `xml:"Referred_By_Worker_Reference,omitempty"`
    AddedByWorkerReference *AddedByWorkerReference `xml:"Added_By_Worker_Reference,omitempty"`
    CriteriaMatchScoreReference *CriteriaMatchScoreReference `xml:"Criteria_Match_Score_Reference,omitempty"`
    JobApplicationAvailabilityData *JobApplicationAvailabilityData `xml:"Job_Application_Availability_Data,omitempty"`
    PersonalInformationData *PersonalInformationData `xml:"Personal_Information_Data,omitempty"`
    GlobalPersonalInformationData *GlobalPersonalInformationData `xml:"Global_Personal_Information_Data,omitempty"`
}

type StageReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WorkflowStepReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DispositionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SourceReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ReferredByWorkerReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AddedByWorkerReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CriteriaMatchScoreReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type JobApplicationAvailabilityData struct {
    CandidateAvailabilityTemplateVersionReference *CandidateAvailabilityTemplateVersionReference `xml:"Candidate_Availability_Template_Version_Reference,omitempty"`
    Flexible *bool `xml:"Flexible,omitempty"`
    NoneWorkForMe *bool `xml:"None_Work_for_Me,omitempty"`
    AvailabilityNotes *string `xml:"Availability_Notes,omitempty"`
    MondayAvailabilityReference *MondayAvailabilityReference `xml:"Monday_Availability_Reference,omitempty"`
    TuesdayAvailabilityReference *TuesdayAvailabilityReference `xml:"Tuesday_Availability_Reference,omitempty"`
    WednesdayAvailabilityReference *WednesdayAvailabilityReference `xml:"Wednesday_Availability_Reference,omitempty"`
    ThursdayAvailabilityReference *ThursdayAvailabilityReference `xml:"Thursday_Availability_Reference,omitempty"`
    FridayAvailabilityReference *FridayAvailabilityReference `xml:"Friday_Availability_Reference,omitempty"`
    SaturdayAvailabilityReference *SaturdayAvailabilityReference `xml:"Saturday_Availability_Reference,omitempty"`
    SundayAvailabilityReference *SundayAvailabilityReference `xml:"Sunday_Availability_Reference,omitempty"`
}

type CandidateAvailabilityTemplateVersionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MondayAvailabilityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type TuesdayAvailabilityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type WednesdayAvailabilityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ThursdayAvailabilityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type FridayAvailabilityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SaturdayAvailabilityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SundayAvailabilityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PersonalInformationData struct {
    GenderReference *GenderReference `xml:"Gender_Reference,omitempty"`
    EthnicityReference *EthnicityReference `xml:"Ethnicity_Reference,omitempty"`
    VeteransStatusReference *VeteransStatusReference `xml:"Veterans_Status_Reference,omitempty"`
    HispanicOrLatino *bool `xml:"Hispanic_or_Latino,omitempty"`
    DisabilityStatusReference *DisabilityStatusReference `xml:"Disability_Status_Reference,omitempty"`
    DisabilityStatusLastUpdatedOn *string `xml:"Disability_Status_Last_Updated_On,omitempty"`
    VeteransPreferenceReference *VeteransPreferenceReference `xml:"Veterans_Preference_Reference,omitempty"`
    AdjudicationInfoData *AdjudicationInfoData `xml:"Adjudication_Info_Data,omitempty"`
    VeteransPreferenceAttachmentData *VeteransPreferenceAttachmentData `xml:"Veterans_Preference_Attachment_Data,omitempty"`
}

type GenderReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EthnicityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type VeteransStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DisabilityStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type VeteransPreferenceReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AdjudicationInfoData struct {
    AdjudicationStatusReference *AdjudicationStatusReference `xml:"Adjudication_Status_Reference,omitempty"`
}

type AdjudicationStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type VeteransPreferenceAttachmentData struct {
    Id *string `xml:"ID,omitempty"`
    Filename *string `xml:"Filename,omitempty"`
    FileContent *string `xml:"File_Content,omitempty"`
    MimeTypeReference *MimeTypeReference `xml:"Mime_Type_Reference,omitempty"`
    Comment *string `xml:"Comment,omitempty"`
}

type MimeTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type GlobalPersonalInformationData struct {
    GenderReference *GenderReference `xml:"Gender_Reference,omitempty"`
    DateOfBirth *string `xml:"Date_of_Birth,omitempty"`
    BirthCountryReference *BirthCountryReference `xml:"Birth_Country_Reference,omitempty"`
    BirthRegionReference *BirthRegionReference `xml:"Birth_Region_Reference,omitempty"`
    CityOfBirth *string `xml:"City_of_Birth,omitempty"`
    MaritalStatusReference *MaritalStatusReference `xml:"Marital_Status_Reference,omitempty"`
    HispanicOrLatino *bool `xml:"Hispanic_or_Latino,omitempty"`
    AboriginalIndigenousIdentificationReference *AboriginalIndigenousIdentificationReference `xml:"Aboriginal_Indigenous_Identification_Reference,omitempty"`
    AboriginalIndigenousIdentificationDetailsReference *AboriginalIndigenousIdentificationDetailsReference `xml:"Aboriginal_Indigenous_Identification_Details_Reference,omitempty"`
    EthnicityReference *EthnicityReference `xml:"Ethnicity_Reference,omitempty"`
    ReligionReference *ReligionReference `xml:"Religion_Reference,omitempty"`
    CitizenshipReference *CitizenshipReference `xml:"Citizenship_Reference,omitempty"`
    NationalityReference *NationalityReference `xml:"Nationality_Reference,omitempty"`
    AdditionalNationalityReference *AdditionalNationalityReference `xml:"Additional_Nationality_Reference,omitempty"`
    SocialBenefitsLocalityReference *SocialBenefitsLocalityReference `xml:"Social_Benefits_Locality_Reference,omitempty"`
    LgbtIdentificationReference *LgbtIdentificationReference `xml:"LGBT_Identification_Reference,omitempty"`
    SexualOrientationReference *SexualOrientationReference `xml:"Sexual_Orientation_Reference,omitempty"`
    GenderIdentityReference *GenderIdentityReference `xml:"Gender_Identity_Reference,omitempty"`
    PronounReference *PronounReference `xml:"Pronoun_Reference,omitempty"`
    DisabilityStatusData *DisabilityStatusData `xml:"Disability_Status_Data,omitempty"`
    MilitaryServiceInformationData *MilitaryServiceInformationData `xml:"Military_Service_Information_Data,omitempty"`
}

type BirthCountryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type BirthRegionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MaritalStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AboriginalIndigenousIdentificationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AboriginalIndigenousIdentificationDetailsReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ReligionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CitizenshipReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type NationalityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AdditionalNationalityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SocialBenefitsLocalityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LgbtIdentificationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SexualOrientationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type GenderIdentityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PronounReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DisabilityStatusData struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    DisabilityStatusReference *DisabilityStatusReference `xml:"Disability_Status_Reference,omitempty"`
    DisabilityReference *DisabilityReference `xml:"Disability_Reference,omitempty"`
    DisabilityStatusDate *string `xml:"Disability_Status_Date,omitempty"`
}

type DisabilityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryServiceInformationData struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    MilitaryServiceReference *MilitaryServiceReference `xml:"Military_Service_Reference,omitempty"`
    MilitaryServiceData *MilitaryServiceData `xml:"Military_Service_Data,omitempty"`
}

type MilitaryServiceReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryServiceData struct {
    MilitaryStatusReference *MilitaryStatusReference `xml:"Military_Status_Reference,omitempty"`
    MilitaryDischargeDate *string `xml:"Military_Discharge_Date,omitempty"`
    MilitaryStatusBeginDate *string `xml:"Military_Status_Begin_Date,omitempty"`
    MilitaryServiceTypeReference *MilitaryServiceTypeReference `xml:"Military_Service_Type_Reference,omitempty"`
    MilitaryRankReference *MilitaryRankReference `xml:"Military_Rank_Reference,omitempty"`
    Notes *string `xml:"Notes,omitempty"`
    MilitaryDischargeTypeReference *MilitaryDischargeTypeReference `xml:"Military_Discharge_Type_Reference,omitempty"`
}

type MilitaryStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryServiceTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryRankReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type MilitaryDischargeTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ResumeAttachmentData struct {
    Id *string `xml:"ID,omitempty"`
    Filename *string `xml:"Filename,omitempty"`
    FileContent *string `xml:"File_Content,omitempty"`
    MimeTypeReference *MimeTypeReference `xml:"Mime_Type_Reference,omitempty"`
    Comment *string `xml:"Comment,omitempty"`
}

type ResumeData struct {
    Summary *string `xml:"Summary,omitempty"`
    SkillData *SkillData `xml:"Skill_Data,omitempty"`
    ExperienceData *ExperienceData `xml:"Experience_Data,omitempty"`
    EducationData *EducationData `xml:"Education_Data,omitempty"`
    CertificationData *CertificationData `xml:"Certification_Data,omitempty"`
    LanguageData *LanguageData `xml:"Language_Data,omitempty"`
    QuestionnaireResponseData *QuestionnaireResponseData `xml:"Questionnaire_Response_Data,omitempty"`
}

type SkillData struct {
    SkillReference *SkillReference `xml:"Skill_Reference,omitempty"`
    SkillName *string `xml:"Skill_Name,omitempty"`
}

type SkillReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ExperienceData struct {
    CompanyReference *CompanyReference `xml:"Company_Reference,omitempty"`
    CompanyName *string `xml:"Company_Name,omitempty"`
    Title *string `xml:"Title,omitempty"`
    Location *string `xml:"Location,omitempty"`
    StartMonth *int `xml:"Start_Month,omitempty"`
    StartYear *int `xml:"Start_Year,omitempty"`
    EndMonth *int `xml:"End_Month,omitempty"`
    EndYear *int `xml:"End_Year,omitempty"`
    CurrentlyWorkHere *bool `xml:"Currently_Work_Here,omitempty"`
    Description *string `xml:"Description,omitempty"`
}

type CompanyReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type EducationData struct {
    SchoolReference *SchoolReference `xml:"School_Reference,omitempty"`
    SchoolName *string `xml:"School_Name,omitempty"`
    FirstYearAttended *int `xml:"First_Year_Attended,omitempty"`
    LastYearAttended *int `xml:"Last_Year_Attended,omitempty"`
    DegreeReference *DegreeReference `xml:"Degree_Reference,omitempty"`
    FieldOfStudyReference *FieldOfStudyReference `xml:"Field_of_Study_Reference,omitempty"`
    GradeAverage *string `xml:"Grade_Average,omitempty"`
}

type SchoolReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DegreeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type FieldOfStudyReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CertificationData struct {
    CertificationSkillReference *CertificationSkillReference `xml:"Certification_Skill_Reference,omitempty"`
    CertificationDataDetails *CertificationDataDetails `xml:"Certification_Data_Details,omitempty"`
}

type CertificationSkillReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CertificationDataDetails struct {
    CertificationId *string `xml:"Certification_ID,omitempty"`
    RemoveCertification *bool `xml:"Remove_Certification,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    CertificationReference *CertificationReference `xml:"Certification_Reference,omitempty"`
    CertificationNumber *string `xml:"Certification_Number,omitempty"`
    ExamDate *string `xml:"Exam_Date,omitempty"`
    ExamScore *string `xml:"Exam_Score,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    SpecialtyDataDetails *SpecialtyDataDetails `xml:"Specialty_Data_Details,omitempty"`
    AttachmentData *AttachmentData `xml:"Attachment_Data,omitempty"`
}

type CertificationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SpecialtyDataDetails struct {
    SpecialtyReference *SpecialtyReference `xml:"Specialty_Reference,omitempty"`
    SpecialtyStartDate *string `xml:"Specialty_Start_Date,omitempty"`
    SpecialtyEndDate *string `xml:"Specialty_End_Date,omitempty"`
    SubspecialtyReference *SubspecialtyReference `xml:"Subspecialty_Reference,omitempty"`
}

type SpecialtyReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SubspecialtyReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AttachmentData struct {
    Id *string `xml:"ID,omitempty"`
    Filename *string `xml:"Filename,omitempty"`
    FileContent *string `xml:"File_Content,omitempty"`
    MimeTypeReference *MimeTypeReference `xml:"Mime_Type_Reference,omitempty"`
    Comment *string `xml:"Comment,omitempty"`
}

type LanguageData struct {
    LanguageReference *LanguageReference `xml:"Language_Reference,omitempty"`
    Language *Language `xml:"Language,omitempty"`
}

type LanguageReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Language struct {
    Native *bool `xml:"Native,omitempty"`
    LanguageAbility *LanguageAbility `xml:"Language_Ability,omitempty"`
}

type LanguageAbility struct {
    LanguageAbilityData *LanguageAbilityData `xml:"Language_Ability_Data,omitempty"`
}

type LanguageAbilityData struct {
    LanguageProficiencyReference *LanguageProficiencyReference `xml:"Language_Proficiency_Reference,omitempty"`
    LanguageAbilityTypeReference *LanguageAbilityTypeReference `xml:"Language_Ability_Type_Reference,omitempty"`
}

type LanguageProficiencyReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LanguageAbilityTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type QuestionnaireResponseData struct {
    ResponseData *ResponseData `xml:"Response_Data,omitempty"`
}

type QuestionnaireReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type QuestionnaireAnswerData struct {
    QuestionOrder *string `xml:"Question_Order,omitempty"`
    MultipleChoiceAnswerData *MultipleChoiceAnswerData `xml:"Multiple_Choice_Answer_Data,omitempty"`
    AnswerDate *string `xml:"Answer_Date,omitempty"`
    AnswerNumeric *int `xml:"Answer_Numeric,omitempty"`
    AnswerText *string `xml:"Answer_Text,omitempty"`
    AttachmentAnswerData *AttachmentAnswerData `xml:"Attachment_Answer_Data,omitempty"`
}

type MultipleChoiceAnswerData struct {
    MultipleChoiceAnswerReference *MultipleChoiceAnswerReference `xml:"Multiple_Choice_Answer_Reference,omitempty"`
    MultipleChoiceAnswerText *string `xml:"Multiple_Choice_Answer_Text,omitempty"`
}

type MultipleChoiceAnswerReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AttachmentAnswerData struct {
    AnswerAttachment *AnswerAttachment `xml:"Answer_Attachment,omitempty"`
}

type AnswerAttachment struct {
    Id *string `xml:"ID,omitempty"`
    Filename *string `xml:"Filename,omitempty"`
    FileContent *string `xml:"File_Content,omitempty"`
    MimeTypeReference *MimeTypeReference `xml:"Mime_Type_Reference,omitempty"`
    Comment *string `xml:"Comment,omitempty"`
}

type ProspectData struct {
    Prospect *bool `xml:"Prospect,omitempty"`
    Confidential *bool `xml:"Confidential,omitempty"`
    ReferralConsentGiven *bool `xml:"Referral_Consent_Given,omitempty"`
    LevelReference *LevelReference `xml:"Level_Reference,omitempty"`
    ProspectStatusReference *ProspectStatusReference `xml:"Prospect_Status_Reference,omitempty"`
    ProspectTypeReference *ProspectTypeReference `xml:"Prospect_Type_Reference,omitempty"`
    SourceReference *SourceReference `xml:"Source_Reference,omitempty"`
    ReferredByWorkerReference *ReferredByWorkerReference `xml:"Referred_By_Worker_Reference,omitempty"`
    ReferralJobReference *ReferralJobReference `xml:"Referral_Job_Reference,omitempty"`
    ReferralJobAreaReference *ReferralJobAreaReference `xml:"Referral_Job_Area_Reference,omitempty"`
    ReferralRelationshipReference *ReferralRelationshipReference `xml:"Referral_Relationship_Reference,omitempty"`
    ReferralComment *string `xml:"Referral_Comment,omitempty"`
    AddedByWorkerReference *AddedByWorkerReference `xml:"Added_By_Worker_Reference,omitempty"`
    ProspectAttachmentData *ProspectAttachmentData `xml:"Prospect_Attachment_Data,omitempty"`
    ResumeData *ResumeData `xml:"Resume_Data,omitempty"`
}

type LevelReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ProspectStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ProspectTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ReferralJobReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ReferralJobAreaReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ReferralRelationshipReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ProspectAttachmentData struct {
    ResumeAttachments *ResumeAttachments `xml:"Resume_Attachments,omitempty"`
}

type ResumeAttachments struct {
    Id *string `xml:"ID,omitempty"`
    Filename *string `xml:"Filename,omitempty"`
    FileContent *string `xml:"File_Content,omitempty"`
    MimeTypeReference *MimeTypeReference `xml:"Mime_Type_Reference,omitempty"`
    Comment *string `xml:"Comment,omitempty"`
}

type ReferralData struct {
    ReferralOwnershipDetailsData *ReferralOwnershipDetailsData `xml:"Referral_Ownership_Details_Data,omitempty"`
}

type ReferralOwnershipDetailsData struct {
    CandidateOwnerWorkerReference *CandidateOwnerWorkerReference `xml:"Candidate_Owner_Worker_Reference,omitempty"`
    OwnershipStartDate *string `xml:"Ownership_Start_Date,omitempty"`
    OwnershipEndDate *string `xml:"Ownership_End_Date,omitempty"`
}

type CandidateOwnerWorkerReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CandidateIdentificationData struct {
    NationalId *NationalId `xml:"National_ID,omitempty"`
    GovernmentId *GovernmentId `xml:"Government_ID,omitempty"`
}

type NationalId struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    NationalIdReference *NationalIdReference `xml:"National_ID_Reference,omitempty"`
    NationalIdData *NationalIdData `xml:"National_ID_Data,omitempty"`
    NationalIdSharedReference *NationalIdSharedReference `xml:"National_ID_Shared_Reference,omitempty"`
}

type NationalIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type NationalIdData struct {
    Id *string `xml:"ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
    Series *string `xml:"Series,omitempty"`
    IssuingAgency *string `xml:"Issuing_Agency,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"Verified_By_Reference,omitempty"`
}

type IdTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type VerifiedByReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type NationalIdSharedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type GovernmentId struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    GovernmentIdReference *GovernmentIdReference `xml:"Government_ID_Reference,omitempty"`
    GovernmentIdData *GovernmentIdData `xml:"Government_ID_Data,omitempty"`
    GovernmentIdSharedReference *GovernmentIdSharedReference `xml:"Government_ID_Shared_Reference,omitempty"`
}

type GovernmentIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type GovernmentIdData struct {
    Id *string `xml:"ID,omitempty"`
    IdTypeReference *IdTypeReference `xml:"ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    IssuedDate *string `xml:"Issued_Date,omitempty"`
    ExpirationDate *string `xml:"Expiration_Date,omitempty"`
    VerificationDate *string `xml:"Verification_Date,omitempty"`
    VerifiedByReference *VerifiedByReference `xml:"Verified_by_Reference,omitempty"`
}

type GovernmentIdSharedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CandidatePoolData struct {
    CandidatePoolMembershipData *CandidatePoolMembershipData `xml:"Candidate_Pool_Membership_Data,omitempty"`
}

type CandidatePoolMembershipData struct {
    StaticCandidatePoolReference *StaticCandidatePoolReference `xml:"Static_Candidate_Pool_Reference,omitempty"`
    ReadinessStatusReference *ReadinessStatusReference `xml:"Readiness_Status_Reference,omitempty"`
}

type ReadinessStatusReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CandidateAttachmentData struct {
    CandidateAttachmentReference *CandidateAttachmentReference `xml:"Candidate_Attachment_Reference,omitempty"`
    AttachmentData *AttachmentData `xml:"Attachment_Data,omitempty"`
    DocumentCategoryReference *DocumentCategoryReference `xml:"Document_Category_Reference,omitempty"`
}

type CandidateAttachmentReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DocumentCategoryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

