// Code generated by goxmlstruct. DO NOT EDIT.

package human_resources

type EmployeePersonalInfo struct {
	EmployeePersonalInfoData struct {
		ExternalIntegrationIDData struct {
			ID struct {
				SystemID string `xml:"System_ID,attr"`
				CharData string `xml:",chardata"`
			} `xml:"ID"`
		} `xml:"External_Integration_ID_Data"`
		PersonalInfoData struct {
			BusinessTitle string `xml:"Business_Title"`
			PersonData    struct {
				BiographicData struct {
					CountryOfBirthReference struct {
						CountryReference struct {
							CountryISOCode string `xml:"Country_ISO_Code"`
						} `xml:"Country_Reference"`
					} `xml:"Country_Of_Birth_Reference"`
					DateOfBirth         string `xml:"Date_Of_Birth"`
					DisabilityReference struct {
						DisabilityName                        string `xml:"Disability_Name"`
						RegulatoryRegionOrganizationReference struct {
							IntegrationIDReference struct {
								Descriptor string `xml:"Descriptor,attr"`
								ID         struct {
									SystemID string `xml:"System_ID,attr"`
									CharData string `xml:",chardata"`
								} `xml:"ID"`
							} `xml:"Integration_ID_Reference"`
						} `xml:"Regulatory_Region_Organization_Reference"`
					} `xml:"Disability_Reference"`
					GenderReference struct {
						GenderDescription string `xml:"Gender_Description"`
					} `xml:"Gender_Reference"`
					PlaceOfBirth string `xml:"Place_Of_Birth"`
					UsesTobacco  bool   `xml:"Uses_Tobacco"`
				} `xml:"Biographic_Data"`
				ContactData struct {
					AddressData struct {
						EffectiveDate string `xml:"Effective_Date,attr"`
						LastModified  string `xml:"Last_Modified,attr"`
						AddressLine   struct {
							Descriptor string `xml:"Descriptor,attr"`
							Type       string `xml:"Type,attr"`
							CharData   string `xml:",chardata"`
						} `xml:"Address_Line"`
						CountryReference struct {
							CountryISOCode string `xml:"Country_ISO_Code"`
						} `xml:"Country_Reference"`
						Municipality    string `xml:"Municipality"`
						PostalCode      string `xml:"Postal_Code"`
						Region          string `xml:"Region"`
						Submunicipality string `xml:"Submunicipality"`
						Subregion       struct {
							Descriptor string `xml:"Descriptor,attr"`
							Type       string `xml:"Type,attr"`
							CharData   string `xml:",chardata"`
						} `xml:"Subregion"`
						UsageData struct {
							Public        bool   `xml:"Public,attr"`
							Comments      string `xml:"Comments"`
							TypeReference struct {
								Primary  bool   `xml:"Primary,attr"`
								CharData string `xml:",chardata"`
							} `xml:"Type_Reference"`
							UseForReference string `xml:"Use_For_Reference"`
						} `xml:"Usage_Data"`
					} `xml:"Address_Data"`
					InstantMessengerData struct {
						InstantMessengerAddress       string `xml:"Instant_Messenger_Address"`
						InstantMessengerComment       string `xml:"Instant_Messenger_Comment"`
						InstantMessengerTypeReference struct {
							InstantMessengerProvider string `xml:"Instant_Messenger_Provider"`
						} `xml:"Instant_Messenger_Type_Reference"`
						UsageData struct {
							Public        bool   `xml:"Public,attr"`
							Comments      string `xml:"Comments"`
							TypeReference struct {
								Primary  bool   `xml:"Primary,attr"`
								CharData string `xml:",chardata"`
							} `xml:"Type_Reference"`
							UseForReference string `xml:"Use_For_Reference"`
						} `xml:"Usage_Data"`
					} `xml:"Instant_Messenger_Data"`
					InternetEmailAddressData struct {
						EmailAddress string `xml:"Email_Address"`
						EmailComment string `xml:"Email_Comment"`
						UsageData    struct {
							Public        bool   `xml:"Public,attr"`
							Comments      string `xml:"Comments"`
							TypeReference struct {
								Primary  bool   `xml:"Primary,attr"`
								CharData string `xml:",chardata"`
							} `xml:"Type_Reference"`
							UseForReference string `xml:"Use_For_Reference"`
						} `xml:"Usage_Data"`
					} `xml:"Internet_Email_Address_Data"`
					PhoneNumberData struct {
						AreaCode                 string `xml:"Area_Code"`
						CountryISOCode           string `xml:"Country_ISO_Code"`
						InternationalPhoneCode   string `xml:"International_Phone_Code"`
						PhoneDeviceTypeReference struct {
							PhoneDeviceTypeDescription string `xml:"Phone_Device_Type_Description"`
						} `xml:"Phone_Device_Type_Reference"`
						PhoneExtension string `xml:"Phone_Extension"`
						PhoneNumber    string `xml:"Phone_Number"`
						UsageData      struct {
							Public        bool   `xml:"Public,attr"`
							Comments      string `xml:"Comments"`
							TypeReference struct {
								Primary  bool   `xml:"Primary,attr"`
								CharData string `xml:",chardata"`
							} `xml:"Type_Reference"`
							UseForReference string `xml:"Use_For_Reference"`
						} `xml:"Usage_Data"`
					} `xml:"Phone_Number_Data"`
					WebAddressData struct {
						UsageData struct {
							Public        bool   `xml:"Public,attr"`
							Comments      string `xml:"Comments"`
							TypeReference struct {
								Primary  bool   `xml:"Primary,attr"`
								CharData string `xml:",chardata"`
							} `xml:"Type_Reference"`
							UseForReference string `xml:"Use_For_Reference"`
						} `xml:"Usage_Data"`
						WebAddress        string `xml:"Web_Address"`
						WebAddressComment string `xml:"Web_Address_Comment"`
					} `xml:"Web_Address_Data"`
				} `xml:"Contact_Data"`
				CustomIDData struct {
					CustomDescription     string `xml:"Custom_Description"`
					CustomID              string `xml:"Custom_ID"`
					CustomIDTypeReference struct {
						CustomIDTypeName string `xml:"Custom_ID_Type_Name"`
					} `xml:"Custom_ID_Type_Reference"`
					ExpirationDate        string `xml:"Expiration_Date"`
					IssuedDate            string `xml:"Issued_Date"`
					OrganizationReference struct {
						IntegrationIDReference struct {
							Descriptor string `xml:"Descriptor,attr"`
							ID         struct {
								SystemID string `xml:"System_ID,attr"`
								CharData string `xml:",chardata"`
							} `xml:"ID"`
						} `xml:"Integration_ID_Reference"`
					} `xml:"Organization_Reference"`
				} `xml:"Custom_ID_Data"`
				DemographicData struct {
					CitizenshipStatusReference struct {
						CitizenshipStatusDescription string `xml:"Citizenship_Status_Description"`
						CountryReference             struct {
							CountryISOCode string `xml:"Country_ISO_Code"`
						} `xml:"Country_Reference"`
					} `xml:"Citizenship_Status_Reference"`
					EthnicityReference struct {
						EthnicityName                         string `xml:"Ethnicity_Name"`
						RegulatoryRegionOrganizationReference struct {
							IntegrationIDReference struct {
								Descriptor string `xml:"Descriptor,attr"`
								ID         struct {
									SystemID string `xml:"System_ID,attr"`
									CharData string `xml:",chardata"`
								} `xml:"ID"`
							} `xml:"Integration_ID_Reference"`
						} `xml:"Regulatory_Region_Organization_Reference"`
					} `xml:"Ethnicity_Reference"`
					HispanicOrLatino     bool   `xml:"Hispanic_or_Latino"`
					HukouLocality        string `xml:"Hukou_Locality"`
					HukouPostalCode      string `xml:"Hukou_Postal_Code"`
					HukouRegionReference struct {
						Descriptor string `xml:"Descriptor,attr"`
						ID         struct {
							Type     string `xml:"type,attr"`
							CharData string `xml:",chardata"`
						} `xml:"ID"`
					} `xml:"Hukou_Region_Reference"`
					HukouSubregionReference struct {
						Descriptor string `xml:"Descriptor,attr"`
						ID         struct {
							Type     string `xml:"type,attr"`
							CharData string `xml:",chardata"`
						} `xml:"ID"`
					} `xml:"Hukou_Subregion_Reference"`
					HukouTypeReference struct {
						Descriptor string `xml:"Descriptor,attr"`
						ID         struct {
							Type     string `xml:"type,attr"`
							CharData string `xml:",chardata"`
						} `xml:"ID"`
					} `xml:"Hukou_Type_Reference"`
					MaritalStatusReference struct {
						MaritalStatusDescription string `xml:"Marital_Status_Description"`
					} `xml:"Marital_Status_Reference"`
					MilitaryServiceData struct {
						MilitaryDischargeDate   string `xml:"Military_Discharge_Date"`
						MilitaryStatusReference struct {
							CountryReference struct {
								CountryISOCode string `xml:"Country_ISO_Code"`
							} `xml:"Country_Reference"`
							MilitaryStatusName string `xml:"Military_Status_Name"`
						} `xml:"Military_Status_Reference"`
					} `xml:"Military_Service_Data"`
					NationalityReference struct {
						Descriptor string `xml:"Descriptor,attr"`
						ID         struct {
							Type     string `xml:"type,attr"`
							CharData string `xml:",chardata"`
						} `xml:"ID"`
					} `xml:"Nationality_Reference"`
					NativeRegionReference struct {
						Descriptor string `xml:"Descriptor,attr"`
						ID         struct {
							Type     string `xml:"type,attr"`
							CharData string `xml:",chardata"`
						} `xml:"ID"`
					} `xml:"Native_Region_Reference"`
					PersonnelFileAgency string `xml:"Personnel_File_Agency"`
				} `xml:"Demographic_Data"`
				GovernmentIDData struct {
					CountryReference struct {
						CountryISOCode string `xml:"Country_ISO_Code"`
					} `xml:"Country_Reference"`
					ExpirationDate            string `xml:"Expiration_Date"`
					GovernmentID              string `xml:"Government_ID"`
					GovernmentIDTypeReference struct {
						GovernmentIDTypeName string `xml:"Government_ID_Type_Name"`
					} `xml:"Government_ID_Type_Reference"`
					IssuedDate       string `xml:"Issued_Date"`
					VerificationDate string `xml:"Verification_Date"`
				} `xml:"Government_ID_Data"`
				LicenseIDData struct {
					AuthorityReference struct {
						AuthorityName                         string `xml:"Authority_Name"`
						RegulatoryRegionOrganizationReference struct {
							IntegrationIDReference struct {
								Descriptor string `xml:"Descriptor,attr"`
								ID         struct {
									SystemID string `xml:"System_ID,attr"`
									CharData string `xml:",chardata"`
								} `xml:"ID"`
							} `xml:"Integration_ID_Reference"`
						} `xml:"Regulatory_Region_Organization_Reference"`
					} `xml:"Authority_Reference"`
					CountryReference struct {
						CountryISOCode string `xml:"Country_ISO_Code"`
					} `xml:"Country_Reference"`
					CountryRegionReference struct {
						CountryReference struct {
							CountryISOCode string `xml:"Country_ISO_Code"`
						} `xml:"Country_Reference"`
						CountryRegionName string `xml:"Country_Region_Name"`
					} `xml:"Country_Region_Reference"`
					ExpirationDate       string `xml:"Expiration_Date"`
					IssuedDate           string `xml:"Issued_Date"`
					LicenseClass         string `xml:"License_Class"`
					LicenseID            string `xml:"License_ID"`
					LicenseTypeReference struct {
						LicenseTypeName string `xml:"License_Type_Name"`
					} `xml:"License_Type_Reference"`
					VerificationDate string `xml:"Verification_Date"`
				} `xml:"License_ID_Data"`
				NameData struct {
					EffectiveDate      string `xml:"Effective_Date,attr"`
					IsLegal            bool   `xml:"Is_Legal,attr"`
					IsPreferred        bool   `xml:"Is_Preferred,attr"`
					LastModified       string `xml:"Last_Modified,attr"`
					AdditionalNameType string `xml:"Additional_Name_Type"`
					CountryReference   struct {
						CountryISOCode string `xml:"Country_ISO_Code"`
					} `xml:"Country_Reference"`
					FirstName string `xml:"First_Name"`
					LastName  struct {
						Type     string `xml:"Type,attr"`
						CharData string `xml:",chardata"`
					} `xml:"Last_Name"`
					LocalNameData struct {
						LocalName   string `xml:"Local_Name,attr"`
						LocalScript string `xml:"Local_Script,attr"`
						FirstName   string `xml:"First_Name"`
						LastName    struct {
							Type     string `xml:"Type,attr"`
							CharData string `xml:",chardata"`
						} `xml:"Last_Name"`
						MiddleName string `xml:"Middle_Name"`
					} `xml:"Local_Name_Data"`
					MiddleName string `xml:"Middle_Name"`
					Prefix     struct {
						Type     string `xml:"Type,attr"`
						CharData string `xml:",chardata"`
					} `xml:"Prefix"`
					Suffix struct {
						Type     string `xml:"Type,attr"`
						CharData string `xml:",chardata"`
					} `xml:"Suffix"`
				} `xml:"Name_Data"`
				PassportIDData struct {
					CountryReference struct {
						CountryISOCode string `xml:"Country_ISO_Code"`
					} `xml:"Country_Reference"`
					ExpirationDate        string `xml:"Expiration_Date"`
					IssuedDate            string `xml:"Issued_Date"`
					PassportNumber        string `xml:"Passport_Number"`
					PassportTypeReference struct {
						PassportTypeName string `xml:"Passport_Type_Name"`
					} `xml:"Passport_Type_Reference"`
					VerificationDate string `xml:"Verification_Date"`
				} `xml:"Passport_ID_Data"`
				PersonalPreferencesData struct {
					ReceiveEmailNotifications bool `xml:"Receive_Email_Notifications"`
				} `xml:"Personal_Preferences_Data"`
				VisaIDData struct {
					CountryReference struct {
						CountryISOCode string `xml:"Country_ISO_Code"`
					} `xml:"Country_Reference"`
					ExpirationDate    string `xml:"Expiration_Date"`
					IssuedDate        string `xml:"Issued_Date"`
					VerificationDate  string `xml:"Verification_Date"`
					VisaID            string `xml:"Visa_ID"`
					VisaTypeReference struct {
						VisaTypeName string `xml:"Visa_Type_Name"`
					} `xml:"Visa_Type_Reference"`
				} `xml:"Visa_ID_Data"`
			} `xml:"Person_Data"`
			QualificationData struct {
				EducationData struct {
					CountryReference struct {
						Descriptor string `xml:"Descriptor,attr"`
						ID         struct {
							Type     string `xml:"type,attr"`
							CharData string `xml:",chardata"`
						} `xml:"ID"`
					} `xml:"Country_Reference"`
					DegreeCompletedReference struct {
						Descriptor string `xml:"Descriptor,attr"`
						ID         struct {
							Type     string `xml:"type,attr"`
							CharData string `xml:",chardata"`
						} `xml:"ID"`
					} `xml:"Degree_Completed_Reference"`
					DegreeReference struct {
						DegreeName string `xml:"Degree_Name"`
					} `xml:"Degree_Reference"`
					EducationGradeAverage               string `xml:"Education_Grade_Average"`
					EducationInstitution                string `xml:"Education_Institution"`
					EducationInstitutionLocation        string `xml:"Education_Institution_Location"`
					EducationalInstitutionTypeReference struct {
						InstitutionTypeName string `xml:"Institution_Type_Name"`
					} `xml:"Educational_Institution_Type_Reference"`
					FieldOfStudyReference struct {
						FieldOfStudyName string `xml:"Field_Of_Study_Name"`
					} `xml:"Field_Of_Study_Reference"`
					FirstYearAttended string `xml:"First_Year_Attended"`
					LastYearAttended  string `xml:"Last_Year_Attended"`
					SchoolReference   struct {
						Descriptor string `xml:"Descriptor,attr"`
						ID         struct {
							Type     string `xml:"type,attr"`
							CharData string `xml:",chardata"`
						} `xml:"ID"`
					} `xml:"School_Reference"`
				} `xml:"Education_Data"`
				ProfessionalExperienceData struct {
					ProfessionalExperience                string `xml:"Professional_Experience"`
					ProfessionalExperienceComment         string `xml:"Professional_Experience_Comment"`
					ProfessionalExperienceRatingReference struct {
						RatingDescription string `xml:"Rating_Description"`
					} `xml:"Professional_Experience_Rating_Reference"`
				} `xml:"Professional_Experience_Data"`
			} `xml:"Qualification_Data"`
		} `xml:"Personal_Info_Data"`
	} `xml:"Employee_Personal_Info_Data"`
	EmployeeReference struct {
		IntegrationIDReference struct {
			Descriptor string `xml:"Descriptor,attr"`
			ID         struct {
				SystemID string `xml:"System_ID,attr"`
				CharData string `xml:",chardata"`
			} `xml:"ID"`
		} `xml:"Integration_ID_Reference"`
	} `xml:"Employee_Reference"`
}

type EmployeePersonalInfoGet struct {
	EmployeeReference struct {
		IntegrationIDReference struct {
			Descriptor string `xml:"Descriptor,attr"`
			ID         struct {
				SystemID string `xml:"System_ID,attr"`
				CharData string `xml:",chardata"`
			} `xml:"ID"`
		} `xml:"Integration_ID_Reference"`
	} `xml:"Employee_Reference"`
}
