import sys
import glob
from xml.etree import ElementTree as ET
from collections import OrderedDict

def go_name(s: str):
    no_namespace = s.split('}')[-1] if '}' in s else s
    no_namespace = no_namespace.replace('-', '_')
    parts = no_namespace.split('_')
    go_field = ''.join(part.capitalize() for part in parts)
    # Check if the go_field starts with an unallowed golang variable character
    if go_field and not go_field[0].isalpha():
        go_field = '_' + go_field
    return go_field, no_namespace

def parse_element(elem: ET.Element, namespace: str, structs: dict, is_root: bool=False):
    go_field, xml_name = go_name(elem.tag)
    namespace_prefix = namespace + ':' if namespace else ''

    if structs.get(go_field):
        fields = structs[go_field]
    else:
        fields = dict[str, list[tuple[str, str]]]()
        structs[go_field] = fields

    if is_root:
        fields['XMLName'] = ('xml.Name', f'xml:"{namespace_prefix}{xml_name}"')
        if namespace:
            fields['XMLNamespace'] = ('*string', f'xml:"xmlns:{namespace},attr,omitempty"')

    for _, (name, _) in enumerate(elem.attrib.items()):
        go_field, xml_name = go_name(name)
        fields[go_field] = ('*string', f'xml:"{namespace_prefix}{xml_name},attr,omitempty"')

    if len(elem) == 0:
        # Leaf node, add value field
        hint = elem.text.strip().lower() if elem.text else ''
        if hint == 'string':
            fields['Value'] = ('*string', f'xml:",chardata"')
        elif hint in ['true', 'false']:
            fields['Value'] = ('*bool', f'xml:",chardata"')
        elif hint.replace('-', '').replace('.', '').isdigit():
            fields['Value'] = ('*int', f'xml:",chardata"')
        else:
            fields['Value'] = ('*string', f'xml:",chardata"')
        return

    for child in elem:
        go_field, xml_name = go_name(child.tag)

        # If the child has attributes or children, it's a struct; else, we're at a leaf
        if len(child) == 0 and len(child.attrib) == 0:
            hint = child.text.strip().lower() if child.text else ''
            if hint == 'string':
                fields[go_field] = ('*string', f'xml:"{namespace_prefix}{xml_name},omitempty"')
            elif hint in ['true', 'false']:
                fields[go_field] = ('*bool', f'xml:"{namespace_prefix}{xml_name},omitempty"')
            elif hint.replace('.', '').isdigit():
                fields[go_field] = ('*int', f'xml:"{namespace_prefix}{xml_name},omitempty"')
            else:
                fields[go_field] = ('*string', f'xml:"{namespace_prefix}{xml_name},omitempty"')
            continue

        fields[go_field] = (f'*{go_field}', f'xml:"{namespace_prefix}{xml_name},omitempty"')
        parse_element(child, namespace, structs, False)

def gen_struct(name, fields):
    lines = []
    lines.append(f'type {name} struct ' + '{')
    for go_field, (go_type, xml_tag) in fields.items():
        lines.append(f'    {go_field} {go_type} `{xml_tag}`')
    lines.append('}')
    return lines

def write_file(filename, package, structs):
    # Create the file and its directories if they don't exist
    import os
    os.makedirs(os.path.dirname(filename), exist_ok=True)

    with open(filename, 'w') as f:
        f.write(f'// Programmatically generated by gen_structs.py\n')
        f.write(f'package {package}\n\n')
        f.write('import "encoding/xml"\n\n')
        for _, (name, fields) in enumerate(structs.items()):
            for line in gen_struct(name, fields):
                f.write(line + '\n')
            f.write('\n')

def main(xml_path, namespace):
    files = glob.glob(xml_path)
    for file in files:
        tree = ET.parse(file)
        structs = OrderedDict()
        parse_element(tree.getroot(), namespace, structs, True)
        _, package_name = go_name(tree.getroot().tag)
        package_name = package_name.lower()
        file_name = f'../model/{package_name}/{package_name}.go'
        write_file(file_name, package_name, structs)

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("Usage: python generate_go_structs.py <xml_file_glob> <namespace>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])