// Code generated by zek 0.1.28; DO NOT EDIT.
package human_resources

import "encoding/xml"

// GetWorkersRequest was generated 2026-01-16 16:17:30 by blocke on Bens-MacBook-Pro.local with zek 0.1.28.
type GetWorkersRequest struct {
	XMLName           xml.Name `xml:"Get_Workers_Request"`
	Text              string   `xml:",chardata"`
	Version           string   `xml:"version,attr"`
	Bsvc              string   `xml:"bsvc,attr"`
	RequestReferences struct {
		Text                     string `xml:",chardata"`
		SkipNonExistingInstances string `xml:"Skip_Non_Existing_Instances,attr"`
		IgnoreInvalidReferences  string `xml:"Ignore_Invalid_References,attr"`
		WorkerReference          struct {
			Text       string `xml:",chardata"`
			Descriptor string `xml:"Descriptor,attr"`
			ID         struct {
				Text string `xml:",chardata"`
				Type string `xml:"type,attr"`
			} `xml:"ID"`
		} `xml:"Worker_Reference"`
	} `xml:"Request_References"`
	RequestCriteria struct {
		Text                       string `xml:",chardata"`
		TransactionLogCriteriaData struct {
			Text                     string `xml:",chardata"`
			TransactionDateRangeData struct {
				Text        string `xml:",chardata"`
				UpdatedFrom struct {
					Text string `xml:",chardata"`
				} `xml:"Updated_From"`
				UpdatedThrough struct {
					Text string `xml:",chardata"`
				} `xml:"Updated_Through"`
				EffectiveFrom struct {
					Text string `xml:",chardata"`
				} `xml:"Effective_From"`
				EffectiveThrough struct {
					Text string `xml:",chardata"`
				} `xml:"Effective_Through"`
			} `xml:"Transaction_Date_Range_Data"`
			TransactionTypeReferences struct {
				Text                     string `xml:",chardata"`
				TransactionTypeReference struct {
					Text       string `xml:",chardata"`
					Descriptor string `xml:"Descriptor,attr"`
					ID         struct {
						Text string `xml:",chardata"`
						Type string `xml:"type,attr"`
					} `xml:"ID"`
				} `xml:"Transaction_Type_Reference"`
			} `xml:"Transaction_Type_References"`
			SubscriberReference struct {
				Text       string `xml:",chardata"`
				Descriptor string `xml:"Descriptor,attr"`
				ID         struct {
					Text string `xml:",chardata"`
					Type string `xml:"type,attr"`
				} `xml:"ID"`
			} `xml:"Subscriber_Reference"`
		} `xml:"Transaction_Log_Criteria_Data"`
		OrganizationReference struct {
			Text       string `xml:",chardata"`
			Descriptor string `xml:"Descriptor,attr"`
			ID         struct {
				Text string `xml:",chardata"`
				Type string `xml:"type,attr"`
			} `xml:"ID"`
		} `xml:"Organization_Reference"`
		CountryReference struct {
			Text       string `xml:",chardata"`
			Descriptor string `xml:"Descriptor,attr"`
			ID         struct {
				Text string `xml:",chardata"`
				Type string `xml:"type,attr"`
			} `xml:"ID"`
		} `xml:"Country_Reference"`
		IncludeSubordinateOrganizations struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Subordinate_Organizations"`
		PositionReference struct {
			Text       string `xml:",chardata"`
			Descriptor string `xml:"Descriptor,attr"`
			ID         struct {
				Text string `xml:",chardata"`
				Type string `xml:"type,attr"`
			} `xml:"ID"`
		} `xml:"Position_Reference"`
		EventReference struct {
			Text       string `xml:",chardata"`
			Descriptor string `xml:"Descriptor,attr"`
			ID         struct {
				Text string `xml:",chardata"`
				Type string `xml:"type,attr"`
			} `xml:"ID"`
		} `xml:"Event_Reference"`
		BenefitPlanReference struct {
			Text       string `xml:",chardata"`
			Descriptor string `xml:"Descriptor,attr"`
			ID         struct {
				Text string `xml:",chardata"`
				Type string `xml:"type,attr"`
			} `xml:"ID"`
		} `xml:"Benefit_Plan_Reference"`
		FieldAndParameterCriteriaData struct {
			Text              string `xml:",chardata"`
			ProviderReference struct {
				Text       string `xml:",chardata"`
				Descriptor string `xml:"Descriptor,attr"`
				ID         struct {
					Text string `xml:",chardata"`
					Type string `xml:"type,attr"`
				} `xml:"ID"`
			} `xml:"Provider_Reference"`
		} `xml:"Field_And_Parameter_Criteria_Data"`
		NationalIDCriteriaData struct {
			Text         string `xml:",chardata"`
			IdentifierID struct {
				Text string `xml:",chardata"`
			} `xml:"Identifier_ID"`
			NationalIDTypeReference struct {
				Text       string `xml:",chardata"`
				Descriptor string `xml:"Descriptor,attr"`
				ID         struct {
					Text string `xml:",chardata"`
					Type string `xml:"type,attr"`
				} `xml:"ID"`
			} `xml:"National_ID_Type_Reference"`
			CountryReference struct {
				Text       string `xml:",chardata"`
				Descriptor string `xml:"Descriptor,attr"`
				ID         struct {
					Text string `xml:",chardata"`
					Type string `xml:"type,attr"`
				} `xml:"ID"`
			} `xml:"Country_Reference"`
		} `xml:"National_ID_Criteria_Data"`
		ExcludeInactiveWorkers struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Inactive_Workers"`
		ExcludeEmployees struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Employees"`
		ExcludeContingentWorkers struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Contingent_Workers"`
		EligibilityCriteriaData struct {
			Text           string `xml:",chardata"`
			FieldReference struct {
				Text       string `xml:",chardata"`
				Descriptor string `xml:"Descriptor,attr"`
				ID         struct {
					Text       string `xml:",chardata"`
					Type       string `xml:"type,attr"`
					ParentID   string `xml:"parent_id,attr"`
					ParentType string `xml:"parent_type,attr"`
				} `xml:"ID"`
			} `xml:"Field_Reference"`
			AsOfEffectiveDate struct {
				Text string `xml:",chardata"`
			} `xml:"As_Of_Effective_Date"`
			AsOfEntryDateTime struct {
				Text string `xml:",chardata"`
			} `xml:"As_Of_Entry_DateTime"`
		} `xml:"Eligibility_Criteria_Data"`
		UniversalIDReference struct {
			Text       string `xml:",chardata"`
			Descriptor string `xml:"Descriptor,attr"`
			ID         struct {
				Text string `xml:",chardata"`
				Type string `xml:"type,attr"`
			} `xml:"ID"`
		} `xml:"Universal_ID_Reference"`
	} `xml:"Request_Criteria"`
	ResponseFilter struct {
		Text              string `xml:",chardata"`
		AsOfEffectiveDate struct {
			Text string `xml:",chardata"`
		} `xml:"As_Of_Effective_Date"`
		AsOfEntryDateTime struct {
			Text string `xml:",chardata"`
		} `xml:"As_Of_Entry_DateTime"`
		Page struct {
			Text string `xml:",chardata"`
		} `xml:"Page"`
		Count struct {
			Text string `xml:",chardata"`
		} `xml:"Count"`
	} `xml:"Response_Filter"`
	ResponseGroup struct {
		Text             string `xml:",chardata"`
		IncludeReference struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Reference"`
		IncludePersonalInformation struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Personal_Information"`
		ShowAllPersonalInformation struct {
			Text string `xml:",chardata"`
		} `xml:"Show_All_Personal_Information"`
		IncludeAdditionalJobs struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Additional_Jobs"`
		IncludeEmploymentInformation struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Employment_Information"`
		IncludeCompensation struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Compensation"`
		IncludeOrganizations struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Organizations"`
		ExcludeOrganizationSupportRoleData struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Organization_Support_Role_Data"`
		ExcludeLocationHierarchies struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Location_Hierarchies"`
		ExcludeCostCenters struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Cost_Centers"`
		ExcludeCostCenterHierarchies struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Cost_Center_Hierarchies"`
		ExcludeCompanies struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Companies"`
		ExcludeCompanyHierarchies struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Company_Hierarchies"`
		ExcludeMatrixOrganizations struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Matrix_Organizations"`
		ExcludePayGroups struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Pay_Groups"`
		ExcludeRegions struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Regions"`
		ExcludeRegionHierarchies struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Region_Hierarchies"`
		ExcludeSupervisoryOrganizations struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Supervisory_Organizations"`
		ExcludeTeams struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Teams"`
		ExcludeCustomOrganizations struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Custom_Organizations"`
		IncludeRoles struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Roles"`
		IncludeManagementChainData struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Management_Chain_Data"`
		IncludeMultipleManagersInManagementChainData struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Multiple_Managers_in_Management_Chain_Data"`
		IncludeBenefitEnrollments struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Benefit_Enrollments"`
		IncludeBenefitEligibility struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Benefit_Eligibility"`
		IncludeRelatedPersons struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Related_Persons"`
		IncludeQualifications struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Qualifications"`
		IncludeEmployeeReview struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Employee_Review"`
		IncludeGoals struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Goals"`
		IncludeDevelopmentItems struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Development_Items"`
		IncludeSkills struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Skills"`
		IncludePhoto struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Photo"`
		IncludeWorkerDocuments struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Worker_Documents"`
		IncludeTransactionLogData struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Transaction_Log_Data"`
		IncludeSubeventsForCorrectedTransaction struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Subevents_for_Corrected_Transaction"`
		IncludeSubeventsForRescindedTransaction struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Subevents_for_Rescinded_Transaction"`
		IncludeSuccessionProfile struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Succession_Profile"`
		IncludeTalentAssessment struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Talent_Assessment"`
		IncludeEmployeeContractData struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Employee_Contract_Data"`
		IncludeContractsForTerminatedWorkers struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Contracts_for_Terminated_Workers"`
		IncludeCollectiveAgreementData struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Collective_Agreement_Data"`
		IncludeProbationPeriodData struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Probation_Period_Data"`
		IncludeExtendedEmployeeContractDetails struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Extended_Employee_Contract_Details"`
		IncludeFeedbackReceived struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Feedback_Received"`
		IncludeUserAccount struct {
			Text string `xml:",chardata"`
		} `xml:"Include_User_Account"`
		IncludeCareer struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Career"`
		IncludeAccountProvisioning struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Account_Provisioning"`
		IncludeBackgroundCheckData struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Background_Check_Data"`
		IncludeContingentWorkerTaxAuthorityFormInformation struct {
			Text string `xml:",chardata"`
		} `xml:"Include_Contingent_Worker_Tax_Authority_Form_Information"`
		ExcludeFunds struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Funds"`
		ExcludeFundHierarchies struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Fund_Hierarchies"`
		ExcludeGrants struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Grants"`
		ExcludeGrantHierarchies struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Grant_Hierarchies"`
		ExcludeBusinessUnits struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Business_Units"`
		ExcludeBusinessUnitHierarchies struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Business_Unit_Hierarchies"`
		ExcludePrograms struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Programs"`
		ExcludeProgramHierarchies struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Program_Hierarchies"`
		ExcludeGifts struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Gifts"`
		ExcludeGiftHierarchies struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Gift_Hierarchies"`
		ExcludeRetireeOrganizations struct {
			Text string `xml:",chardata"`
		} `xml:"Exclude_Retiree_Organizations"`
	} `xml:"Response_Group"`
}
