// Programmatically generated by gen_structs.py
package put_applicant_response

import "encoding/xml"

type PutApplicantResponse struct {
    XMLName xml.Name `xml:"Put_Applicant_Response"`
    Version *string `xml:"version,attr,omitempty"`
    ApplicantReference *ApplicantReference `xml:"Applicant_Reference,omitempty"`
    ExceptionsResponseData *ExceptionsResponseData `xml:"Exceptions_Response_Data,omitempty"`
}

type ApplicantReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Id struct {
    Type *string `xml:"type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type ExceptionsResponseData struct {
    ExceptionsData *ExceptionsData `xml:"Exceptions_Data,omitempty"`
}

type ExceptionsData struct {
    ExceptionData *ExceptionData `xml:"Exception_Data,omitempty"`
}

type ExceptionData struct {
    Classification *string `xml:"Classification,omitempty"`
    Message *string `xml:"Message,omitempty"`
}

