// Programmatically generated by gen_structs.py
package employee_personal_info_get

import "encoding/xml"

type EmployeePersonalInfoGet struct {
    XMLName xml.Name `xml:"wd:Employee_Personal_Info_Get"`
    XMLNamespace *string `xml:"xmlns:wd,attr,omitempty"`
    AsOfDate *string `xml:"wd:As_Of_Date,attr,omitempty"`
    AsOfMoment *string `xml:"wd:As_Of_Moment,attr,omitempty"`
    Version *string `xml:"wd:version,attr,omitempty"`
    EmployeeReference *EmployeeReference `xml:"wd:Employee_Reference,omitempty"`
}

type EmployeeReference struct {
    IntegrationIdReference *IntegrationIdReference `xml:"wd:Integration_ID_Reference,omitempty"`
}

type IntegrationIdReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Id struct {
    SystemId *string `xml:"wd:System_ID,attr,omitempty"`
    Value *string `xml:",chardata"`
}

