// Programmatically generated by gen_structs.py
package get_change_personal_information_request

import "encoding/xml"

type GetChangePersonalInformationRequest struct {
    XMLName xml.Name `xml:"wd:Get_Change_Personal_Information_Request"`
    XMLNamespace *string `xml:"xmlns:wd,attr,omitempty"`
    Version *string `xml:"wd:version,attr,omitempty"`
    RequestReferences *RequestReferences `xml:"wd:Request_References,omitempty"`
    ResponseFilter *ResponseFilter `xml:"wd:Response_Filter,omitempty"`
    RequestCriteriaData *RequestCriteriaData `xml:"wd:Request_Criteria_Data,omitempty"`
}

type RequestReferences struct {
    PersonReference *PersonReference `xml:"wd:Person_Reference,omitempty"`
    UniversalIdReference *UniversalIdReference `xml:"wd:Universal_ID_Reference,omitempty"`
}

type PersonReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Id struct {
    Type *string `xml:"wd:type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type UniversalIdReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ResponseFilter struct {
    AsOfEffectiveDate *string `xml:"wd:As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"wd:As_Of_Entry_DateTime,omitempty"`
    Page *int `xml:"wd:Page,omitempty"`
    Count *int `xml:"wd:Count,omitempty"`
}

type RequestCriteriaData struct {
    PersonTypeCriteriaData *PersonTypeCriteriaData `xml:"wd:Person_Type_Criteria_Data,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
}

type PersonTypeCriteriaData struct {
    IncludeAcademicAffiliates *bool `xml:"wd:Include_Academic_Affiliates,omitempty"`
    IncludeExternalCommitteeMembers *bool `xml:"wd:Include_External_Committee_Members,omitempty"`
    IncludeExternalStudentRecords *bool `xml:"wd:Include_External_Student_Records,omitempty"`
    IncludeStudentProspectRecords *bool `xml:"wd:Include_Student_Prospect_Records,omitempty"`
    IncludeStudentRecords *bool `xml:"wd:Include_Student_Records,omitempty"`
    IncludeWorkers *bool `xml:"wd:Include_Workers,omitempty"`
}

type CountryReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

