// Programmatically generated by gen_structs.py
package get_change_home_contact_information_response

import "encoding/xml"

type GetChangeHomeContactInformationResponse struct {
    XMLName xml.Name `xml:"Get_Change_Home_Contact_Information_Response"`
    Version *string `xml:"version,attr,omitempty"`
    RequestReferences *RequestReferences `xml:"Request_References,omitempty"`
    ResponseFilter *ResponseFilter `xml:"Response_Filter,omitempty"`
    ResponseResults *ResponseResults `xml:"Response_Results,omitempty"`
    ResponseData *ResponseData `xml:"Response_Data,omitempty"`
}

type RequestReferences struct {
    PersonReference *PersonReference `xml:"Person_Reference,omitempty"`
    UniversalIdReference *UniversalIdReference `xml:"Universal_ID_Reference,omitempty"`
}

type PersonReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Id struct {
    Type *string `xml:"type,attr,omitempty"`
    Value *string `xml:",chardata"`
    ParentId *string `xml:"parent_id,attr,omitempty"`
    ParentType *string `xml:"parent_type,attr,omitempty"`
}

type UniversalIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ResponseFilter struct {
    AsOfEffectiveDate *string `xml:"As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"As_Of_Entry_DateTime,omitempty"`
    Page *int `xml:"Page,omitempty"`
    Count *int `xml:"Count,omitempty"`
}

type ResponseResults struct {
    TotalResults *int `xml:"Total_Results,omitempty"`
    TotalPages *int `xml:"Total_Pages,omitempty"`
    PageResults *int `xml:"Page_Results,omitempty"`
    Page *int `xml:"Page,omitempty"`
}

type ResponseData struct {
    ChangeHomeContactInformation *ChangeHomeContactInformation `xml:"Change_Home_Contact_Information,omitempty"`
}

type ChangeHomeContactInformation struct {
    PersonReference *PersonReference `xml:"Person_Reference,omitempty"`
    ChangeHomeContactInformationData *ChangeHomeContactInformationData `xml:"Change_Home_Contact_Information_Data,omitempty"`
}

type ChangeHomeContactInformationData struct {
    PersonReference *PersonReference `xml:"Person_Reference,omitempty"`
    UniversalIdReference *UniversalIdReference `xml:"Universal_ID_Reference,omitempty"`
    EventEffectiveDate *string `xml:"Event_Effective_Date,omitempty"`
    PersonContactInformationData *PersonContactInformationData `xml:"Person_Contact_Information_Data,omitempty"`
}

type PersonContactInformationData struct {
    PersonAddressInformationData *PersonAddressInformationData `xml:"Person_Address_Information_Data,omitempty"`
    PersonPhoneInformationData *PersonPhoneInformationData `xml:"Person_Phone_Information_Data,omitempty"`
    PersonEmailInformationData *PersonEmailInformationData `xml:"Person_Email_Information_Data,omitempty"`
    PersonInstantMessengerInformationData *PersonInstantMessengerInformationData `xml:"Person_Instant_Messenger_Information_Data,omitempty"`
    PersonWebAddressInformationData *PersonWebAddressInformationData `xml:"Person_Web_Address_Information_Data,omitempty"`
}

type PersonAddressInformationData struct {
    ReplaceAll *string `xml:"Replace_All,attr,omitempty"`
    AddressInformationData *AddressInformationData `xml:"Address_Information_Data,omitempty"`
}

type AddressInformationData struct {
    AddressFormatType *string `xml:"Address_Format_Type,attr,omitempty"`
    Delete *string `xml:"Delete,attr,omitempty"`
    EffectiveDate *string `xml:"Effective_Date,attr,omitempty"`
    AddressData *AddressData `xml:"Address_Data,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
    NumberOfDays *int `xml:"Number_of_Days,omitempty"`
    DaysOfTheWeekReference *DaysOfTheWeekReference `xml:"Days_of_the_Week_Reference,omitempty"`
    AddressReference *AddressReference `xml:"Address_Reference,omitempty"`
    AddressId *string `xml:"Address_ID,omitempty"`
}

type AddressData struct {
    FormattedAddress *string `xml:"Formatted_Address,attr,omitempty"`
    DefaultAddress *string `xml:"Default_Address,attr,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    CountryRegionReference *CountryRegionReference `xml:"Country_Region_Reference,omitempty"`
    CountryRegionDescriptor *string `xml:"Country_Region_Descriptor,omitempty"`
    AddressLineData *AddressLineData `xml:"Address_Line_Data,omitempty"`
    SubregionData *SubregionData `xml:"Subregion_Data,omitempty"`
    SubmunicipalityData *SubmunicipalityData `xml:"Submunicipality_Data,omitempty"`
    PostalCode *string `xml:"Postal_Code,omitempty"`
    Municipality *string `xml:"Municipality,omitempty"`
    MunicipalityLocal *string `xml:"Municipality_Local,omitempty"`
    CountryCityReference *CountryCityReference `xml:"Country_City_Reference,omitempty"`
}

type CountryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CountryRegionReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AddressLineData struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type SubregionData struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type SubmunicipalityData struct {
    AddressComponentName *string `xml:"Address_Component_Name,attr,omitempty"`
    Type *string `xml:"Type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type CountryCityReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type UsageData struct {
    Public *string `xml:"Public,attr,omitempty"`
    TypeData *TypeData `xml:"Type_Data,omitempty"`
    UseForReference *UseForReference `xml:"Use_For_Reference,omitempty"`
    UseForTenantedReference *UseForTenantedReference `xml:"Use_For_Tenanted_Reference,omitempty"`
    Comments *string `xml:"Comments,omitempty"`
}

type TypeData struct {
    Primary *string `xml:"Primary,attr,omitempty"`
    TypeReference *TypeReference `xml:"Type_Reference,omitempty"`
}

type TypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type UseForReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type UseForTenantedReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type DaysOfTheWeekReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AddressReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PersonPhoneInformationData struct {
    ReplaceAll *string `xml:"Replace_All,attr,omitempty"`
    PhoneInformationData *PhoneInformationData `xml:"Phone_Information_Data,omitempty"`
}

type PhoneInformationData struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    PhoneData *PhoneData `xml:"Phone_Data,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
    PhoneReference *PhoneReference `xml:"Phone_Reference,omitempty"`
    PhoneId *string `xml:"Phone_ID,omitempty"`
}

type PhoneData struct {
    FormattedPhone *string `xml:"Formatted_Phone,attr,omitempty"`
    DeviceTypeReference *DeviceTypeReference `xml:"Device_Type_Reference,omitempty"`
    CountryCodeReference *CountryCodeReference `xml:"Country_Code_Reference,omitempty"`
    CompletePhoneNumber *string `xml:"Complete_Phone_Number,omitempty"`
    Extension *string `xml:"Extension,omitempty"`
}

type DeviceTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type CountryCodeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PhoneReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PersonEmailInformationData struct {
    ReplaceAll *string `xml:"Replace_All,attr,omitempty"`
    EmailInformationData *EmailInformationData `xml:"Email_Information_Data,omitempty"`
}

type EmailInformationData struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    EmailData *EmailData `xml:"Email_Data,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
    EmailReference *EmailReference `xml:"Email_Reference,omitempty"`
    EmailId *string `xml:"Email_ID,omitempty"`
}

type EmailData struct {
    EmailAddress *string `xml:"Email_Address,omitempty"`
    EmailComment *string `xml:"Email_Comment,omitempty"`
}

type EmailReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PersonInstantMessengerInformationData struct {
    ReplaceAll *string `xml:"Replace_All,attr,omitempty"`
    PersonInstantMessengerData *PersonInstantMessengerData `xml:"Person_Instant_Messenger_Data,omitempty"`
}

type PersonInstantMessengerData struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    InstantMessengerData *InstantMessengerData `xml:"Instant_Messenger_Data,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
    InstantMessengerReference *InstantMessengerReference `xml:"Instant_Messenger_Reference,omitempty"`
    InstantMessengerId *string `xml:"Instant_Messenger_ID,omitempty"`
}

type InstantMessengerData struct {
    InstantMessengerTypeReference *InstantMessengerTypeReference `xml:"Instant_Messenger_Type_Reference,omitempty"`
    InstantMessengerAddress *string `xml:"Instant_Messenger_Address,omitempty"`
    InstantMessengerComment *string `xml:"Instant_Messenger_Comment,omitempty"`
}

type InstantMessengerTypeReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type InstantMessengerReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PersonWebAddressInformationData struct {
    ReplaceAll *string `xml:"Replace_All,attr,omitempty"`
    PersonWebAddressData *PersonWebAddressData `xml:"Person_Web_Address_Data,omitempty"`
}

type PersonWebAddressData struct {
    Delete *string `xml:"Delete,attr,omitempty"`
    WebAddressData *WebAddressData `xml:"Web_Address_Data,omitempty"`
    UsageData *UsageData `xml:"Usage_Data,omitempty"`
    WebAddressReference *WebAddressReference `xml:"Web_Address_Reference,omitempty"`
    WebAddressId *string `xml:"Web_Address_ID,omitempty"`
}

type WebAddressData struct {
    WebAddress *string `xml:"Web_Address,omitempty"`
    WebAddressComment *string `xml:"Web_Address_Comment,omitempty"`
}

type WebAddressReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

