// Programmatically generated by gen_structs.py
package get_workers_request

import "encoding/xml"

type GetWorkersRequest struct {
    XMLName xml.Name `xml:"wd:Get_Workers_Request"`
    XMLNamespace *string `xml:"xmlns:wd,attr,omitempty"`
    Version *string `xml:"wd:version,attr,omitempty"`
    RequestReferences *RequestReferences `xml:"wd:Request_References,omitempty"`
    RequestCriteria *RequestCriteria `xml:"wd:Request_Criteria,omitempty"`
    ResponseFilter *ResponseFilter `xml:"wd:Response_Filter,omitempty"`
    ResponseGroup *ResponseGroup `xml:"wd:Response_Group,omitempty"`
}

type RequestReferences struct {
    SkipNonExistingInstances *string `xml:"wd:Skip_Non_Existing_Instances,attr,omitempty"`
    IgnoreInvalidReferences *string `xml:"wd:Ignore_Invalid_References,attr,omitempty"`
    WorkerReference *WorkerReference `xml:"wd:Worker_Reference,omitempty"`
}

type WorkerReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type Id struct {
    Type *string `xml:"wd:type,attr,omitempty"`
    Value *string `xml:",chardata"`
    ParentId *string `xml:"wd:parent_id,attr,omitempty"`
    ParentType *string `xml:"wd:parent_type,attr,omitempty"`
}

type RequestCriteria struct {
    TransactionLogCriteriaData *TransactionLogCriteriaData `xml:"wd:Transaction_Log_Criteria_Data,omitempty"`
    OrganizationReference *OrganizationReference `xml:"wd:Organization_Reference,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
    IncludeSubordinateOrganizations *bool `xml:"wd:Include_Subordinate_Organizations,omitempty"`
    PositionReference *PositionReference `xml:"wd:Position_Reference,omitempty"`
    EventReference *EventReference `xml:"wd:Event_Reference,omitempty"`
    BenefitPlanReference *BenefitPlanReference `xml:"wd:Benefit_Plan_Reference,omitempty"`
    FieldAndParameterCriteriaData *FieldAndParameterCriteriaData `xml:"wd:Field_And_Parameter_Criteria_Data,omitempty"`
    NationalIdCriteriaData *NationalIdCriteriaData `xml:"wd:National_ID_Criteria_Data,omitempty"`
    ExcludeInactiveWorkers *bool `xml:"wd:Exclude_Inactive_Workers,omitempty"`
    ExcludeEmployees *bool `xml:"wd:Exclude_Employees,omitempty"`
    ExcludeContingentWorkers *bool `xml:"wd:Exclude_Contingent_Workers,omitempty"`
    EligibilityCriteriaData *EligibilityCriteriaData `xml:"wd:Eligibility_Criteria_Data,omitempty"`
    UniversalIdReference *UniversalIdReference `xml:"wd:Universal_ID_Reference,omitempty"`
}

type TransactionLogCriteriaData struct {
    TransactionDateRangeData *TransactionDateRangeData `xml:"wd:Transaction_Date_Range_Data,omitempty"`
    TransactionTypeReferences *TransactionTypeReferences `xml:"wd:Transaction_Type_References,omitempty"`
    SubscriberReference *SubscriberReference `xml:"wd:Subscriber_Reference,omitempty"`
}

type TransactionDateRangeData struct {
    UpdatedFrom *string `xml:"wd:Updated_From,omitempty"`
    UpdatedThrough *string `xml:"wd:Updated_Through,omitempty"`
    EffectiveFrom *string `xml:"wd:Effective_From,omitempty"`
    EffectiveThrough *string `xml:"wd:Effective_Through,omitempty"`
}

type TransactionTypeReferences struct {
    TransactionTypeReference *TransactionTypeReference `xml:"wd:Transaction_Type_Reference,omitempty"`
}

type TransactionTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type SubscriberReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type OrganizationReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type CountryReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type PositionReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type EventReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type BenefitPlanReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type FieldAndParameterCriteriaData struct {
    ProviderReference *ProviderReference `xml:"wd:Provider_Reference,omitempty"`
}

type ProviderReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type NationalIdCriteriaData struct {
    IdentifierId *string `xml:"wd:Identifier_ID,omitempty"`
    NationalIdTypeReference *NationalIdTypeReference `xml:"wd:National_ID_Type_Reference,omitempty"`
    CountryReference *CountryReference `xml:"wd:Country_Reference,omitempty"`
}

type NationalIdTypeReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type EligibilityCriteriaData struct {
    FieldReference *FieldReference `xml:"wd:Field_Reference,omitempty"`
    AsOfEffectiveDate *string `xml:"wd:As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"wd:As_Of_Entry_DateTime,omitempty"`
}

type FieldReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type UniversalIdReference struct {
    Descriptor *string `xml:"wd:Descriptor,attr,omitempty"`
    Id *Id `xml:"wd:ID,omitempty"`
}

type ResponseFilter struct {
    AsOfEffectiveDate *string `xml:"wd:As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"wd:As_Of_Entry_DateTime,omitempty"`
    Page *int `xml:"wd:Page,omitempty"`
    Count *int `xml:"wd:Count,omitempty"`
}

type ResponseGroup struct {
    IncludeReference *bool `xml:"wd:Include_Reference,omitempty"`
    IncludePersonalInformation *bool `xml:"wd:Include_Personal_Information,omitempty"`
    ShowAllPersonalInformation *bool `xml:"wd:Show_All_Personal_Information,omitempty"`
    IncludeAdditionalJobs *bool `xml:"wd:Include_Additional_Jobs,omitempty"`
    IncludeEmploymentInformation *bool `xml:"wd:Include_Employment_Information,omitempty"`
    IncludeCompensation *bool `xml:"wd:Include_Compensation,omitempty"`
    IncludeOrganizations *bool `xml:"wd:Include_Organizations,omitempty"`
    ExcludeOrganizationSupportRoleData *bool `xml:"wd:Exclude_Organization_Support_Role_Data,omitempty"`
    ExcludeLocationHierarchies *bool `xml:"wd:Exclude_Location_Hierarchies,omitempty"`
    ExcludeCostCenters *bool `xml:"wd:Exclude_Cost_Centers,omitempty"`
    ExcludeCostCenterHierarchies *bool `xml:"wd:Exclude_Cost_Center_Hierarchies,omitempty"`
    ExcludeCompanies *bool `xml:"wd:Exclude_Companies,omitempty"`
    ExcludeCompanyHierarchies *bool `xml:"wd:Exclude_Company_Hierarchies,omitempty"`
    ExcludeMatrixOrganizations *bool `xml:"wd:Exclude_Matrix_Organizations,omitempty"`
    ExcludePayGroups *bool `xml:"wd:Exclude_Pay_Groups,omitempty"`
    ExcludeRegions *bool `xml:"wd:Exclude_Regions,omitempty"`
    ExcludeRegionHierarchies *bool `xml:"wd:Exclude_Region_Hierarchies,omitempty"`
    ExcludeSupervisoryOrganizations *bool `xml:"wd:Exclude_Supervisory_Organizations,omitempty"`
    ExcludeTeams *bool `xml:"wd:Exclude_Teams,omitempty"`
    ExcludeCustomOrganizations *bool `xml:"wd:Exclude_Custom_Organizations,omitempty"`
    IncludeRoles *bool `xml:"wd:Include_Roles,omitempty"`
    IncludeManagementChainData *bool `xml:"wd:Include_Management_Chain_Data,omitempty"`
    IncludeMultipleManagersInManagementChainData *bool `xml:"wd:Include_Multiple_Managers_in_Management_Chain_Data,omitempty"`
    IncludeBenefitEnrollments *bool `xml:"wd:Include_Benefit_Enrollments,omitempty"`
    IncludeBenefitEligibility *bool `xml:"wd:Include_Benefit_Eligibility,omitempty"`
    IncludeRelatedPersons *bool `xml:"wd:Include_Related_Persons,omitempty"`
    IncludeQualifications *bool `xml:"wd:Include_Qualifications,omitempty"`
    IncludeEmployeeReview *bool `xml:"wd:Include_Employee_Review,omitempty"`
    IncludeGoals *bool `xml:"wd:Include_Goals,omitempty"`
    IncludeDevelopmentItems *bool `xml:"wd:Include_Development_Items,omitempty"`
    IncludeSkills *bool `xml:"wd:Include_Skills,omitempty"`
    IncludePhoto *bool `xml:"wd:Include_Photo,omitempty"`
    IncludeWorkerDocuments *bool `xml:"wd:Include_Worker_Documents,omitempty"`
    IncludeTransactionLogData *bool `xml:"wd:Include_Transaction_Log_Data,omitempty"`
    IncludeSubeventsForCorrectedTransaction *bool `xml:"wd:Include_Subevents_for_Corrected_Transaction,omitempty"`
    IncludeSubeventsForRescindedTransaction *bool `xml:"wd:Include_Subevents_for_Rescinded_Transaction,omitempty"`
    IncludeSuccessionProfile *bool `xml:"wd:Include_Succession_Profile,omitempty"`
    IncludeTalentAssessment *bool `xml:"wd:Include_Talent_Assessment,omitempty"`
    IncludeEmployeeContractData *bool `xml:"wd:Include_Employee_Contract_Data,omitempty"`
    IncludeContractsForTerminatedWorkers *bool `xml:"wd:Include_Contracts_for_Terminated_Workers,omitempty"`
    IncludeCollectiveAgreementData *bool `xml:"wd:Include_Collective_Agreement_Data,omitempty"`
    IncludeProbationPeriodData *bool `xml:"wd:Include_Probation_Period_Data,omitempty"`
    IncludeExtendedEmployeeContractDetails *bool `xml:"wd:Include_Extended_Employee_Contract_Details,omitempty"`
    IncludeFeedbackReceived *bool `xml:"wd:Include_Feedback_Received,omitempty"`
    IncludeUserAccount *bool `xml:"wd:Include_User_Account,omitempty"`
    IncludeCareer *bool `xml:"wd:Include_Career,omitempty"`
    IncludeAccountProvisioning *bool `xml:"wd:Include_Account_Provisioning,omitempty"`
    IncludeBackgroundCheckData *bool `xml:"wd:Include_Background_Check_Data,omitempty"`
    IncludeContingentWorkerTaxAuthorityFormInformation *bool `xml:"wd:Include_Contingent_Worker_Tax_Authority_Form_Information,omitempty"`
    ExcludeFunds *bool `xml:"wd:Exclude_Funds,omitempty"`
    ExcludeFundHierarchies *bool `xml:"wd:Exclude_Fund_Hierarchies,omitempty"`
    ExcludeGrants *bool `xml:"wd:Exclude_Grants,omitempty"`
    ExcludeGrantHierarchies *bool `xml:"wd:Exclude_Grant_Hierarchies,omitempty"`
    ExcludeBusinessUnits *bool `xml:"wd:Exclude_Business_Units,omitempty"`
    ExcludeBusinessUnitHierarchies *bool `xml:"wd:Exclude_Business_Unit_Hierarchies,omitempty"`
    ExcludePrograms *bool `xml:"wd:Exclude_Programs,omitempty"`
    ExcludeProgramHierarchies *bool `xml:"wd:Exclude_Program_Hierarchies,omitempty"`
    ExcludeGifts *bool `xml:"wd:Exclude_Gifts,omitempty"`
    ExcludeGiftHierarchies *bool `xml:"wd:Exclude_Gift_Hierarchies,omitempty"`
    ExcludeRetireeOrganizations *bool `xml:"wd:Exclude_Retiree_Organizations,omitempty"`
}

