// Programmatically generated by gen_structs.py
package get_change_legal_name_response

import "encoding/xml"

type GetChangeLegalNameResponse struct {
    XMLName xml.Name `xml:"Get_Change_Legal_Name_Response"`
    Version *string `xml:"version,attr,omitempty"`
    RequestReferences *RequestReferences `xml:"Request_References,omitempty"`
    ResponseFilter *ResponseFilter `xml:"Response_Filter,omitempty"`
    ResponseResults *ResponseResults `xml:"Response_Results,omitempty"`
    ResponseData *ResponseData `xml:"Response_Data,omitempty"`
}

type RequestReferences struct {
    PersonReference *PersonReference `xml:"Person_Reference,omitempty"`
    UniversalIdReference *UniversalIdReference `xml:"Universal_ID_Reference,omitempty"`
}

type PersonReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type Id struct {
    Type *string `xml:"type,attr,omitempty"`
    Value *string `xml:",chardata"`
}

type UniversalIdReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ResponseFilter struct {
    AsOfEffectiveDate *string `xml:"As_Of_Effective_Date,omitempty"`
    AsOfEntryDatetime *string `xml:"As_Of_Entry_DateTime,omitempty"`
    Page *int `xml:"Page,omitempty"`
    Count *int `xml:"Count,omitempty"`
}

type ResponseResults struct {
    TotalResults *int `xml:"Total_Results,omitempty"`
    TotalPages *int `xml:"Total_Pages,omitempty"`
    PageResults *int `xml:"Page_Results,omitempty"`
    Page *int `xml:"Page,omitempty"`
}

type ResponseData struct {
    ChangeLegalName *ChangeLegalName `xml:"Change_Legal_Name,omitempty"`
}

type ChangeLegalName struct {
    PersonReference *PersonReference `xml:"Person_Reference,omitempty"`
    ChangeLegalNameData *ChangeLegalNameData `xml:"Change_Legal_Name_Data,omitempty"`
}

type ChangeLegalNameData struct {
    PersonReference *PersonReference `xml:"Person_Reference,omitempty"`
    UniversalIdReference *UniversalIdReference `xml:"Universal_ID_Reference,omitempty"`
    EffectiveDate *string `xml:"Effective_Date,omitempty"`
    NameData *NameData `xml:"Name_Data,omitempty"`
}

type NameData struct {
    FormattedName *string `xml:"Formatted_Name,attr,omitempty"`
    ReportingName *string `xml:"Reporting_Name,attr,omitempty"`
    CountryReference *CountryReference `xml:"Country_Reference,omitempty"`
    PrefixData *PrefixData `xml:"Prefix_Data,omitempty"`
    FirstName *string `xml:"First_Name,omitempty"`
    MiddleName *string `xml:"Middle_Name,omitempty"`
    LastName *string `xml:"Last_Name,omitempty"`
    SecondaryLastName *string `xml:"Secondary_Last_Name,omitempty"`
    TertiaryLastName *string `xml:"Tertiary_Last_Name,omitempty"`
    LocalNameDetailData *LocalNameDetailData `xml:"Local_Name_Detail_Data,omitempty"`
    SuffixData *SuffixData `xml:"Suffix_Data,omitempty"`
    FullNameForSingaporeAndMalaysia *string `xml:"Full_Name_for_Singapore_and_Malaysia,omitempty"`
}

type CountryReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type PrefixData struct {
    TitleReference *TitleReference `xml:"Title_Reference,omitempty"`
    TitleDescriptor *string `xml:"Title_Descriptor,omitempty"`
    SalutationReference *SalutationReference `xml:"Salutation_Reference,omitempty"`
}

type TitleReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type SalutationReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type LocalNameDetailData struct {
    LocalName *string `xml:"Local_Name,attr,omitempty"`
    LocalScript *string `xml:"Local_Script,attr,omitempty"`
    FirstName *string `xml:"First_Name,omitempty"`
    MiddleName *string `xml:"Middle_Name,omitempty"`
    LastName *string `xml:"Last_Name,omitempty"`
    SecondaryLastName *string `xml:"Secondary_Last_Name,omitempty"`
    FirstName2 *string `xml:"First_Name_2,omitempty"`
    MiddleName2 *string `xml:"Middle_Name_2,omitempty"`
    LastName2 *string `xml:"Last_Name_2,omitempty"`
    SecondaryLastName2 *string `xml:"Secondary_Last_Name_2,omitempty"`
}

type SuffixData struct {
    SocialSuffixReference *SocialSuffixReference `xml:"Social_Suffix_Reference,omitempty"`
    SocialSuffixDescriptor *string `xml:"Social_Suffix_Descriptor,omitempty"`
    AcademicSuffixReference *AcademicSuffixReference `xml:"Academic_Suffix_Reference,omitempty"`
    HereditarySuffixReference *HereditarySuffixReference `xml:"Hereditary_Suffix_Reference,omitempty"`
    HonorarySuffixReference *HonorarySuffixReference `xml:"Honorary_Suffix_Reference,omitempty"`
    ProfessionalSuffixReference *ProfessionalSuffixReference `xml:"Professional_Suffix_Reference,omitempty"`
    ReligiousSuffixReference *ReligiousSuffixReference `xml:"Religious_Suffix_Reference,omitempty"`
    RoyalSuffixReference *RoyalSuffixReference `xml:"Royal_Suffix_Reference,omitempty"`
}

type SocialSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type AcademicSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HereditarySuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type HonorarySuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ProfessionalSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type ReligiousSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

type RoyalSuffixReference struct {
    Descriptor *string `xml:"Descriptor,attr,omitempty"`
    Id *Id `xml:"ID,omitempty"`
}

